### ISSUE TITLE
[TASK]: Look into the csv formatting for getCsv endpoint. 

### ISSUE THREAD

**Issue by Tom-Szendrey** [DARPA-ASKEM/terarium#1005]
**Describe the task**
Look into the csv formatting for getCsv endpoint. This is used in `DatasetResource` `getCsv` `csvToRecords`
This helper function should very likely be replaced by a proper library or written to be a lot more dependable. 
It is not hard to imagine a csv format that will break this helper function.

**Task Items**
- [ ] Check possible csv formats.
- [ ] Change csvToRecords or replace it all together
**Goal**
More resilient resource

**Comment by kbirk** [comment]
Fixed during migration work in https://github.com/DARPA-ASKEM/terarium/issues/2349
