### ISSUE TITLE
extraction text layer from PDF

### ISSUE THREAD

**Issue by dgauldie** [DARPA-ASKEM/Terarium#1020]
- Able to extract text layer from PDF
- To send it to MIT for model extraction

**Comment by tangopapatime** [comment]
As mentioned yesterday this issue was in review but I ran into a small little issue while cleaning up the code for the PR.  An follow up task of updating orchestration to setup the service in the stack.

https://github.com/DARPA-ASKEM/Terarium/issues/1074
