### ISSUE TITLE
Calibrate detail pane

### ISSUE THREAD

**Issue by Tom-Szendrey** [DARPA-ASKEM/Terarium#1098]
## For Input tab
1. Model diagram + equations
2. Initial model configuration  
**Note:** the above two are the same components than at the top of Simulate drilldown (coordinate with @mj3cheun )? Don't worry about the selection over the histograms.
3. Row of checkmarks to specify which parameters should be calibrated (default to all checked)
4. Data preview (should be same as what is shown in dataset drilldown) - dataset column visibility dropdown is low priority
5. Train/test ratio section (key is slider for the ratio). Default to 80:20. @mj3cheun can take over the chart?
6. Mapping table: one column for model variables, one column for data variables. The cells are dropdown selector with ability to type to select variable more quickly. For the first pass we can hard code the default mappings or just show no default values and let the user make the selections. Eventually, the initial mappings should come from TA1. Expanding a row should show the variables descriptions as seen in the Description tab table of the model/dataset object. The **Add Mapping** button should add another row for an additional mapping (only show one row by default or the amount of rows found by TA1 eventually).
7. The Run button at the top should be disabled until the minimum input requirements are met (at least one mapping and at least one parameter checked).
![Image](https://github.com/DARPA-ASKEM/Terarium/assets/42645294/a4ef2b90-5f45-4603-926e-b4275eee77fb)
## For output tab
1. Output tab should be accessible before/while/after calibrate is running. 
2. For the first pass, can ignore the top charts. Start with adding the bottom charts  (@mj3cheun) - one chart per variable in the mapping should be shown by default. The dataset variables (one per chart) should be visible right away (in black) - even before running anything. Can ignore intermediary results for the first pass and just plot the final (green) line once calibration results are in (i.e. using the calibrated values in a simulate run).
3. New model configuration: fill table with new parameter values when they become available.
4. Ability to rename the new configuration. Note: this new configuration should also be added in the model page at the bottom of the configuration table.

![Image](https://github.com/DARPA-ASKEM/Terarium/assets/42645294/e9d0a8e6-cf80-4cc2-ab2d-bef6a1ecfee1)

**Comment by shawnyama** [comment]
Reopen because only v0 is done - the listed features aren't fully implemented
