### ISSUE TITLE
[FEAT]: Creating new configurations from the Simulations screen

### ISSUE THREAD

**Issue by jamiewaese-uncharted** [DARPA-ASKEM/Terarium#1147]
Although users can create model configurations on the Model screen, it would be more efficient if they can also do this from the Simulation screen.

Here are some designs to describe that flow:
![Creating new configurations from the simulation screen 1](https://github.com/DARPA-ASKEM/Terarium/assets/120480244/981135fe-0e39-469e-a3a1-7e9c1b88a6ca)

![Creating new configurations from the simulation screen 2](https://github.com/DARPA-ASKEM/Terarium/assets/120480244/a007c1fa-15ab-4a33-87b1-f70cdf83cb6a)

![Creating new configurations from the simulation screen 3](https://github.com/DARPA-ASKEM/Terarium/assets/120480244/317f1278-ea24-4c3f-858f-4ce66a1511f7)

**Comment by dgauldie** [comment]
designs have changed.
