### ISSUE TITLE
[FEAT]: Add file manager to data table on Overview page

### ISSUE THREAD

**Issue by jamiewaese-uncharted** [DARPA-ASKEM/Terarium#1172]
The data table on the Overview page is just roughed in. The intent is for it to be the main file manager for a project, where you can:
- open, rename, duplicate, delete any of the items in your resources
- add tags (this is a stretch goal)

The table ought to have a keyword search field so you can filter the table to help you find whatever you're looking for. Also sort buttons as the top of each column.

![Monosnap Terarium 2023-06-05 10-51-45](https://github.com/DARPA-ASKEM/Terarium/assets/120480244/98a3afd0-3631-496b-b753-e777a5026b6e)

It might look something like this: 
![image](https://github.com/DARPA-ASKEM/Terarium/assets/120480244/afa0225f-fd9b-459b-83a1-eae192d2e014)

**Comment by pascaleproulx** [comment]
First pass of this is done. Will close and open other issues for renaming work.
