### ISSUE TITLE
Toggle Sidebar visiblity

### ISSUE THREAD

**Issue by YohannParis** [DARPA-ASKEM/TERArium#118]
**Is your feature request related to a problem? Please describe.**
- On the homepage, the _Sidebar_ should not be visible.

**Describe the solution you'd like**
- Hide/Show the Sidebar based depending on which _Views_ is visible. Hide for `Home`, Show for the others.

**Comment by echl** [comment]
@YohannParis Should the sidebar display if the Data Explorer is open? It doesn't seem to be it's own view/component.

**Comment by YohannParis** [comment]
> @YohannParis Should the sidebar display if the Data Explorer is open? It doesn't seem to be it's own view/component.

You should not worry about that, the _Data Explorer_ will be open full-screen above everything, modal style.
