### ISSUE TITLE
[BUG]: Upload button on modal for 'Upload resources' feature doesn't work

### ISSUE THREAD

**Issue by shawnyama** [DARPA-ASKEM/Terarium#1196]
**Describe the bug**
Here I try to upload a csv and it doesn't work.

**To Reproduce**

https://github.com/DARPA-ASKEM/Terarium/assets/28237258/239caffe-f93e-4a50-8b0a-822194d5af10

**Comment by pascaleproulx** [comment]
If you click cancel, most of the time the file has been uploaded. If possible, this modal should be simplified to load data automatically after selecting a file and once uploaded the Upload button should become enabled.
