### ISSUE TITLE
[BUG]: Overview page should have its own notes

### ISSUE THREAD

**Issue by pascaleproulx** [DARPA-ASKEM/terarium#1215]
**Describe the bug**
Testing the Notes features, which is very nice!! It works (stay associated) with most tabs except for the Overview page. In that case it just shows the notes associated with the last tab that was viewed prior to switching to the Overview page (see screenshot).

**Expected behavior**
Overview page should have its own notes. Could be used to capture notes about the project.

**Screenshots**
<img width="1779" alt="image" src="https://github.com/DARPA-ASKEM/Terarium/assets/42645294/7bea6b3a-71ad-498f-8268-6c22ae513c18">

**Comment by shawnyama** [comment]
I might have fixed this in this branch https://github.com/DARPA-ASKEM/Terarium/pull/1118. Feel free to add on to it
