### ISSUE TITLE
[FEAT]: Rename PetriNet `states` and `transition` in the playground

### ISSUE THREAD

**Issue by YohannParis** [DARPA-ASKEM/Terarium#125]
**Describe the solution you'd like**
- Add UI features in the PetriNet playground to rename _states_ and _transition_
- The issue is where those names will be saved?
    - Edit the current model -> which create a new one
    - Add MetaData to the current model
    - or our version of PetriNet allows this feature, which is different than UofF PetriNet

**Comment by Tom-Szendrey** [comment]
![image](https://user-images.githubusercontent.com/17088680/202484316-69c44d53-4f8f-4d5e-8995-837ffd0a2a6e.png)

A very rough sketch of what this could like has been done. It obviously would need work put in to prevent users from breaking it but this is not a high priority at the moment. 
Just wanted to leave this here incase anyone picked up this issue
