### ISSUE TITLE
support interaction of matrices for model configuration

### ISSUE THREAD

**Issue by jamiewaese-uncharted** [DARPA-ASKEM/terarium#1250]
Here are designs for configuring a stratified model.

1. Click on any of the cells to open the modal for setting its value. Note that since this is a stratified model, the background-image of the cell is drawn as a matrix with each section colored according to the various values, like a heatmap.  
![Image](https://github.com/DARPA-ASKEM/Terarium/assets/120480244/cdaa3ca4-dab5-479c-8d3c-6d5b1cb5e037)

2) This is the standard view (the "non decomposed" view) of the Age group by Age group matrix. Note the table component, which could be built with [vue-pivot-table](https://www.npmjs.com/package/@marketconnect/vue-pivot-table), aka [this](https://seungwoo321.github.io/vue-pivottable/guide/getting-started.html) which is nicely demoed [here](https://codesandbox.io/s/vue-pivottable-ui-base-forked-34men2)

![Image](https://github.com/DARPA-ASKEM/Terarium/assets/120480244/e5042b8b-8dc5-480b-8c8d-95fb19c4ddc6)

3) This is the "decomposed" view -- note the toggle switch is turned on. In this view we have two accordions: one for base model settings, the other for the strata model settings. The base model setting is just a single value so there's only one field to fill in. The strata model settings can be a large matrix so you may not want to enter every field manually. It comes with a dropdown menu with a bunch of preset matrix configurations (e.g., Uniform distribution on diagonal). You can auto populate the matrix by selecting different options. But you can also edit the cells of the matrix manually, just by clicking to select a cell and typing the new value. Press return or click away to close edit mode.  
![Image](https://github.com/DARPA-ASKEM/Terarium/assets/120480244/da7fd55d-4ffd-49bf-8441-a31dc6fc94f3)

4) Configuring a more complex model works the same way. We now have two dimension tiles in the rows and columns slots. You can drag them to re-order the table layout. You can click on to them open a multi-select menu, which allows you to toggle off rows you're not interested in.
![Image](https://github.com/DARPA-ASKEM/Terarium/assets/120480244/7265d90e-373e-444d-91e4-032478a44318)

This is already built into vue-pivot-table
![Image](https://github.com/DARPA-ASKEM/Terarium/assets/120480244/b48f1516-7f36-4a10-bb04-cee16b83ae3d)

5) Here is the "decomposed" view of the more complex model. Note the toggle is now on.
![Image](https://github.com/DARPA-ASKEM/Terarium/assets/120480244/47ef65de-a656-4577-9ff4-4bd55ee3d2c3)

**Comment by YohannParis** [comment]
Waiting for SimPy functionality
