### ISSUE TITLE
[BUG]: Uploading a csv file fails

### ISSUE THREAD

**Issue by pascaleproulx** [DARPA-ASKEM/Terarium#1261]
**Describe the bug**
Uploading a csv from file spits out errors (see screenshot).

**To Reproduce**
1. Download this dataset: [Go to '...'](https://github.com/DARPA-ASKEM/experiments/blob/main/thin-thread-examples/milestone_6month/evaluation/ta1/usa-IRDVHN_age.csv)
2. On the Overview page, click the Upload resources button
3. Select dataset you downloaded and click Import
4. The upload button is broken but the file seems to load anyway (issue https://github.com/DARPA-ASKEM/Terarium/issues/1196)
5. Click cancel and click on the dataset to open it
6. It does not open and spits out a bunch of errors (see screenshot)

**Expected behavior**

**Screenshots**
<img width="1784" alt="image" src="https://github.com/DARPA-ASKEM/Terarium/assets/42645294/e1cfd50e-1866-425e-9348-aafc07f85fca">

**Comment by dvince2** [comment]
These CORS issues have been resolved and files now upload.  Once uploaded you are taken back to the over view page for a project.
There are still some issues around file size, but, an error message now shows correctly to the user.
