### ISSUE TITLE
[TASK]: User interface/popup for user log data

### ISSUE THREAD

**Issue by hvasque14** [DARPA-ASKEM/Terarium#1320]
Need to create a user interface/pop-up for users to fill in to connect logging data to the MITRE scenarios. Users could access the form in the footer. 

Within the pop-up form, users need to be able to indicate the following:
1. Scenario 
2. Scenario Question 
3. Description of what they are working on.
4. Notes

Additionally, the pop-up form needs a method to start recording time, pause the recording, resume the recording, and stop the recording. 

Attached is a sketch for the pop-up. This is just a concept and I'm open to design suggestions.

<img width="516" alt="Logging form sketch" src="https://github.com/DARPA-ASKEM/Terarium/assets/116816354/66f30799-5faa-49d1-800f-6613caf7ac60">

**Comment by pascaleproulx** [comment]
Additional requirements from MITRE:
- Error logs - when things break and what actions caused them to break
- Runtime for simulations
- LLMs, when they hang, how long does it take to get back profiling results
- When do modelers go into different parts of the workbench and how much time they spend in each space: e.g. searching for docs, working with data, doing a simulation
- Extraction pipelines - how long to get to HITL curation step? How long does full end-to-end process with HITL curation take?
- Deadtime, waiting for a response from something
- When does workbench call out to other TA services, and get responses back?

**Comment by pascaleproulx** [comment]
Also, since many people will be using the system, it will be impartant to track userids for each action and report entries (for tasks and issues) so that logs can be filtered by userid. The userids do not have to be anonymized.
