### ISSUE TITLE
[FEAT]: Simulate ensemble (deterministic)

### ISSUE THREAD

**Issue by jamiewaese-uncharted** [DARPA-ASKEM/terarium#1368]
Fresh new designs for the Simulate ensemble (deterministic) operator:

INPUT PAGE
![Simulate ensemble (deterministic) input](https://github.com/DARPA-ASKEM/Terarium/assets/120480244/512de7ea-9ee1-4b9f-bf25-cc0fb7724588)

OUTPUT PAGE
![Simulate ensemble (deterministic) output](https://github.com/DARPA-ASKEM/Terarium/assets/120480244/617dca9f-17d6-484d-8d64-e7beecebbea9)

NODE (EMPTY)
![Simulate ensemble (deterministic) node empty](https://github.com/DARPA-ASKEM/Terarium/assets/120480244/36d2bea5-1de2-4d39-ba85-8d1fd18a5536)

NODE (COMPLETE)
![Simulate ensemble (deterministic) node complete](https://github.com/DARPA-ASKEM/Terarium/assets/120480244/94be4136-7057-4be7-a98e-c289691fcba1)

FIGMA LINK:
https://www.figma.com/file/5uzTEU3jtIfY62fp6I7SYo/Terarium---Workflow-%26-etc?type=design&node-id=1498%3A245440&mode=design&t=4Mo8g3XnXOHdBxp1-1

**Comment by Tom-Szendrey** [comment]
Thanks!!!!
