### ISSUE TITLE
[FEAT]: Add a simulation plan page

### ISSUE THREAD

**Issue by dgauldie** [DARPA-ASKEM/TERArium#152]
**Describe the solution you'd like**
* Create the simulation plan page
* Ignore the _Question_ part of the page
* Create the simulation graph

**Additional context**

![Image](https://user-images.githubusercontent.com/636801/199068768-8f93af8b-5fc4-45c5-aa15-f8259cf33c69.png)

**Comment by bencodrington** [comment]
@mwdchang is this safe to close now?
