### ISSUE TITLE
[BUG]: Cannot create and save any note using the Notes side panel

### ISSUE THREAD

**Issue by liunelson** [DARPA-ASKEM/terarium#1523]
**Describe the bug**
Sabina tried to create and save notes within the Notes side panel. However, upon clicking "save", the list of notes remains empty.

**To Reproduce**
1. Go to 'Notes' side panel
2. Click on 'Create a note'
3. Type something in the text field
4. Click on 'Save'
5. No note appears in the list

**Expected behavior**
We expect that notes are saved and can be retrieved as part of the project.

**Screenshots**

**Additional context**
We're on staging.

**Comment by shawnyama** [comment]
Are you just testing this on the overview page? That doesn't work yet because the overview page is not recognized as an asset in the backend. At the moment this situation is avoided as there needs to be some sort of overview asset created in the backend to associate the note with.

**Comment by shawnyama** [comment]
same as https://github.com/DARPA-ASKEM/terarium/issues/1215
