### ISSUE TITLE
[FEAT]: Open simulation plan page from the model page

### ISSUE THREAD

**Issue by dgauldie** [DARPA-ASKEM/Terarium#153]
**Describe the solution you'd like**
* Create the interface to select a question this model can fulfill (`simple forecasting` for now).
* Figure out with @pascaleproulx the process between selecting a question and opening the _Simulation plan_
* TA3 CIEMSS will provide an API, we should stub it to provide a list of questions

**Additional context**

![Image](https://user-images.githubusercontent.com/636801/199069583-fac7776e-c75c-482b-b981-5947919f5e91.png)

**Comment by YohannParis** [comment]
@liunelson could you provide more information about the TA3 API please?
