### ISSUE TITLE
[FEAT]: Model diagram tooltips (hover over anything for more information)

### ISSUE THREAD

**Issue by jamiewaese-uncharted** [DARPA-ASKEM/Terarium#1559]
The petrinet diagram would be more useful if users could hover over a node to see its name, description, units, extractions, etc. Here's a quick mockup:

![image](https://github.com/DARPA-ASKEM/Terarium/assets/120480244/8ade9618-f94b-4263-a61a-f0c4128017c8)

**Comment by dgauldie** [comment]
will not do
