### ISSUE TITLE
[BUG]: Model configurations are missing in `projects/{project_id}/assets`

### ISSUE THREAD

**Issue by liunelson** [DARPA-ASKEM/terarium#1572]
**Describe the bug**
Given a project ID, the `assets` endpoint returns no model configuration even though there are models (with model configurations) in this project.

**Expected behavior**
I expect that the `assets` endpoint for a given project ID returns the list of model configurations that I can reach using the `models/{model_id}/model_configurations` endpoint.

**Comment by mwdchang** [comment]
Configuration is/was not considered first class of a project so they weren't included, this might change with some discussion yohann/jami are having with pascale.
