### ISSUE TITLE
[FEAT]: Display new project within the carrousel

### ISSUE THREAD

**Issue by YohannParis** [DARPA-ASKEM/TERArium#158]
**Describe the solution you'd like**
* Once a project has been added, display it within the users carrousel

**Comment by echl** [comment]
@YohannParis  Presumably we can simply refresh the project carousel which would make a new call to the backend which would include the newly created project?

**Comment by YohannParis** [comment]
> @YohannParis Presumably we can simply refresh the project carousel which would make a new call to the backend which would include the newly created project?

Sure, but I would also expect the form that create a project to bring you automatically to the project page. So when the user click back to the homepage/projects page, a new API call would be made at that moment.

**Comment by YohannParis** [comment]
@mwdchang: Please link the PR that closes this issue!
