### ISSUE TITLE
[TASK]: Getting project list shouldnt be set to first 50

### ISSUE THREAD

**Issue by Tom-Szendrey** [DARPA-ASKEM/Terarium#1602]
Our drop down for listing projects seems to default at 50

The calls used to populate this drop down should not be limited to 50 otherwise any projects past the first 50 become really awkward to use

Solution:
Progressive pagination, e.g. 0-49 => 0-99 => 0-149 ??
Or maybe like the last 20 projects updated + a searchbar if you are looking for specific stuff

Leaning towards the search bar

<img width="1447" alt="image" src="https://github.com/DARPA-ASKEM/Terarium/assets/17088680/07b3f349-0aa6-4c20-91de-3aca772c3cc1">

<img width="734" alt="image" src="https://github.com/DARPA-ASKEM/Terarium/assets/17088680/8e810eb4-3612-4e56-b763-fe7d8748c5b3">

**Comment by Tom-Szendrey** [comment]
Marking as Backlog just because there will be some designs around this by the sounds of it post eval
@pascaleproulx @jamiewaese-uncharted  for visibility

**Comment by YohannParis** [comment]
Done
