### ISSUE TITLE
[TASK]: Save as Dataset fully integrated 

### ISSUE THREAD

**Issue by Tom-Szendrey** [DARPA-ASKEM/terarium#1605]
Save as Dataset Button:

Doesnt exist on:
-    Calibration (Ciemms)
-    Calibrate Julia

Disabled on:
-    Simulate Ensemble
-    Calibrate Ensemble

Creates “None Result Dataset” in project -> Weird name but at least filled with data!
-    Simulate Ciemms
-    Simulate Julia

**Comment by YohannParis** [comment]
What is the state on this?

**Comment by Tom-Szendrey** [comment]
OLD issue thats been done
