### ISSUE TITLE
Cleaning up Code Editor

### ISSUE THREAD

**Issue by YohannParis** [DARPA-ASKEM/terarium#1611]
### Code editor clean up
- Splitting the code editor and the code asset into different components
- This is used by _Artifacts_ and _Code_ ProjectAssetsTypes

**Comment by tangopapatime** [comment]
With @shawnyama heading on Vacation on Wednesday (Aug 2) I can continue this effort.

**Comment by YohannParis** [comment]
It does not exist a paper with GitHub code that can create a model.
