### ISSUE TITLE
Simplify Extraction-Service Integration within TDS

### ISSUE THREAD

**Issue by YohannParis** [DARPA-ASKEM/Terarium#1618]
Simplify the integration of the Extraction Service within the TDS platform to enhance functionality.

**Comment by YohannParis** [comment]
@brandomr i assigned you this task because we talk about it. But I will let you figure out if you want to keep this in this GitHub project or just update us on our weekly sync meeting.

**Comment by brandomr** [comment]
Sounds good--will keep you posted on this

**Comment by YohannParis** [comment]
This is not worth or ressources
