### ISSUE TITLE
Add progress info for CIEMSS components.

### ISSUE THREAD

**Issue by YohannParis** [DARPA-ASKEM/Terarium#1634]
Review and merge the GitHub pull request for the PyCiemss service at https://github.com/DARPA-ASKEM/pyciemss-service/pull/9.

**Comment by YohannParis** [comment]
@blanchco Please bug @Tom-Szendrey and @mwdchang for guidance on where to find the information needed to implement this feature. It's an easy task, but a complexed one.

**Comment by dgauldie** [comment]
duplicate
