### ISSUE TITLE
Implement optimization under uncertainty

### ISSUE THREAD

**Issue by YohannParis** [DARPA-ASKEM/Terarium#1636]
Work on optimization techniques considering uncertainties in the system.

**Comment by liunelson** [comment]
Risk-Based Optimization Under Uncertainty (RBOUU), a.k.a. "optimize"

This is a feature in PyCIEMSS that takes a model, a quantity of interest, and some interventions (i.e. setting some variables/parameters to some to-be-determined values at some given times) and returns an "optimal policy" (i.e. values of the interventions such that (1) an objective function over the intervention variables/parameters and (2) the quantity of interest are simultaneously minimized.

Example: given a SIDARTHE model, the 2-last-days average of `I` as the quantity of interest, and an intervention of "beta \in [0.0, 3.0]" at time `t = 0.1`, we get the optimal policy of intervention`beta = 0.0`.

Test notebook: [https://github.com/liunelson/pyciemss/blob/nl-test/notebook/integration_demo/nliu/review_interfaces.py](https://github.com/liunelson/pyciemss/blob/nl-test/notebook/integration_demo/nliu/review_interfaces.py)

@fivegrant here's a handy table that I made, where I describe which/how each argument should be exposed for integration.
https://docs.google.com/spreadsheets/d/1_iyt9TFcdUlTzYOebhk2_Kz-ToW6wJFXQ3Vinbovwx8

@jamiewaese-uncharted @pascaleproulx ^ this table could serve as guide to the design of the workflow boxes.
