### ISSUE TITLE
[Task]: Fix Parameters over Time

### ISSUE THREAD

**Issue by YohannParis** [DARPA-ASKEM/Terarium#1637]
Conduct tests involving interventions and observe variations in parameters over time.

**Comment by pascaleproulx** [comment]
I tried changing gamma over time. The results are wrong.

https://app.terarium.ai/app/#/projects/40/workflows/Workflow/bf5f14b8-237f-49da-bc27-790c9cf1ead4

![Image](https://github.com/DARPA-ASKEM/Terarium/assets/42645294/aeed5c5e-6d23-4394-abf5-82bd9b649935)

![Image](https://github.com/DARPA-ASKEM/Terarium/assets/42645294/3cddfc88-23ea-47d5-bbed-4589bb6149d8)

**Comment by Tom-Szendrey** [comment]
Just writing this down as a reminder for when i look into this more
I will need to add interventions to payload:

```
{
  "engine": "ciemss",
  "model_config_id": "ba8da8d4-047d-11ee-be56",
  "timespan": {
    "start": 0,
    "end": 90
  },
  "interventions": [{"timestep":2,"name":"beta","value":0.4}],  
  "extra": {
    "num_samples": 100
  }
}
```

https://github.com/DARPA-ASKEM/pyciemss-service/blob/6cfe408143b6505980d24b82ad0807c7a5499958/service/models.py#L105-L107
