### ISSUE TITLE
VEGA Research HMI

### ISSUE THREAD

**Issue by YohannParis** [DARPA-ASKEM/terarium#1641]
DC Edit: The background is that PyCIEMSS is producing a VEGA-like output, this is an investigation to whether we can/should use it or whether we should just render our own.

Please note there are VEGA, and VEGA-lite ... it isn't clear which one is being sent from PyCIEMSS.

Implement VEGA, a visualization grammar, within the Human-Machine Interface.

**Comment by echl** [comment]
Research notes here: https://docs.google.com/document/d/11_jSRyn8Y1bUW7HJnCZNfLVmdDX0t6l5sWJU_arZX70/edit
