### ISSUE TITLE
Fixing existing simulation-chart

### ISSUE THREAD

**Issue by YohannParis** [DARPA-ASKEM/terarium#1642]
Address and fix issues related to the HMI chart, including scaling and other improvements.

**Comment by mwdchang** [comment]
Not sure if this solution is still valid, the repo hasn't been touched in a long time and may be out of date against the current version of chart.js

https://stackoverflow.com/questions/30216167/chartjs-plot-data-based-with-unequal-time-intervals

**Comment by YohannParis** [comment]
Wait for report on #1641
