### ISSUE TITLE
[FEAT]: Display user selected model within `Model Renderer` component

### ISSUE THREAD

**Issue by dgauldie** [DARPA-ASKEM/TERArium#165]
**Goals**
* Create a new component named `ModelRendered` to visualise models in the _Models_ view.
* Base code from the TA2 playground.

**Comment by bencodrington** [comment]
The `ModelRenderer` component has already been added, I'll repurpose this ticket to hook it up so that it renders the selected model (whose ID will be in the URL) rather than the arbitrary hardcoded model it's currently showing.
