### ISSUE TITLE
[BUG]: Calibrate (probabilistic) should ignore data columns not explicitly mapped

### ISSUE THREAD

**Issue by pascaleproulx** [DARPA-ASKEM/Terarium#1660]
**Describe the bug**
Calibrate (probabilistic) should ignore data columns not explicitly mapped. It errored out on columns in dataset not in model.

**To Reproduce**
1. In the workflow graph, set things up to calibrate a model using the Calibrate (probabilistic) box (select a model and a dataset where the dataset contains extra columns with variables not in the model)
2. Create the mapping in the drilldown pane for calibrate and click run

=> check the logs: it errors out mentioning columns in the dataset that were not explicitly part of the mapping.

Could be an issue for CIEMSS to solve.

**Comment by blanchco** [comment]
linkedpr: https://github.com/DARPA-ASKEM/pyciemss-service/pull/43

**Comment by blanchco** [comment]
Fixed by the above PR in pyciemss-service
