### ISSUE TITLE
[BUG]: Pressing Enter should be equivalent to click on the Create button for new project

### ISSUE THREAD

**Issue by pascaleproulx** [DARPA-ASKEM/terarium#1667]
**Describe the bug**
I can't count anymore the number of times I tried creating a new project and ended up with no project because I concluded the process by pressing Enter on the keyboard instead of clicking on the Create button. This is a deep paper cut for me (and I am assuming others too).

**To Reproduce**
1. Click on 'New Project' button from the home page
2. Enter a name and optionally a description
3. Press Enter
=> the modal closes but the project does not get created.

**Expected behavior**
Pressing Enter should do the same as explicitly clicking the Create button, i.e. create the project and opening it.

**Comment by blanchco** [comment]
This has been fixed, pressing enter does create a new project
