### ISSUE TITLE
[FEAT]: Show in the Data Explorer mock Models within the Data Service

### ISSUE THREAD

**Issue by YohannParis** [DARPA-ASKEM/TERArium#167]
**Describe the solution you'd like**
* Use _Data Service_ API to fetch mock Models
* Show them in the _Data Explorer_

**Comment by amostafa-uncharted** [comment]
Note that the current implementation of the data explorer includes a client-side "data" service that encapsulates some temp data (i.e., json array) of models metadata as well as some functions to fetching such data. Ideally, the mock models data would be removed from the client-side data service, and the functions in the data service should be updated to use the Data Service API to fetch the (mock) models from the backend.
