### ISSUE TITLE
[BUG]: Imported README file is not displayed properly

### ISSUE THREAD

**Issue by pascaleproulx** [DARPA-ASKEM/terarium#1676]
**Describe the bug**

**To Reproduce**
1. Click on 'import' button on a document with a github url
2. browse the github repo and select a readme file (.md or .txt)
3. Import file to project
4. Open the readme in the project
=> it opens the code viewer and does not show the content of the readme

**Expected behavior**
A .md or .txt file should be placed in the document section of the resources panel and open as a document (with appropriate metadata and provenance). 

**Screenshots**
<img width="1113" alt="image" src="https://github.com/DARPA-ASKEM/Terarium/assets/42645294/7307872f-985a-4024-9d06-73927ddfb306">

@dvince2 @brandomr

**Comment by shawnyama** [comment]
solved here https://github.com/DARPA-ASKEM/terarium/commit/5edaec38aa46466cb9f4c6638c3bb0f23d240509
