### ISSUE TITLE
[FEAT]: Add ability to rename a dataset

### ISSUE THREAD

**Issue by pascaleproulx** [DARPA-ASKEM/Terarium#1697]
Add stacked dot menu with ability to rename and duplicate a dataset like for models.
<img width="1054" alt="image" src="https://github.com/DARPA-ASKEM/Terarium/assets/42645294/5b4b2754-9b53-4400-97a1-da00876315c1">

**Comment by YohannParis** [comment]
Waiting for `data-service` to add a duplication endpoint
