### ISSUE TITLE
Click "enter" on create new project/assets should submit the form and not close the modal

### ISSUE THREAD

**Issue by blanchco** [DARPA-ASKEM/Terarium#1719]

**Comment by blanchco** [comment]
@YohannParis @pascaleproulx 
Could you confirm the expected behaviour here:
1. Open a modal to create project or asset
2. fill information in modal
3. click enter, modal does not close
4. project or asset is created in the background
6. modal is still open, the modal information clears and you can then create another project or asset

**Comment by YohannParis** [comment]
Nope, right now when you click enter it closes the modal without submitting the form.
You should make sure the form is submitted when you click enter like if you had clicked on the `create`  button, and then close the modal.

**Comment by blanchco** [comment]
@YohannParis one more question here - should this behaviour for all modals or just the create project and create model modals?
