### ISSUE TITLE
[BUG]: xDD extractions of images are not coming through

### ISSUE THREAD

**Issue by pascaleproulx** [DARPA-ASKEM/Terarium#1726]
**Describe the bug**
Can't see the extracted images in the preview (but see the little thumbnails in the result card). Also without images in the project.

**To Reproduce**
1. In the explorer, search for 'SEIRHD equations'
2. The first result corresponds to the screenshots

**Screenshots**
<img width="897" alt="image" src="https://github.com/DARPA-ASKEM/Terarium/assets/42645294/edeffc01-413f-4b84-b548-a30e42353336">
<img width="1354" alt="image" src="https://github.com/DARPA-ASKEM/Terarium/assets/42645294/a91ca792-8799-480a-8fce-0b551fab0f46">

**Comment by pascaleproulx** [comment]
Note that I was able to get images to show up for some of the results e.g. https://app.terarium.ai/app/#/projects/77/publications/83

**Comment by dvince2** [comment]
xdd-document-service is their prod instance, xdd-dev-service is their dev service.  We're doing document search on dev (and we get the extraction thumbnails from there)... then we were going to prod to get the actual extractions.
The xDD team has an issue right now where the document in that issue (and I'm sure others) returns 0 extractions on prod but shows extractions on dev.  I've alerted them to that issue.
This fix though is just to make document and extraction searching in sync with each other... so if the previews show extractions we can actually get the same extractions
