### ISSUE TITLE
[BUG]: Facets are broken

### ISSUE THREAD

**Issue by pascaleproulx** [DARPA-ASKEM/Terarium#1727]
**Describe the bug**
Applying a facet on search results get stuck in 'Loading'. The only facet that works is the github repo one.

**To Reproduce**
1. Go to Explorer and type the query: mask efficacy estimates systematic review
2. See results and the Publication Year facet shows results for 2022 for example. Click on that bar.
3. See page gets blank and stuck in loading like in screenshot.

**Screenshots**
<img width="1049" alt="image" src="https://github.com/DARPA-ASKEM/Terarium/assets/42645294/41e7ee81-a840-40d5-bc1a-4abefdadbcee">

**Comment by dvince2** [comment]
This looks to be an issue on xdd during a recent refactor. Issue opened here: https://github.com/DARPA-ASKEM/TA1-TA4-Tickets/issues/6
