### ISSUE TITLE
[FEAT]: Add the username on project hover

### ISSUE THREAD

**Issue by pascaleproulx** [DARPA-ASKEM/Terarium#1728]
**Is your feature request related to a problem? Please describe.**
I would like to know who created a project from the home page. I like the rollover behaviour that shows the description. Would be neat to add the username of the project creator there too.

<img width="663" alt="image" src="https://github.com/DARPA-ASKEM/Terarium/assets/42645294/663d6646-3ce8-491e-9d2d-398788976596">

**Comment by dgauldie** [comment]
Neil has new designs for this
