### ISSUE TITLE
[BUG]: Model from equations does not end properly

### ISSUE THREAD

**Issue by pascaleproulx** [DARPA-ASKEM/terarium#1731]
**Describe the bug**
If create a new model from scratch by entering equations, at the final step the equation edit model does not close and the created model is not recognized as a normal model by Mira in the model transform. Might be related to the default configuration?

**To Reproduce**
1. From the Overview page, click on 'New Model'
2. On the model tab, click 'Edit equations' and enter the following equations by pasting in the laTeX filed, one at a time
\frac{dS}{dt} = - \beta I \frac{S}{N}
\frac{dE}{dt} = \beta I \frac{S}{N} - r_{EI}E
\frac{dI}{dt} = r_{EI}E - r_{IR}p_{IR}I - r_{IH}p_{IH}I
\frac{dH}{dt} = r_{IH}p_{IH}I - r_{HR}p_{HR}H - r_{HD}p_{HD}H
\frac{dR}{dt} = r_{IR}p_{IR}I + r_{HR}p_{HR}H
\frac{dD}{dt} = r_{HD}p_{HD}H
3. Click 'Update model'
4. See that the 'edit equations' mode is not closed as expected although the diagram is visible.
5. Click on the Transform tab to modify the model using Mira.
6. See that the LLM does not print the model as done for a model not created the way we just did (see screenshots below). It cannot operator on that model either. For example, try typing "Stratify with strata 'masked' and 'unmasked'. That creates the following error:
<img width="700" alt="image" src="https://github.com/DARPA-ASKEM/Terarium/assets/42645294/3d97196d-44bd-4b5f-8a19-7452248227c8">

Default configuration when model created from equations:
<img width="1505" alt="image" src="https://github.com/DARPA-ASKEM/Terarium/assets/42645294/952b0b7c-d336-46f4-b78e-925a1beab2e2">

Default configuration when model NOT created from equations (e.g. from the diagram):
<img width="1493" alt="image" src="https://github.com/DARPA-ASKEM/Terarium/assets/42645294/03657e52-e350-4563-9a7e-f11eb74c2c63">

What you see for a model created from equations on the transform tab (missing the graph preview):
<img width="841" alt="image" src="https://github.com/DARPA-ASKEM/Terarium/assets/42645294/a86217ce-562b-4754-b091-3fa0b9b4a19c">

What you see on the transform tav with a model not created from equations (graph preview):
<img width="823" alt="image" src="https://github.com/DARPA-ASKEM/Terarium/assets/42645294/712802d1-892c-483a-be3d-62add705675e">

What you see on the transform tav with a model not created from diagram (still a graph preview):
<img width="536" alt="image" src="https://github.com/DARPA-ASKEM/Terarium/assets/42645294/5b844a8a-9ebc-425f-b8b8-ea574fcc61ec">

**Additional context**

**Comment by YohannParis** [comment]
@Free-Quarks is working on it.

**Comment by brandomr** [comment]
@pascaleproulx @YohannParis based on what I'm seeing--when I `update model` a request is sent to `https://app.staging.terarium.ai/api/extract/latex-to-amr/petrinet` which [proxies to the skema unified service](https://github.com/DARPA-ASKEM/Terarium/blob/20c85d9e5c682709e033d9206c0a44473556c0bf/packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/resources/extractionservice/ExtractionResource.java#L81-L95C1) and doesn't use the `knowledge middleware` (aka `TA1 Service`). I think we should switch this to use our `knowledge middleware` since it has robust logging/error handling and can help us sort out what's going awry

**Comment by YohannParis** [comment]
> @pascaleproulx @YohannParis based on what I'm seeing--when I `update model` a request is sent to `https://app.staging.terarium.ai/api/extract/latex-to-amr/petrinet` which [proxies to the skema unified service](https://github.com/DARPA-ASKEM/Terarium/blob/20c85d9e5c682709e033d9206c0a44473556c0bf/packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/resources/extractionservice/ExtractionResource.java#L81-L95C1) and doesn't use the `knowledge middleware` (aka `TA1 Service`). I think we should switch this to use our `knowledge middleware` since it has robust logging/error handling and can help us sort out what's going awry

Yes, that's one of the task to be done next Sprint.

**Comment by pascaleproulx** [comment]
Note that #4. in the original description is still there (equations editing mode is still live after the diagram shows up).
<img width="1275" alt="image" src="https://github.com/DARPA-ASKEM/terarium/assets/42645294/811855de-4f29-4b0a-8a14-bf201c97ff59">

And now the equations are lost after reloading the model tab.
<img width="1300" alt="image" src="https://github.com/DARPA-ASKEM/terarium/assets/42645294/5b95409b-776c-4025-bcdc-7f2603702218">

**Comment by pascaleproulx** [comment]
Also, it created three configurations: maybe I pressed save more than once? Note the Default config is all blank and then two configs with the model name appeared too.
<img width="1285" alt="image" src="https://github.com/DARPA-ASKEM/terarium/assets/42645294/6c756dec-d6ba-4537-89ea-14c56e51c359">

**Comment by blanchco** [comment]
@pascaleproulx when you press save do you expect only one configuration to be made?  That being the 'Default config'

**Comment by pascaleproulx** [comment]
Yes, I expect only one config to be created and it to be the default one. It technically does not HAVE to be called 'Default Config' although that probably makes most sense.
