### ISSUE TITLE
[FEAT]: Add ability to duplicate a project

### ISSUE THREAD

**Issue by pascaleproulx** [DARPA-ASKEM/Terarium#1743]
**Is your feature request related to a problem? Please describe.**
Cloning or duplicating a project is a core feature of the app - it supports the notion of building on other people's work. We also saw the need after the eval where MITRE wanted to create a copy of the official project to keep playing with it without modifying the original. @toddroper mentioned that this feature would need to be a frontend flow.  "We have too many operational objects in the workflow and do not properly register objects to the project.  This leaves TDS without a proper understanding of how to duplicate the project without a lot of faulty logic."

This feature would be available from the stack icon menu besides the project name. Now it shows 'Edit' but it should have 'Rename' and 'Duplicate' like on the model and dataset objects.
<img width="536" alt="image" src="https://github.com/DARPA-ASKEM/Terarium/assets/42645294/b6417c41-2876-4d91-8349-107db3841f84">

**Comment by YohannParis** [comment]
This might complicated, because do we want to do a deep copy or not.

**Comment by dgauldie** [comment]
this will be closed until later on in the program
