### ISSUE TITLE
[FEAT]: Nested graph colour update for model diagrams

### ISSUE THREAD

**Issue by ngraham76** [DARPA-ASKEM/Terarium#1753]
In an effort to increase contrast and reduce clutter, will be changing our graphs from greyscale to colour for model diagrams and removing labels from nested nodes. In discussion with Jamie, Pascale and Nelson we have settled on a modified viridis colour palette for our nested nodes. We will reply on the legend as an alternate to nested node labels to avoid double encoding and allow the graph to be viewed clearly without the clutter of labels. 

Matrices will not be coloured, but grey and/or white with labels removed. If you have any questions please feel free to chat with me any time.

**Current:**
<img width="420" alt="image" src="https://github.com/DARPA-ASKEM/Terarium/assets/141876103/47b8e9c9-3715-4177-92d0-1cd7cf10fcf0">
<img width="451" alt="image" src="https://github.com/DARPA-ASKEM/Terarium/assets/141876103/0511abf1-bdc0-4231-8c81-66b1f43f2dce">

**Proposed:**

<img width="648" alt="image" src="https://github.com/DARPA-ASKEM/Terarium/assets/141876103/2aef2e3c-9c15-49ac-a421-3266c20f0074">
<img width="667" alt="image" src="https://github.com/DARPA-ASKEM/Terarium/assets/141876103/02777ef5-6717-447a-bd14-8f6e60dd45a8">
<img width="644" alt="image" src="https://github.com/DARPA-ASKEM/Terarium/assets/141876103/bb833a29-2a2f-470f-9ae7-718cea44ec73">

**Comment by mwdchang** [comment]
@ngraham76 @pascaleproulx why not @Jami159 why not just use something from colorbrewer if we want a palette that has been shown to be distinct and readable?

https://colorbrewer2.org/#type=qualitative&scheme=Accent&n=5

**Comment by ngraham76** [comment]
> @ngraham76 @pascaleproulx why not @Jami159 why not just use something from colorbrewer if we want a palette that has been shown to be distinct and readable?
> 
> https://colorbrewer2.org/#type=qualitative&scheme=Accent&n=5

We're pretty happy with the colour palette we selected, they are distinct, clear and legible. They are also a good fit with the overall green colour scheme of Terarium and they work well from an accessibility standpoint - being derived from the viridis palette.
