### ISSUE TITLE
[TASK]: Factored matrices for model configuration

### ISSUE THREAD

**Issue by mwdchang** [DARPA-ASKEM/Terarium#1764]
We currently have the flattened matrix for transition configuration, we should also have the factored tables available.

For example: transition T1 has been stratified by age={A1, A1} and location={L1, L2}. Then
- There is an existing flattened table = [A!_L1, A1_L2, A2_L1, A2_L2] ^2
- We will add age = [A1, A2], and
- We will add location = [L1, L2]

We can set the cell values in these factored tables, when doing so it should also update the flattened table if the flattened table's cell values are derived.

**Comment by YohannParis** [comment]
This is for CatLab, but because of the move to MIRA this is tabled
