### ISSUE TITLE
[BUG]: Cannot use stats from date columns because stats are not calculated

### ISSUE THREAD

**Issue by mwdchang** [DARPA-ASKEM/Terarium#1767]
We are using `DataResource.javve#getStats()` to collect column statistics, this doesn't work when it comes to dates, e.g. "2002-02-3". 

We should consider extending this to cover date-like strings/objects, as the min/max/interval are used as input for calibration in the userinteerface.

Note we may need to extend the data structure to have some notion of "interval" for to rescale the data to start at the number 1.

https://github.com/DARPA-ASKEM/Terarium/blob/e98ed653cf560db9afd0b5af7f9a24faff3802a3/packages/services/hmi-server/src/main/java/software/uncharted/terarium/hmiserver/resources/dataservice/DatasetResource.java#L305-L337

**Comment by dgauldie** [comment]
will not do in the short term
