### ISSUE TITLE
[TASK] cosmos extraction display

### ISSUE THREAD

**Issue by YohannParis** [DARPA-ASKEM/terarium#1775]
**Describe the task**
Implement into the HMI PDF extractions saved by TDS, like images and text.

**Comment by dvince2** [comment]
@YohannParis where should these show up? Are there designs for this?

**Comment by YohannParis** [comment]
> @YohannParis where should these show up? Are there designs for this?

This task needs to wait for TDS to implement their counter-part: #1774
