### ISSUE TITLE
Adding "align" to model enrichment

### ISSUE THREAD

**Issue by dgauldie** [DARPA-ASKEM/terarium#1841]
@mwdchang to investigate and develop plan for implementation

**Comment by mwdchang** [comment]
The basic idea here is to hook up one or more API calls to enrich a given model. 

For example, given a model and related publication text, we expect that
- We will have additional metadata we can inject into the model (at the model level), and/or
- We will be have richer metadata at the states/transitions level


The wider implication here is that if the "model" changes, it has a rippling effect across to other objects in Terarium - namely ModelConfigurations as they effectively subsumes a model. So this means that say:
- We update model X
- We need to find for model X, a list of configurations
- For each one of the configurations we need to apply the same updates we have done to X

**Comment by blanchco** [comment]
[discussion regarding this](https://unchartedsoftware.slack.com/archives/C03S02YH3D5/p1695907826006519?thread_ts=1695907647.314509&cid=C03S02YH3D5)
