### ISSUE TITLE
[FEAT]: Allow output ports of different types

### ISSUE THREAD

**Issue by mwdchang** [DARPA-ASKEM/terarium#1870]
Per discussion, we should be more direct in terms of what workflow operations produce. There are some confusions over whether an operation should consume a model o ra model configurations that we want to clear up.

1. model-operation should produce a single **model** output and a listing of **model-configurations**
2. model-transform-operation should take in **model** input, and produce both a **model** output that is the result of the transform, and a default **model-configuration** that is associated with the produced model.
3. We will need to adjust the tera-jupyter modules so that they consume model-ids instead of model-configuration-ids

The schematic of what the workflow looks like that involves these two operations: 

![Image](https://github.com/DARPA-ASKEM/Terarium/assets/1220927/1c741c53-67e0-4d60-b522-bb781fa3420a)

**Comment by jamiewaese-uncharted** [comment]
I don't think we're doing this. There's a lot of new designs in progress and under review, and it's all using the current mental model. I think we should close this issue... but I'm open to further discussion.

**Comment by blanchco** [comment]
@pascaleproulx @YohannParis Just noting Jamie's comment here.  Should this issue be closed?
