### ISSUE TITLE
[BUG]: Typo in the parameter modal associated with a model's configuration table

### ISSUE THREAD

**Issue by liunelson** [DARPA-ASKEM/terarium#1883]
**Describe the bug**
`A distibution`.

**To Reproduce**
1. Go to any model and its "Model" tab
2. Scroll down to the configuration table
3. Click on the hamburger of any parameter
4. Click on the "Type" dropdown
5. See the typo

**Expected behavior**
It should be `A distribution` (missing `r`).

**Screenshots**
![Screenshot 2023-09-20 at 16 57 31](https://github.com/DARPA-ASKEM/Terarium/assets/1030720/bee82ba0-fa80-43fc-9c67-e25ce3fcccc6)

**Additional context**
This was on staging and Jami's local.

**Comment by liunelson** [comment]
@Jami159 I assigned it to you but feel free to have it assigned to whoever else is appropriate.

**Comment by Jami159** [comment]
LOL yeah it's a very quick fix
