### ISSUE TITLE
add provenance after model/dataset enrichment

### ISSUE THREAD

**Issue by YohannParis** [DARPA-ASKEM/terarium#1887]
- Modify "Add ressources" modal to display `Document` instead of `Artifacts`.
- Add provenance to model to link `Document` selected for enrichment.
- Get the results in the model and update it, should be done automaticaly by refreshing like the call equations to amr

**Comment by pascaleproulx** [comment]
@blanchco Please tweak the '+ Add Resources' button link to say 'Enrich model description'. This will bring up the same modal where the user can select a document and get back the model card. Later, we will add another button to get back extracted variables metadata and align them with the model (will be a different issue). Thanks!

**Comment by blanchco** [comment]
Button name change has been done in https://github.com/DARPA-ASKEM/terarium/pull/1916.  Will continue to work on provenance linking
