### ISSUE TITLE
FUNMAN 2: Additional plumbing and storage (maybe?)

### ISSUE THREAD

**Issue by dgauldie** [DARPA-ASKEM/terarium#1890]
FUNMAN API is already asynchronous and provides an end-point to fetch query results. However looking at the deployment configurations of funman, it doesn't look like it has any persistent storage capabilities - which means we could lose all the run-results if we redeploy/update.

We should investigate if there are storage options we can turn on/off, and more importantly whether this is something we want to pursue, which would involve storing the results into S3 as we do other simulation-type results, or whether we want to leave things as-is and live with the fact data can be lost.

**Comment by Tom-Szendrey** [comment]
Im marking this as Ready as i do not believe we need this for the hackathon demo which is first prio

All progress that was previously on this ticket has been lost between transition
