### ISSUE TITLE
FUNMAN 5: Workflow and drilldown UI

### ISSUE THREAD

**Issue by mwdchang** [DARPA-ASKEM/terarium#1925]
Create workflow operation, funman node, and funman drilldown to support user interactions. Note this does not include the charts and utilities to manipulate funman outputs - these are covered in other tasks. Please check with Jami and Pascale as there may be some subtle design changes.

Design Reference:
- https://www.figma.com/file/GkVfEqpItMg67pNgh5oUAd/Terarium---New-%26-Improved?type=design&node-id=15-47982&mode=design&t=lC7kKMEXvYFKCizP-0

**Comment by pascaleproulx** [comment]
@jamiewaese-uncharted @ngraham76 could you update the figma link to point to the latest version as seen in the prototype please? e.g. placing number of samples and tolerance into the 'more options' section, etc. Thanks.

**Comment by ngraham76** [comment]
> @jamiewaese-uncharted @ngraham76 could you update the figma link to point to the latest version as seen in the prototype please? e.g. placing number of samples and tolerance into the 'more options' section, etc. Thanks.

This Figma link points to the Sept 28th version of the file, is there a newer version? If so, I can't find it - @jamiewaese-uncharted will have to update this link as he worked on this.
