### ISSUE TITLE
[BUG]: Cannot upload a PDF

### ISSUE THREAD

**Issue by pascaleproulx** [DARPA-ASKEM/terarium#1961]
**Describe the bug**
Using the 'Upload Resources' button, try uploading the PDF from the basic scenario (selecting the file downloaded to your computer). You can see the preview but clicking uploading does not make the paper appears in the project.

See also related issue 1849 for changes to the upload modal.

**Comment by Tom-Szendrey** [comment]
-Make sure using publication not artifact 
-bonus would be include other file types (@YohannParis can add these file types)

**Comment by Tom-Szendrey** [comment]
Reusing this issue to also change from Artifact -> Document
