### ISSUE TITLE
[TASK]: Document Text Viewer should be prettier and more functional

### ISSUE THREAD

**Issue by Tom-Szendrey** [DARPA-ASKEM/terarium#1996]
The code-editor currently being used needs a bit of fixing up to make it more compatible for how its being used

**Comment by Tom-Szendrey** [comment]
I will be saving this for last as this is currently functional. 
The main thing is that we need a new component for these rather than just reusing the code editor
Viewing txt and md files is a tad ugly so if there are no designs for this I can reference other sites if there are no designs but the ground work will make future designs a lot easier to update to

**Comment by echl** [comment]
@pascaleproulx @jamiewaese-uncharted I whipped up something basic but let me know what else we might need design wise. There's also the option of incorporating PrimeVue's Editor component which allows rich text editing. 

https://github.com/DARPA-ASKEM/terarium/assets/16358728/9f6430dc-a905-4c08-acc4-d9fcab613d1c

**Comment by jamiewaese-uncharted** [comment]
We should render the markdown files as formatted text. 

![Image](https://github.com/DARPA-ASKEM/terarium/assets/120480244/9da0bdb9-9b79-47e2-a7f9-90c8c9b36446)
