### ISSUE TITLE
[BUG]: COSMOS extractions not persisted consistently

### ISSUE THREAD

**Issue by pascaleproulx** [DARPA-ASKEM/terarium#2009]
**Describe the bug**
After uploading a PDF on staging, I can see the COSMOS extractions. But if I upload a second PDF, I lose the extractions on the first PDF and soon enough on the second PDF too.

**Comment by blanchco** [comment]
@pascaleproulx I am not able to recreate this particular scenario where you upload pdfs synchronously and the extractions disappear from the first pdf.  However I have seen an issue where pdf extractions do not persist, but it happens the next day (I'm assuming the extraction links might expire).  Is this what this ticket is might be referring when we are saying that the extractions do not persist?

**Comment by pascaleproulx** [comment]
Yes, I also noticed it got better yesterday (seem to persist longer) but
disappearing the next day is still bad.
