### ISSUE TITLE
[BUG]: unexpected value for parameter

### ISSUE THREAD

**Issue by pascaleproulx** [DARPA-ASKEM/terarium#2033]
Using the biomodel955, I created a new config and set beta to change over time with values as seen in screenshot.
<img width="592" alt="image" src="https://github.com/DARPA-ASKEM/terarium/assets/42645294/b2030cb0-2058-473b-a115-cbaa2edcac42">

However, when charting the parameter after simulation, the initial value of beta is way up for some reason.
<img width="849" alt="image" src="https://github.com/DARPA-ASKEM/terarium/assets/42645294/1dc67d9a-f22a-4d5e-8da8-68bfbc50a2fb">

**Comment by blanchco** [comment]
Hey @pascaleproulx Just wondering what would be expected in for the initial value here?  It looks like when defining the value over time it started at timestep 1 meaning the timestep 0 was never defined.  The simulation looks like it uses numbers between 0-1 if it is not defined for each sample (value is different for each sample).

![Image](https://github.com/DARPA-ASKEM/terarium/assets/33158416/5efb2f39-79e7-41b9-a6ec-9e0eabebd57d)

 I tried with timestep 0 being defined and got a better looking initial value (it was the set value 0 for every sample):


![Image](https://github.com/DARPA-ASKEM/terarium/assets/33158416/798e53ce-f808-4c48-97b6-e9e6f3a0ee89)


![Image](https://github.com/DARPA-ASKEM/terarium/assets/33158416/6967d48b-052b-4a66-90f6-d925a60e4617)
