### ISSUE TITLE
[TASK]: Incorporate specific fonts for displaying formulas

### ISSUE THREAD

**Issue by mwdchang** [DARPA-ASKEM/terarium#2074]
### Edit November 08, 2023
Looks like the the Latin-Modern is available as a web-font and can be downloaded from Font-Squirrel.
https://www.fontsquirrel.com/fonts/list/find_fonts?q%5Bterm%5D=latin+modern&q%5Bsearch_check%5D=Y

### Original task
> Is it possible for us to incorporate either the font "Latin Modern Math" or "Computer Modern Math" in Terarium? In talking with Nelson, these fonts are the standard for scientific literature math. As I define our model style guide we need to make 
some decisions on what font we will use to display variable labels in our diagrams and formulas.

See maybe
- Latin modern:  https://www.gust.org.pl/projects/e-foundry/lm-math/download
- Computer modern math: https://www.ctan.org/tex-archive/fonts/cm/

**Comment by ngraham76** [comment]
@mwdchang Do you know if we can use this Latin Modern Math or Computer Modern Math font in our application?

**Comment by liunelson** [comment]
@asylves1 
I found the font files for Latin Modern Math
* the original `*.otf`
https://www.gust.org.pl/projects/e-foundry/lm-math/download
* converted to `*.woff, *woff2` (download and look for `latinmodern-math.woff, .woff2`)
https://github.com/fred-wang/MathFonts/archive/gh-pages.zip
* this online generator was able to take the `*.otf` and return `*.ttf, *eot, *svg`
https://transfonter.org/

This page describes a bit what this font is
>The Latin Modern Math (LM Math) font completes the modernization of the Computer Modern family of typefaces designed and programmed by Donald E. Knuth.

https://www.cdnfonts.com/latin-modern-math.font
