### ISSUE TITLE
[Chore]: Clean up VIRIDIS usage in workflow components

### ISSUE THREAD

**Issue by mwdchang** [DARPA-ASKEM/terarium#2188]
We added a colour coordination for simulate operations around the time of the July hackathon, currently this is both a) not really working, and b) no longer needed because simulate ops no longer take in multiple config. If we need to have a colour coordination scheme later we will redo it properly.

We should:
1. Remove `VIRIDIS_14` and associated functions from **tera-workflow.vue**
2. Remove `VIRIDIS_14` and associated functions from **tera-workflow-node.vue**

**Comment by YohannParis** [comment]
It would be useful to keep the utils for VIRIDIS as we are going to use it for the border colours of tasks withing a drilldown modal.

**Comment by mwdchang** [comment]
> It would be useful to keep the utils for VIRIDIS as we are going to use it for the border colours of tasks withing a drilldown modal.

We have like 3 or 4 (possibly different) VIRIDIS palettes all used independently - so I would rather clean house than to figure out which VIRIDIS might be the correct version.
