### ISSUE TITLE
[FEAT]: Auto-mapping for model calibration

### ISSUE THREAD

**Issue by YohannParis** [DARPA-ASKEM/terarium#2222]
Using concept from grounding results, provide to the user an already mapped solution for model calibration drilldown.

- [x] V0: Do the grounding ids match
- [x] V1: Use MIRA call to get confidence on match of 2 IDs: https://github.com/gyorilab/mira/pull/261
- [ ] Slightly adjacent: remove options from dropdown as they get chosen

Using MIRA needs to be careful. 
We can assume it will be accurate and move on, but that is not a safe assumption. Here is an example question sent to TA2 (Jan 3rd):
https://askemgroup.slack.com/archives/C03THCGK2DU/p1704310487727779

**Comment by Tom-Szendrey** [comment]
Here is a sample of why we may not want to remove options from the dropdown as they get chosen:
we are not always guaranteed a 1:1 mapping for everything  

![Image](https://github.com/DARPA-ASKEM/terarium/assets/17088680/48eb6521-d261-4fb4-8202-0f5f10392346)
