### ISSUE TITLE
Create UI skeleton framework for drilldowns

### ISSUE THREAD

**Issue by mwdchang** [DARPA-ASKEM/terarium#2253]
We have a common UI/Design pattern for showing workflow operation drilldowns. 

We should create a general wrapper component to govern the general look and feel so the same style doesn't need to be reinvented across operations.  Perhaps consider a template component with slots that can be customized.

<img width="652" alt="image" src="https://github.com/DARPA-ASKEM/terarium/assets/1220927/be5655cd-97f2-4736-b1c2-f6e53fb911b5">

https://www.figma.com/file/yCstHNeLLPx0TzZC9uWXbl/Terarium---November-2023?node-id=2%3A128739&mode=dev

**Comment by YohannParis** [comment]
@blanchco let's work together to brake this down properly into multiple tasks.
