### ISSUE TITLE
Update the drilldowns in workflow page

### ISSUE THREAD

**Issue by YohannParis** [DARPA-ASKEM/terarium#2297]
Because the drilldowns are unique per operator, they should be defined in their folder.
Update `tera-workflow.vue` per example:

**Current**
```html
<Teleport to="body">
  <tera-drilldown ... >
    <tera-calibrate-julia v-if="currentActiveNode.operationType === WorkflowOperationTypes.CALIBRATION_JULIA" ... />
    <tera-calibrate-ciemss v-if="currentActiveNode.operationType === WorkflowOperationTypes.CALIBRATION_CIEMSS" ... />
    ...
  </tera-drilldown>
</Teleport>
```

**New**
```html
<Teleport to="body">
  <tera-calibrate-julia-drilldown v-if="currentActiveNode.operationType === WorkflowOperationTypes.CALIBRATION_JULIA" ... />
  <tera-calibrate-ciemss-drilldown v-if="currentActiveNode.operationType === WorkflowOperationTypes.CALIBRATION_CIEMSS" ... />
  ...
</Teleport>
```

_Originally posted by @YohannParis in https://github.com/DARPA-ASKEM/terarium/pull/2291#discussion_r1402530701_

**Comment by mwdchang** [comment]
@YohannParis what is the point of this task? I don't see the merits here? It seems like we are just end up moving and renaming files around?

**Comment by YohannParis** [comment]
@mwdchang you are completely right.
Because all those files are technically the drilldown, and they are all behaving slightly differently, they cannot be invoked within a single `<tera-drilldown>` but instead they should have a `<tera-drilldown>` as their foundation.
