### ISSUE TITLE
[TASK]: Funman output table prettify 

### ISSUE THREAD

**Issue by Tom-Szendrey** [DARPA-ASKEM/terarium#2346]
Add sliders to this
round corners on input boxes
correct heights
Group select and parameter into same column

<img width="583" alt="image" src="https://github.com/DARPA-ASKEM/terarium/assets/17088680/7dac1895-da32-44aa-8f87-4a827001f1f8">

<img width="608" alt="image" src="https://github.com/DARPA-ASKEM/terarium/assets/17088680/0bb36d37-616d-4559-a7e9-be7af4f837c1">

**Comment by dgauldie** [comment]
Please add the task to make constraint explicit (non-negative constraint and mass conservation)

**Comment by mwdchang** [comment]
Waiting for operator design to be re-assessed based on evaluation comment that it is hard to understand funman result.

Note there are talks between ciemss and funman to produce a compatible parameters in the form of a dill file similar to ciemss-calibrate.

**Comment by YohannParis** [comment]
This will be done in another issue.
