### ISSUE TITLE
migrate data-service endpoints into hmi-server

### ISSUE THREAD

**Issue by dgauldie** [DARPA-ASKEM/terarium#2349]

**Comment by kbirk** [comment]
Checklist of things to get in:

- [ ] Create / Update should return the model type, not just a `{"id": id }` json obj.
- [ ] Change all DB model types to use UUID `id` field.
- [ ] Change all DB model type references to use UUIDs are foreign keys.
- [ ] Swagger docs for all endpoints
- [ ] Ensure exceptions return descriptive yet sanitized 500s
- [ ] URL casing consistency
