### ISSUE TITLE
[FEAT]: TA1 operator Code to Model

### ISSUE THREAD

**Issue by YohannParis** [DARPA-ASKEM/terarium#2356]
![Screenshot 2023-12-04 at 10 46 42 AM](https://github.com/DARPA-ASKEM/terarium/assets/636801/540005d1-0846-4a20-adff-d816886a4563)

[Figma link](https://www.figma.com/file/yCstHNeLLPx0TzZC9uWXbl/Terarium---November-2023?type=design&node-id=2-169350&mode=dev)

### Objective
Each version will be developed and managed within its own Pull Request (PR).

### Specifications
- input: 
  - Code Asset Id
  - Which code block (dynamics) have been selected as output from the _code asset_ operator.
- output: Model Asset Id 
- state:
  - Model framework selection
  - User can add code block, that are not part of the input.
  - User should be able to rename the code block.

### Version 1: Initial Setup and Model Creation
- [x] #2370
- [x] #2371
- [x] #2374
- [ ] #2375
Query: @dvince2, is this feasible?
- [x] #2383
Reference: [Lifecycle of Assets](https://docs.google.com/document/d/1Iro5mHvCZo61SrkIrFotIyFkI3_KBzej88O2c39-kwg/edit).

### Version 2: Enhanced Output Options
- [x] #2395
Coordination: Organize a quick meeting with the HMI group for consensus on implementation.
Action: Please arrange the meeting when ready. FYI @mwdchang 

### Version 3: Dynamic Selection for Model Creation
- [ ] Allow user to select dynamics for model creation.
Note: This implies support for multiple dynamics in the code asset. Assess feasibility, and if necessary, schedule a meeting for further discussion.
- [x] #2406

### Version 4: Code Visualization
- [x] #2423
- [x] #2431

### Version 5: Integration of Other Models
- [ ] Explore the integration of Regnet and Petri Nets models.
- [ ] Update the drilldown functionality accordingly.

**Comment by YohannParis** [comment]
> This looks great. Should we ask TA1 to see if for a given zipped repo then can suggest dynamics for us?

great question I will ask again at the Working groupo

**Comment by blanchco** [comment]
Pushing this back to the backlog for now... I've taken this as far as it can go right now.

**Comment by YohannParis** [comment]
Thank you, let's call it done for now and reopen issues as needed. Thanks for the great work guys!
