### ISSUE TITLE
[TASK]: Store intermediate results to datastore as they're consumed

### ISSUE THREAD

**Issue by Jami159** [DARPA-ASKEM/terarium#2393]
Right now when we run a calibrate, we're storing the intermediate results to state and that's how we're "saving" them.
This isn't very robust and there are cases where these some/all of these intermediate results are lost (for example, if a calibrate drilldown component is unmounted while there is an ongoing run).

Ask: store intermediate vals as they're consumed in the backend / figure out further details

cc: @mwdchang @dvince2

**Comment by mwdchang** [comment]
duplicate
