### ISSUE TITLE
[TASK]: Configure a model operator

### ISSUE THREAD

**Issue by jamiewaese-uncharted** [DARPA-ASKEM/terarium#2409]
# Design overview
This issue contains a lot of flows and sub-flows. Sorry it's complicated.

The [Figma page for all these designs is here:](https://www.figma.com/file/w4BmFSXhtXTqQy3T7cpWy3/Terarium---January-2024?type=design&node-id=19%3A42307&mode=design&t=4SSSQemG3XjZCw4F-1)

## Workflow node
The first input is for a model. The second input can accept a dataset, document or code. When the second input is in use, a third input appears. And so on, there’s always a slot to add one more thing.

![Configure model - workflow node](https://github.com/DARPA-ASKEM/terarium/assets/120480244/43f4cf79-012f-4ee5-bd9e-313f88a40395)
![Configure model - workflow node - multiple inputs](https://github.com/DARPA-ASKEM/terarium/assets/120480244/b6c2e7c0-714d-4252-8033-45637d7d4fb6)

## Workflow operator (wizard)
The wizard consists of a two step process:
1. The first step is "Context", where you set the model configuration’s name, description, geospatial (location) and temporal (time frame) information.  
2. The second step is “Set values”, where you set the values for all the variables and parameters.

![Configure model - operator wizard](https://github.com/DARPA-ASKEM/terarium/assets/120480244/d3c7394c-542f-4c5d-b061-578aa44b748a)
![Configure model - operator wizard - missing value](https://github.com/DARPA-ASKEM/terarium/assets/120480244/7b749bb7-e80c-47ac-82de-1cca0c1ba76f)

## Model tooltips
When you hover over a variable or parameter in the selection tree, a tool tip appears with a diagram of the model with that element highlighted.
![image](https://github.com/DARPA-ASKEM/terarium/assets/120480244/e8541050-7dfd-4a08-82c6-46aa5461b715)
![image](https://github.com/DARPA-ASKEM/terarium/assets/120480244/ef6af8c4-7d30-4dd0-871a-2db36a8b6cf7)
![image](https://github.com/DARPA-ASKEM/terarium/assets/120480244/5dd6cc08-e49a-4b36-95cb-af6576432653)
![image](https://github.com/DARPA-ASKEM/terarium/assets/120480244/52030e94-4416-4493-b171-8eb1097954a3)

### Using the LLM to set a configuration
The LLM can fill out the fields on the context and values pages. Enter a question and it will fill out the form on your behalf. You can either accept or discard its suggestion. If you click discard, it will clear the form. If you click accept, the LLM box resets to its base state, and you can either continue editing manually or click Run.
![Configure model - LLM stuff](https://github.com/DARPA-ASKEM/terarium/assets/120480244/cc0c766c-8dc2-4cec-9cb1-9b464f368545)
![image](https://github.com/DARPA-ASKEM/terarium/assets/120480244/3e7f2121-9471-48bc-a3be-ded1952e202f)![Configure model - LLM stuff 3](https://github.com/DARPA-ASKEM/terarium/assets/120480244/157545d8-82da-46e5-81d6-0b18ca44e5c7)
![Configure model - LLM stuff 4](https://github.com/DARPA-ASKEM/terarium/assets/120480244/6d5dfc17-e1e8-4e7f-a54e-0cb0e4e35f34)

## Filling in missing values
All missing values must be added before the configuration can be run. The current number of missing values error message is listed above the variable and parameter selection menu. Menu items in red indicate which values are missing and must be addressed. When all missing values have been populated, the error message above the tree menu disappears and the run button is enabled.
![Configure model - missing values](https://github.com/DARPA-ASKEM/terarium/assets/120480244/1919e599-3645-4592-9eca-ffadf92b74d8)
![Configure model - missing values 2](https://github.com/DARPA-ASKEM/terarium/assets/120480244/cdcbec77-d880-4357-bbfb-c01f56bcd384)
![Configure model - missing values 3](https://github.com/DARPA-ASKEM/terarium/assets/120480244/eb1a5c27-a4ae-46b3-97f4-5553a18f3ccc)
![Configure model - missing values 4](https://github.com/DARPA-ASKEM/terarium/assets/120480244/272dd863-921a-43bd-a253-46045564b6a8)

### Matrix drilldown
When viewing a top-level variable or parameter, the associated matrix can be opened by clicking the “Open Matrix” button in the Set Values form or in the configuration output tables. All values associated with a variable or parameter can be viewed and modified in the matrix table. A dropdown to change the source of the matrix table allows the user to swap all values in one go. The matrix can be downloaded as a CSV file, modified and then re-uploaded if the user would prefer to make bulk changes in a spreadsheet.
![image](https://github.com/DARPA-ASKEM/terarium/assets/120480244/ef21d278-c14f-4ef9-a74f-b08f9b9265b7)
![image](https://github.com/DARPA-ASKEM/terarium/assets/120480244/3ad4ae2d-4ac2-4e9e-9775-1a213526246b)
** I'd love to see a Matrix transition when this opens, as in: [https://github.com/javascriptacademy-stash/digital-rain](https://github.com/javascriptacademy-stash/digital-rain)
![image](https://github.com/DARPA-ASKEM/terarium/assets/120480244/68a0bff3-6aaa-4ed3-a998-700fed1be816)

## Output preview
Here's what a valid output looks like.
![image](https://github.com/DARPA-ASKEM/terarium/assets/120480244/9c4f71c4-efd1-4f88-bd3f-e1587a2a5bc3)
![image](https://github.com/DARPA-ASKEM/terarium/assets/120480244/96e6a505-dd9d-47de-9c0c-c94d61ade3ad)

# Other scenarios
## When a code file is attached
The LLM can pull information out of the attached code file to populate context and values. When viewing a value or parameter, all possible values (sourced from the attached files) that can be used appears below the form as options for the user. Each card has a link that, when clicked, opens a code viewer modal with the appropriate line of code highlighted. If the Use This Value button is clicked, the value is ported into the Value field and the label changes from Possible Values to Source. If the user deletes the value from the input field, it reverts back.
![image](https://github.com/DARPA-ASKEM/terarium/assets/120480244/7eafbb5b-cac8-4747-8558-680530438270)
![image](https://github.com/DARPA-ASKEM/terarium/assets/120480244/21c38d19-cd68-41e7-b787-1009898f482d)
![image](https://github.com/DARPA-ASKEM/terarium/assets/120480244/0d231541-d38c-4ad2-9965-4484877e5320)
![image](https://github.com/DARPA-ASKEM/terarium/assets/120480244/d975cc77-c3f6-4eac-8427-c49ab68f529a)

## When a document is attached
This is the same as above, but with a PDF viewer.
![image](https://github.com/DARPA-ASKEM/terarium/assets/120480244/8d3b173e-bcef-46ad-8a43-0e65bddb07ea)
![image](https://github.com/DARPA-ASKEM/terarium/assets/120480244/c0b2b49c-bf09-4e32-a07d-6471e27e7fd8)
![image](https://github.com/DARPA-ASKEM/terarium/assets/120480244/e8dd0503-ce23-4fa9-80b5-16cc38589ff0)

**Comment by mwdchang** [comment]
model-configuration operator has an updated design
