### ISSUE TITLE
[TASK]: Add code user blocks to the code to model operator

### ISSUE THREAD

**Issue by YohannParis** [DARPA-ASKEM/terarium#2417]
**Describe the task**
Per design a user is able to add one or more _code block_ to the _code to model_ operator. Those code blocks will now be used to help create a new model. But the user created code blocks are not part of the `Code` asset used as _input_ of the operator.

To enable this features, one solution needs to be selected to move forward:

1. When a user add a new _code block_ to the operator state, the `Code` asset used as _input_ is updated with a new file named `code_to_model-[Timestamp].[language file extension]` and containing the _code block_ code. This means the _code block_ needs to be selected as an _ouput_ of the `Code` asset operator. But needs to be unchecked (as in _include in process_ checkbox) for other _outputs_ state by default.
2. Update the [code_to_amr](https://github.com/DARPA-ASKEM/knowledge-middleware/blob/main/worker/operations.py#L776) operations of the `knowledge-middleware` worker to stop using the `data-service` itself and receive code information directly.

**Task Items**
- [ ] Decide which path to go forward: Edit `Code` asset used as input, or update `knowledge-middleware`.
- [ ] Add the functionality to add user created _code block_ to the operator state.

**Comment by mwdchang** [comment]
create model from code is currently deprecated
