### ISSUE TITLE
[TASK]: Investigate using askem-julia for doing model-service related tasks

### ISSUE THREAD

**Issue by mwdchang** [DARPA-ASKEM/terarium#2468]
There are a lot of overlaps between the dependencies of model-service and the dependencies of askem-julia. And to some degree, beaker - which uses askem-julia performs somewhat compatible and complementary functions to that of model-service.

To that end, ideally both askem-julia and model-service should use the same versions of packages. Since askem-julia can be thought of as an engine of sort, we can try to leverage it rather than to bootstrap nearly identical packages. 

In chatting with Five and Tom, we floated an idea of making the web-service in a different language (e.g. JS, python), and it then makes a call out to the askem-julia binary/image. In this way askem-julia is shared across multiple repos. An added benefit is that boiler plate code are easier to write and to develop - more familiarity and reduce the amount of Julia (pre)compilatons.

Docker for beaker that uses existing askem-julia image
- https://github.com/DARPA-ASKEM/beaker-kernel/blob/main/Dockerfile

References: for making external calls to Julia from X
- Python: https://github.com/JuliaPy/PythonCall.jl
- NodeJS doesn't seem like it is in active dev: https://github.com/maxmouchet/julia-node-extension-demo

**Comment by YohannParis** [comment]
Not relevant anymore
