### ISSUE TITLE
[TASK]: Calibration Design cleanup

### ISSUE THREAD

**Issue by Tom-Szendrey** [DARPA-ASKEM/terarium#2498]
Getting back to design a bit more:

- [ ] - Mapping header section fill
- [x] - Mapping header icons for model + dataset
- [x] - subline of description text for each accordion tab
- [x] - button icons added
- [ ]  - button styling
- [x] - accordion tabs so we dont get lost
- [ ] - run/close button styling 
- [ ] - close button label
- [ ] - Probabilistic -> Number of iterations -> iterations
- [ ] - Solver method vs ODE Solver vs Calibrate method
- [ ] - Chains vs num of samples?

**Comment by YohannParis** [comment]
Is this still needed?

**Comment by Tom-Szendrey** [comment]
outdated - soon to be fully revamped from design team
