### ISSUE TITLE
[TASK] Enhance the "Document to Model" Operator

### ISSUE THREAD

**Issue by YohannParis** [DARPA-ASKEM/terarium#2559]
- [x] 1. Add a new input of type `text`.
- [x] 2. Automatically run extractions endpoints upon connecting text.
- [x] 3. Display the Model Card in the preview panel
- [x] 4. Add a toggle to Select between TA1(Knowlege-middleware) and TA4 (GoLLM)

**Comment by blanchco** [comment]
Blocked by knowledge middleware
