### ISSUE TITLE
[TASK] Enhance "Code to Model" operator

### ISSUE THREAD

**Issue by YohannParis** [DARPA-ASKEM/terarium#2560]
- [x] 1. Add a new input of type `text`
- [x] 2. Automatically run extractions endpoints upon connecting text. When the user click on `Run` to update the controller to run the model card on knowledge-middleware once the model is returned.
- [x] 3. Display the Model Card in the preview panel
- [ ] #2644
- [x] 5. Allow "Add to code block" to work
- [x] 6. Allow to save those code bloc as a `Code` Asset

**Comment by blanchco** [comment]
Blocked by knowledge middleware
