### ISSUE TITLE
[EPIC] TA3 operator review tasks (to be broken down and prioritized)

### ISSUE THREAD

**Issue by mwdchang** [DARPA-ASKEM/terarium#2580]
@mwdchang @pascaleproulx @Tom-Szendrey @Jami159 @YohannParis @dgauldie 

On Monday Jan 15, we had a review of the current status of all the TA3 workflow boxes/operators (`Simulate, Calibrate, Optimize` in `Probabilistic, Deterministic, Ensemble` variants) in Terarium. Here are the tasks, unprioritized as yet:

Edit Jan-24: Moved into different subsections to make tracking easier

### Done
- We need to be able to add & remove "interventions" in the `Configure Model` box (@blanchco)
- Update design and fix CIEMSS ensemble simulate @mwdchang 
- Check that the `Probabilistic, Deterministic` variants of boxes return the same results (simulate)
- PyCIEMSS `Optimize` service needs to be set up and wired to the `Optimize` workflow box 
- Optimize operator plumbing in Terarium
- The auto-mapping between variables and dataset columns should be 1-to-1 #2790 
- Show the "spinner" (while a process is running) and the result charts (when complete) in the workflow boxes
- The intermediate results (loss function chart in `Calibrate`) need to _not_ disappear after the process is complete 
- The "Notebook" tab of the `Transform Dataset` should show the dataset in full by default (currently, the user has to select columns)
- CIEMSS ensemble calibrate to have status/spinner on workflow 
- `Transform Dataset` box need to be updated to be consistent with design sketches

### Waiting, blocked
Intermediate result need to wait for the TDS migration to calm down, then we can move forward to store the intermediate representations on S3/ES for later use.

**Comment by YohannParis** [comment]
Guys please update this into distinct tasks

**Comment by Tom-Szendrey** [comment]
> Guys please update this into distinct tasks

Will update the bullet points in this task first, i believe the vast majority of these are done as it is

**Comment by Tom-Szendrey** [comment]
Updated this to only contain the finished tasks and created 3 new tickets for the remaining tasks.
All new tickets are in the newest sprint in feature planning just for visibility
