### ISSUE TITLE
subset dataset operator

### ISSUE THREAD

**Issue by shawnyama** [DARPA-ASKEM/terarium#2613]

**Comment by ngraham76** [comment]
> @ngraham76 could you provide the Figma design for this operator please?

Sure thing, it's here:
https://www.figma.com/file/w4BmFSXhtXTqQy3T7cpWy3/Terarium---January-2024?type=design&node-id=553%3A115639&mode=design&t=EwsKEzeb3IDTjDVL-1

<img width="973" alt="image" src="https://github.com/DARPA-ASKEM/terarium/assets/141876103/242f0e12-145a-427f-af85-46270ad1401c">
