### ISSUE TITLE
[BUG]: Equations are not preserved after adding a text document to the 'create model from document' operator

### ISSUE THREAD

**Issue by pascaleproulx** [DARPA-ASKEM/terarium#2723]
**Describe the bug**
Trying to enrich with text after having created the model from equations remove all equations but the first one.

**To Reproduce**
1. On a workflow in this [project](https://app.staging.terarium.ai/projects/f8007e36-f026-47c7-b671-27b471a83dc9/WORKFLOW/505951df-eeb0-460d-89d8-a0d32c3cdbd7), add a 'create model from a document'
2. Add these equations (one at a time...) to create a sidarthe model:
\frac{dS}{dt} = -\alpha S I -\beta S D -\gamma S A -\delta S R
\frac{dI}{dt} = \alpha S I +\beta S D +\gamma S A +\delta S R - \epsilon I -\zeta I -\lambda I
\frac{dD}{dt} = -\eta D + \epsilon I - \rho D
\frac{dA}{dt} = -\kappa A -\theta A -\mu A +\zeta I
\frac{dT}{dt} = -\tau T +\mu A +\nu R -\sigma T
\frac{dH}{dt} = \kappa A + \xi R +\sigma T +\rho D + \lambda I
\frac{dE}{dt} = \tau T
\frac{dR}{dt} = \eta D + \theta A -\nu R -\xi R
3. Run the operator => success, you have a valid model :)
4. Go back the the workflow and add a link between the text from the document and the operator like this:
![image](https://github.com/DARPA-ASKEM/terarium/assets/42645294/5b1f30f3-5a35-4508-bfa5-09eea1f544da)
5. Open the operator: it lost all its equations but the first one.

**Expected behavior**
The equations should be preserved.

**Screenshots**
<img width="1494" alt="image" src="https://github.com/DARPA-ASKEM/terarium/assets/42645294/dca08047-a0d7-4f4d-bd81-3d26b71da688">

**Comment by asylves1** [comment]
Cannot reproduce looks like it has been fix already.
