### ISSUE TITLE
[BUG]: Can't plug a simulation output into a transform data operator

### ISSUE THREAD

**Issue by pascaleproulx** [DARPA-ASKEM/terarium#2733]
**Describe the bug**
Can't plug a simulation output into a transform data operator. 

**To Reproduce**
1. Configure and run a model or use this [workflow](https://app.staging.terarium.ai/projects/f8007e36-f026-47c7-b671-27b471a83dc9/WORKFLOW/519320d3-53bd-4163-82b2-cd0b3ded67b1)
2. Add a transform data operator and try to connect the simulation output to it. It does not work.

**Expected behavior**
Running a simulation should automatically create a temporary dataset that can be connected to a transform data operator.

**Comment by Tom-Szendrey** [comment]
This appears to have been done


![Image](https://github.com/DARPA-ASKEM/terarium/assets/17088680/8b2ce71b-b2bd-41b6-a3c5-ee744c129ba7)



![Image](https://github.com/DARPA-ASKEM/terarium/assets/17088680/0f772af3-4f40-4a33-ac9d-3699384ffa6d)
