### ISSUE TITLE
[TASK]: Add LLM agent interface for stratify

### ISSUE THREAD

**Issue by mwdchang** [DARPA-ASKEM/terarium#2741]
Add LLM agent interface for doing stratification with natural language, we used to do this via the model-transform operator, so part of the work will be migrating the logic there into a single notebook-cell context.

**Comment by Tom-Szendrey** [comment]
This has been done with another issue
![image](https://github.com/DARPA-ASKEM/terarium/assets/17088680/9c556385-b464-47fe-b513-ddd68d5a0c99)
