### ISSUE TITLE
Logging and timing of terarium activities

### ISSUE THREAD

**Issue by dgauldie** [DARPA-ASKEM/terarium#2778]
We have logging during the last eval.  This is in the client event code.
Verify that we still have logging, and then, is it acceptable - are there areas we should add it to?

Items to add/change

- [x] get rid of pause/resume and keep start/stop
- [x] log the time the user spends in each operator drilldown
- [x] Add precanned scenarios/tasks/descriptions
- [x] Add checkbox to denote multiple users

**Comment by dvince2** [comment]
`tera-navbar.vue` 

Evaluation scenario from the profile:

Scenario needs to be a dropdown (from doc. Scenario 1.1, 1.2, 2.1.a, etc)
Premade json with scenario and task question.

Add checkbox that means multiple people at bottom of form, or dropdown/spinner?. <input type=number>.

Don't hide on "Begin"

**Comment by dvince2** [comment]
https://docs.google.com/document/d/1DNKJ9fXlycx_k7xBecYzVh8NORyrIihWzImHgexQQzg/edit
