### ISSUE TITLE
add pyciemss beaker context to optimize and others

### ISSUE THREAD

**Issue by Tom-Szendrey** [DARPA-ASKEM/terarium#3128]
Add the pyciemss beaker context to the following operators:

- [ ] Optimize
- [ ] Calibrate
- [ ] #3808
- [ ] Ensemble simulate
- [ ] Ensemble calibrate

The objective is to allow the user to write their own pyciemss code allowing them more control over the calls they wish to make.
The output should be the std output from the code cell

**Comment by Tom-Szendrey** [comment]
This is on pause as I am unsure how to save output for a node with arbitrary code written by the user

**Comment by blanchco** [comment]
Closing this ticket until we have further information from @liunelson on what we want to do with pyciemss notebook context

cc @mwdchang @Tom-Szendrey
