### ISSUE TITLE
Stock & Flow to LaTeX not working

### ISSUE THREAD

**Issue by YohannParis** [DARPA-ASKEM/terarium#3282]
Loading a stock and flow model looks very fine, the issue there is not equations. 
This might be solved by updating Mira to the latest as it has been updated. 
https://app.terarium.ai/projects/efbd7399-2e5e-429f-ba89-9cfa8f5c0e88/model/e197b0d3-d853-42e0-8b85-6a7d0948781f

**Comment by YohannParis** [comment]
Based on TA3, this issue is due to the model using unorthodox MathML `<pulse/>`.
They cannot convert it to equations.
Requested to use `422 Unprocessable Entity` error instead for better error handling on the front-end.

**Comment by mwdchang** [comment]
Stock-n-flow support has largely been deprecated.
