### ISSUE TITLE
[TASK]: Smarter Terarium CI-build

### ISSUE THREAD

**Issue by mwdchang** [DARPA-ASKEM/terarium#3320]
Currently as part of client/server build in Terarium, regardless of where things have been changed we create new versions of
- gollm-taskrunner
- mira-taskrunner
With funman-taskrunner to be added to the collection

Ideally we would only build them if the relevant files had been changed. This would save build time/resources and we don't need to constantly pulling down task runner images.

Note there are a few slight caveats in terms of how the files are setup:
- The MIRA task scripts are within Terarium, while
- The GoLLM scripts on the other hand are in the gollm repo

**Comment by YohannParis** [comment]
close by #3369
