### ISSUE TITLE
Implement design update to the Calibrate Model operator

### ISSUE THREAD

**Issue by Tom-Szendrey** [DARPA-ASKEM/terarium#3331]
- [x] Ciemss Calibrate is returning a parameters.dill that is currently being unused. we need it to also sample this distribution, make a Simulate call, and some simulation result
- [ ] We also need to show a plot of this posterior distribution (maybe start with Joseph's viz work)

**Comment by Tom-Szendrey** [comment]
In order to sample parameters.dill it may help to check out what Nelson wrote:

```
calibrated_results = pyciemss.calibrate(
    model1, 
    dataset1, 
    data_mapping = data_mapping, 
    num_iterations = num_iterations
)

parameter_estimates = calibrated_results["inferred_parameters"]

calibrated_sample_results = pyciemss.sample(
    model1, 
    end_time, 
    logging_step_size, 
    num_samples,
    start_time = start_time, 
    inferred_parameters = parameter_estimates
)

data0 = calibrated_sample_results["data"][calibrated_sample_results["data"]["timepoint_id"] == 0]

parameters = list(parameter_estimates().keys())
parameter_samples = {p: data0[p + "_param"] for p in parameter_estimates().keys()}

parameter_statistics = {
    p: {
        "mean": np.nanmean(parameter_samples[p]), 
        "std": np.nanstd(parameter_samples[p])
    }
    for p in parameters
}
```

**Comment by liunelson** [comment]
Design update is complete and ready for implementation:
https://www.figma.com/design/EoihrRoNNbuOAJtudKqp7L/Terarium---June-2024?node-id=1-26505&t=nlgqHpBvqQFvdpEC-0

**Comment by liunelson** [comment]
@Tom-Szendrey 
This notebook contains the steps for transforming the result of `pyciemss.calibrate(...)` into what's needed for the charts in the `Calibrate Model` operator:
https://github.com/liunelson/pyciemss/blob/nl-test/notebooks/test_calibrate_interface.ipynb

I ran 3 simulations:
1. Simulate the model using an initial (pre-calibration) configuration
2. Calibrate this model configuration with a training dataset
3. Simulate the model using the calibrated (post-calibration) configuration

Let me know if unclear.
