### ISSUE TITLE
Model Configuration update without refresh

### ISSUE THREAD

**Issue by Tom-Szendrey** [DARPA-ASKEM/terarium#3391]
the temporary model-config objects were wrapped inside a parent wrapper, and because of that the reactivity downstream have have been impacted.

- [ ] Correct this for updating cell values
- [ ] Check for other places this same logic has been applied

An example of this can be seen below:
(Only shows changes when we leave and come back/refresh)
https://github.com/DARPA-ASKEM/terarium/assets/17088680/c2356ac0-7738-489c-8b11-933cfba5eef8

https://github.com/DARPA-ASKEM/terarium/blob/main/packages/client/hmi-client/src/model-representation/service.ts#L33

https://github.com/DARPA-ASKEM/terarium/blob/2313a9b822b8463a5bed5e1e493e1544836b4ef0/packages/client/hmi-client/src/components/model/petrinet/tera-initial-table.vue#L373-L377

**Comment by Tom-Szendrey** [comment]
@blanchco  Please feel free to update any details I believe you may know more about this

**Comment by blanchco** [comment]
sounds good, this will probably be swept up in the model config redesign

**Comment by blanchco** [comment]
looks like this has already been fixed. closing
