### ISSUE TITLE
[BUG]: show/hide model description is broken for short text

### ISSUE THREAD

**Issue by bencodrington** [DARPA-ASKEM/TERArium#347]
**Describe the bug**
Models with short descriptions are overlapped by the button.
It also doesn't make sense to show an expand/collapse button at all when a description is that short.

**To Reproduce**
1. Open a model with a short description (perhaps Zhao2020? As shown in the screenshot below)
2. Notice that the beginning of the text is overlapped.

**Expected behavior**
Don't show the faded background or expand/collapse button when the description is less than 480 characters or so.
The description text is set to wrap after `120ch` ([approximately but not exactly 120 characters](https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Values_and_units)). The button allows 3rem (about 2 and a half lines, depending on line height) of uninterrupted description above it before the fade begins.

Be sure to test with many different lengths of text, with different window sizes.

**Screenshots**
![image](https://user-images.githubusercontent.com/16928557/206501621-9557efc0-546e-4c5c-a23c-ddbab3fd1d46.png)

**Additional context**
We expect to use similar behaviour and appearance in other parts of the app. Consider extracting a new expandable text component for later reuse.

**Comment by mwdchang** [comment]
No longer relevant due to design changes.
