### ISSUE TITLE
Create a new input component

### ISSUE THREAD

**Issue by YohannParis** [DARPA-ASKEM/terarium#3476]
We need a new basic input component that will handle the new label design, being able to call utilities to modify it's v-model/value.

In the future, or now, we need to display error message and status (yellow border, etc.).

Do not worry about design precision, will pass onto the Design team to ~fix~ improve it.

![Image](https://github.com/DARPA-ASKEM/terarium/assets/636801/8ded208f-0843-4c17-abbe-e8c7442aeaa6)

**Comment by ngraham76** [comment]
@YohannParis  @jamiewaese-uncharted Here are specs for this input component's error state. We wouldn't have a warning (yellow) state - all we need is _valid_ and _error_.

![image](https://github.com/DARPA-ASKEM/terarium/assets/141876103/43678375-830a-4808-972e-c7ba979120cd)

**Comment by ngraham76** [comment]
@YohannParis @blanchco  Slight adjustment: after talking to Jamie, the specs for the error state should be as follows (we had a couple of different variants of the error state in the designs - we'll go with this version).

![image](https://github.com/DARPA-ASKEM/terarium/assets/141876103/4364c4c6-2728-4324-a5d2-443424b62735)
