### ISSUE TITLE
Create Scientific Notation input

### ISSUE THREAD

**Issue by YohannParis** [DARPA-ASKEM/terarium#3477]
Using the new input #3476 and the new number utils #3467 
Create a component to enter numbers.

**Comment by liunelson** [comment]
I just reviewed `number.spec.ts` and made some comments on a few cases that may be missing.

Def not a priority, there may be a need in the future to support complex numbers
possibly: `1 + i2` and `-1 234.567 8e+2 - i 9.012 345e+1`
_Lovely_
