### ISSUE TITLE
[BUG]: initial variables and parameters are not saved for stratified models

### ISSUE THREAD

**Issue by dgauldie** [DARPA-ASKEM/terarium#3515]
**Describe the bug**
When stratifiying a model, if the user changes variable values, then saves, then presses the `Matrix` button, the matrix values show the original values and not the new ones. 

if you close the component and reload, the values are back to the original
if you save as a new model the original values are saves and not the new ones

**To Reproduce**

**Expected behavior**

**Screenshots**

![image](https://github.com/DARPA-ASKEM/terarium/assets/4194153/6c07b582-83ed-4d55-aed6-cc5c8f10cfff)

![image](https://github.com/DARPA-ASKEM/terarium/assets/4194153/adb64507-6e21-410e-b1fb-4d696d7d73cb)

**Additional context**

**Comment by pascaleproulx** [comment]
What is the context here? Are you making those value changes in the configure operator @dgauldie ?
