### ISSUE TITLE
[BUG]: some models cannot display model equations

### ISSUE THREAD

**Issue by dgauldie** [DARPA-ASKEM/terarium#3517]
**Describe the bug**
After stratifying a model and saving it as a new model, when a user tries to view it, there is a server error and no equations appear.

**To Reproduce**

**Expected behavior**

**Screenshots**

![image](https://github.com/DARPA-ASKEM/terarium/assets/4194153/806e21d2-9871-464b-ae13-aeec695f20cc)

**Additional context**

**Comment by shawnyama** [comment]
This isn't a stratified model issue, it seems to effect random models. I haven't come across this issue with a newly stratified model but I have in the following staging ids:
- `d51e837c-c720-1b9e-e1b6-fd3ad3f5207c`
- `e5edcfcb-93c4-929b-9b0c-4510a0295a88`
- `855aaecc-7a6f-4783-9e86-30cda6c616ab` (or any empty model that you create in the resource sidebar)
