### ISSUE TITLE
[BUG]: Unexpected error occurs when enriching model description without a document

### ISSUE THREAD

**Issue by jryu01** [DARPA-ASKEM/terarium#3520]
**Describe the bug**
Unexpected error occurs when enriching model description without a document
![Screenshot 2024-05-02 at 4 26 59 PM](https://github.com/DARPA-ASKEM/terarium/assets/3279838/011b4cb9-9140-40cc-9575-8518fe046bd8)

**To Reproduce**
1. Upload a model file ([SIR_Model](https://drive.google.com/file/d/1OwKCQTKSflTW4oAbdCQ8xGXeUYmbCryG/view?usp=drive_link)) using upload resources in a new project. 
2. Click and view created model from the resources panel
3. Click Enrich description -> Enrich description

**Comment by j2whiting** [comment]
You should always have a research paper (document) at the very least to produce a TA4 model card. It's better to have a research paper and a petrinet model

**Comment by asylves1** [comment]
It appears to be fixed, error is no longer appearing. 
Double checked with @jryu01
