### ISSUE TITLE
[BUG]: Edit Model

### ISSUE THREAD

**Issue by ngraham76** [DARPA-ASKEM/terarium#3648]
**Describe the bug**
Step 3a. of the Model Edit test, when opening viewing in the notebook, am not seeing the model updated as expected:

`(S) -> [t0] -> (I) -> [t1] -> (R) -> [NaturalConversion] -> (B2)`

What I see:
<img width="718" alt="image" src="https://github.com/DARPA-ASKEM/terarium/assets/141876103/5c61920b-5f71-4359-8e07-d825c9834bc4">

**To Reproduce**
Link an Edit Model operator to the Configured.json model
Open the Edit Model operator
Drag a Natural Conversion template into the canvas
Link port R from the t1 template to port A in the Natural conversion template.
Open the flattened view or the Notebook to view

**Comment by shawnyama** [comment]
This wasn't working at the time since beaker wasn't working.
