### ISSUE TITLE
[BUG]: Connection pipe / port issues with Model Edit

### ISSUE THREAD

**Issue by ngraham76** [DARPA-ASKEM/terarium#3650]
**Describe the bug**
Step 3b. of the Model Edit test, connecting theR port of the Natural Conversion template to the A port of the Configured SIR model results in what appears to be a "disconnected" pipe. When toggling over to the _Decomposed_ view, it's not clear what port in the Natural Conversion it's connected to. And when going back to the _Flattened_ view, the Natural Conversion template node is ... gone.

**To Reproduce**
Link an Edit Model operator to the Configured.json model
Open the Edit Model operator
Drag a Natural Conversion template into the canvas
Switch to Flattened view
Link port R from the Configured SIR node to port A2 in the Natural conversion template.
Note the disconnected pipe error
Switch to Flattened view
Note that it's not clear what Natural Conversion port is connected
Switch back to Decomposed view.
Note that the Natural Conversion node is now gone.

**Screenshots**
![image](https://github.com/DARPA-ASKEM/terarium/assets/141876103/21730e0a-8569-4c9b-abac-eec664266aaf)
![image](https://github.com/DARPA-ASKEM/terarium/assets/141876103/9ca512a4-4759-49de-bbf5-0fa08df82a03)
![image](https://github.com/DARPA-ASKEM/terarium/assets/141876103/fbf4c701-9f77-4183-b9cf-31c5c520c569)

**Comment by shawnyama** [comment]
This was acting up at the time since beaker wasn't working.
