### ISSUE TITLE
[BUG]: Validate Configuration upper bounds field loses focus

### ISSUE THREAD

**Issue by asylves1** [DARPA-ASKEM/terarium#3651]
**Describe the bug**
After each inputted number the field loses focus

**To Reproduce**
1. upload a model [Configured SIR.json](https://github.com/DARPA-ASKEM/terarium/files/15339274/Configured.SIR.json)
2. add it to a workflow
3. click 'add another constraint'
4. try changing Upper bound

**Expected behavior**
should not lose focus after add a number

**Screenshots**
![image](https://github.com/DARPA-ASKEM/terarium/assets/95376249/ff53b4e3-3255-44a3-9f7a-83ef466cde39)

**Comment by mwdchang** [comment]
The bad text-input interaction is a known issue, the problem is we regenerate the UI every time the number changes so you constantly lose focus is you type. 

Tracked here along with a few other things: https://github.com/DARPA-ASKEM/terarium/issues/3567
