### ISSUE TITLE
[BUG]: 400 error occurs when navigating from `/projects/{pid}/ workflow/{wid}` to main root page (`/`)

### ISSUE THREAD

**Issue by jryu01** [DARPA-ASKEM/terarium#3672]
**Describe the bug**
400 error occurs when navigating from `/projects/{pid}/ workflow/{wid}` to main root page (`/`)

**To Reproduce**
1. Create a project -> Upload a model
2. Create a workflow -> Add the created model
3. Click `terarium` logo to navigate to the main page. 
4. See 400 error

When navigating from the workflow page, it seems, GET `workflow/{wid}` is being called and getting error missing projectId from the main page.

**Comment by jryu01** [comment]
<img width="1505" alt="Screenshot 2024-06-07 at 4 11 47 PM" src="https://github.com/DARPA-ASKEM/terarium/assets/3279838/a0178d5b-10a5-42b8-a7a3-8e2899a7fe2c">

Note that now I'm getting 403 instead of 400

Also, you need to get back to the main page immediately after adding the model to the workflow. If you wait longer sometimes the error doesn't seem to appear.

**Comment by mwdchang** [comment]
I am not getting a 403 when this happens:
- Create a new workflow
- Go back to home page via the Terarium logo

It seems like we are updating without a valid project id.
