### ISSUE TITLE
Investigate bad models on prod (not related to migrations!)

### ISSUE THREAD

**Issue by dvince2** [DARPA-ASKEM/terarium#3695]
There are several models on production that have been brought over from older versions of TDS. they do not have valid UUIDs and cause issues when users attempt to interact with them.

**Comment by kbirk** [comment]
For simplicity sake, delete any duplicate assets that are soft deleted:

```
DELETE FROM project_asset
WHERE asset_id IN (
    SELECT asset_id
    FROM project_asset
    GROUP BY asset_id
    HAVING COUNT(asset_id) > 1
) AND deleted_on IS NOT NULL
```

Then query all remaining duplicate assets:
```
SELECT *
FROM project_asset
WHERE asset_id IN (
    SELECT asset_id
    FROM project_asset
WHERE deleted_on is NULL
    GROUP BY asset_id
    HAVING COUNT(asset_id) > 1
)
```

There are 191 rows on `staging` that share the same asset_id with another row.

All are of type `MODEL`, `DATASET`, or `DOCUMENT`.

**Comment by kbirk** [comment]
This will be fixed by the staging / pg wipe.
