### ISSUE TITLE
Data Service

### ISSUE THREAD

**Issue by brandomr** [DARPA-ASKEM/TERArium#37]
- [x] first draft of the data model
- [x] Setup PostGres and ES
- [x] Upload Starter Kit data
- [x] Setup CRUD APIs
- [ ] Setup data Query API 
- [ ] Integrate some of the _data-annotations_ logic
- [ ] Integration of DKG
- [ ] Search algorithm that match grounder models with grounded datasets

**Comment by brandomr** [comment]
This issue is to design an initial data model or storing:

* projects
* users
* datasets
* models
* simulations and simulation plans

It should include traceability information such as provenance and version history. This will be created using DBML and used as a discussion document before being ported into an ORM.

**Comment by YohannParis** [comment]
This will be taking care of by:
- https://github.com/DARPA-ASKEM/data-service/issues/18
- https://github.com/DARPA-ASKEM/data-service/issues/19
- https://github.com/DARPA-ASKEM/data-service/issues/20
- https://github.com/DARPA-ASKEM/data-service/issues/22
- https://github.com/DARPA-ASKEM/data-service/issues/24
