### ISSUE TITLE
[BUG]: Uploading dataset not working

### ISSUE THREAD

**Issue by Tom-Szendrey** [DARPA-ASKEM/terarium#3705]
When uploading a new dataset to the project we are getting an object that has multiple file names and no columns section filled in
This occurs when we only upload a singular file

Sample on staging:
https://app.staging.terarium.ai/projects/d7e690d5-ec81-4b01-8e97-295863454dfe/dataset/1501aea6-ddda-4b4d-a8c4-c8e7da18dd9b
![image](https://github.com/DARPA-ASKEM/terarium/assets/17088680/463cb5d4-52f5-430c-8a99-e099718c2193)

Sample object locally with the following file:
[simResult.csv](https://github.com/DARPA-ASKEM/terarium/files/15457529/simResult.csv)
![image](https://github.com/DARPA-ASKEM/terarium/assets/17088680/c6147e48-b4ca-4168-8240-5da7d9013c10)

```
{
    "id": "ca081a8c-bc2f-4c2d-9070-2bc79b18e635",
    "createdOn": "2024-05-27T14:59:13.498+00:00",
    "updatedOn": "2024-05-27T14:59:14.377+00:00",
    "name": "simResult",
    "description": "simResult.csv",
    "fileNames": [
        "simResult.csv",
        "simResult.csv"
    ],
    "temporary": false,
    "publicAsset": false,
    "userId": "7421f1cd-b9aa-4e26-be86-a4cefc3acc7e",
    "datasetUrls": [],
    "columns": []
}
```

**Comment by asylves1** [comment]
Talked to @dvince2 about the values missing from the columns. It appears to be an issue with database. Re-assigning it to @dvince2 .
