### ISSUE TITLE
[FEAT]: Cluster similar assets in the data explorer matrix view

### ISSUE THREAD

**Issue by amostafa-uncharted** [DARPA-ASKEM/TERArium#371]
**Feature description**
The data explorer contains a matrix view component that aims to display a summarized view of the focused search results. For examples, the goal is to group together related models in each row with the corresponding concepts as columns.

Currently, the clustering implementation of search results within the data explorer matrix view lacks grouping of items that share identical concepts. For example, if model1 and model2 have the exact set of concepts should be clustered into one group. The view currently shows ONE model per row and shows all concepts as columns. Ideally, this clustering implementation needs to be refined to group similar models or datasets into groups, each group as one row. Also, the group label should reflect the number of elements associated in it. 

Note that the matrix view for publications or papers is done differently and currently group all papers by clustering based on a specific field such as "journal". This means each row will show all the papers that are published by a given journal. Columns in this case will clearly reflect the journal names.

This task is all about re-visiting and refining clustering to true summarize similar items into groups, and the focus here will be on grouping models and datasets who share the same set of concepts

**Comment by YohannParis** [comment]
The matrix view doesn't exist anymore.
