### ISSUE TITLE
[TASK]: Fix inconsistency with regards to the "id" field for project assets

### ISSUE THREAD

**Issue by amostafa-uncharted** [DARPA-ASKEM/terarium#377]
**Describe the task**
An observed inconsistency relates to the “id” field that is part of various resources. For example, the models/datasets provide IDs as numbers while it is returned as string from XDD. This inconsistency forces the client side to maintain "id" as string OR number and to cast everything to string before doing ID comparison to avoid incorrect results.
See for example part of the code such as 
`toLowerCase().includes(term.toLowerCase())
`
The HMI server should make sure that all IDs of the same type to facilitate searching for and comparison of resources

**Task Items**
- [ ] Review all "id" fields in the code and clean improper casting and type definitions
- [ ] Ensure that all "id" fields are correctly mapped at the HMI server and communicate the need to the data service team and xDD team as necessary

**Goal**
A clear and concise description of what the end result must have for it to be approved as complete.

**Screenshots**
If applicable, add screenshots or designs

**Additional context**
Add any other context about the task here

**Comment by YohannParis** [comment]
@dvince2 I think that this has been fixed right?

**Comment by dvince2** [comment]
Negative.  Looking quickly, `Model`, `Dataset` and `ArtifactListItem` all still have inconsistent types for id.  Documents from xdd are good but this will need addressing (and maybe more)
```
export type Model = {
	id: string | number;
	...
};
```

**Comment by YohannParis** [comment]
Okay, maybe when we have some downtime, or maybe a mini-hackathon task will be to work for a week with @iross and us to clean up all of this.
