### ISSUE TITLE
[BUG]: model configuration notebook test, AI generates bad code

### ISSUE THREAD

**Issue by kbirk** [DARPA-ASKEM/terarium#3785]
Following this test: 
https://github.com/DARPA-ASKEM/terarium/blob/main/testing/manual/model-configuration-notebook.md

After I ask the AI to `Update R0 to 0.2` and run the code I get

```
KeyError

'R0'
[ "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m", "\u001b[0;31mKeyError\u001b[0m Traceback (most recent call last)", "Cell \u001b[0;32mIn[1], line 19\u001b[0m\n\u001b[1;32m 17\u001b[0m parameter_values \u001b[38;5;241m=\u001b[39m {\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mR0\u001b[39m\u001b[38;5;124m'\u001b[39m: \u001b[38;5;241m0.2\u001b[39m}\n\u001b[1;32m 18\u001b[0m \u001b[38;5;28;01mfor\u001b[39;00m kk, vv \u001b[38;5;129;01min\u001b[39;00m parameter_values\u001b[38;5;241m.\u001b[39mitems():\n\u001b[0;32m---> 19\u001b[0m \u001b[43mmodel_config\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mparameters\u001b[49m\u001b[43m[\u001b[49m\u001b[43mkk\u001b[49m\u001b[43m]\u001b[49m\u001b[38;5;241m.\u001b[39mvalue \u001b[38;5;241m=\u001b[39m vv\n", "\u001b[0;31mKeyError\u001b[0m: 'R0'" ]
```

Also the error output is a mess of escape codes

**Comment by brandomr** [comment]
@kbirk was this on staging or prod? I just tried on staging without issue from this [workflow node](https://app.staging.terarium.ai/projects/4adcc0cf-6b84-4f92-97bf-bf0ede655464/workflow/0bcb3443-72f9-4e28-b110-36c2cba0dc7e?operator=338e65dd-8b42-415e-a593-8f29930aedb6)




https://github.com/DARPA-ASKEM/terarium/assets/5840199/92d21e33-0a9b-461d-9d99-ec3413734599
