### ISSUE TITLE
[BUG]: Permissions error when opening a node in a new window

### ISSUE THREAD

**Issue by blanchco** [DARPA-ASKEM/terarium#3788]
**Describe the bug**
When you select "Open node in new window" on a workflow node the new window will open with a forbidden error:

testing/manual/test-workflow-interactions.md
2.4

https://github.com/DARPA-ASKEM/terarium/assets/33158416/2879259c-9095-41f8-bb19-2338270415cd

**Comment by YohannParis** [comment]
Will fix this feature another time.
