### ISSUE TITLE
[BUG]: model-configuration from document

### ISSUE THREAD

**Issue by mwdchang** [DARPA-ASKEM/terarium#3791]
Not really sure where this came from. In the GoLLM logs I see:
```
2024-06-07 15:51:32 [INFO] [67fe2b03-e8e0-4388-bb82-ee1c7f4ea4d6] stdout: Reading model config from research paper:  [software.uncharted.terarium.taskrunner.service.Task:371]
2024-06-07 15:51:32 [WARN] [67fe2b03-e8e0-4388-bb82-ee1c7f4ea4d6] stderr: Error: Error decoding JSON: Expecting property name enclosed in double quotes: line 1 column 11 (char 10) [software.uncharted.terarium.taskrunner.service.Task:384]
2024-06-07 15:51:32 [INFO] [67fe2b03-e8e0-4388-bb82-ee1c7f4ea4d6] stdout: Modelling the COVID-19 epidemic and [software.uncharted.terarium.taskrunner.ser
```

While the follow errors were propagated into the HMI:

> Failed: /usr/local/lib/python3.10/site-packages/pydantic/_internal/_fields.py:149: UserWarning: Field "model_cards" has conflict with protected namespace "model_". You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`. warnings.warn( Error: Error decoding JSON: Expecting property name enclosed in double quotes: line 1 column 11 (char 10) from text { { "conditions": { "no_intervention": "No social-distancing countermeasures were applied", "mild_intervention": "Social-distancing countermeasures had a mild effect", "strong_intervention": "Social-distancing countermeasures were stronger", "very_strong_intervention": "Social-distancing countermeasures were very strong", "loss_of_immunity": "Recovered individuals can become susceptible again after day 50", "increased_testing": "A wider testing campaign is launched after day 38" }, "parameters": [{ "id": "alpha", "value": { "no_intervention": 0.422, "mild_intervention": 0.285, "strong_intervention": 0.200, "very_strong_intervention": 0.057, "loss_of_immunity": null, "increased_testing": null } }, { "id": "beta", "value": { "no_intervention": 0.0057, "mild_intervention": 0.0057, "strong_intervention": 0.0057, "very_strong_intervention": 0.0057, "loss_of_immunity": null, "increased_testing": null } }, { "id": "gamma", "value": { "no_intervention": 0.285, "mild_intervention": 0.171, "strong_intervention": 0.086, "very_strong_intervention": 0.057, "loss_of_immunity": null, "increased_testing": null } }, { "id": "delta", "value": { "no_intervention": 0.0057, "mild_intervention": 0.0057, "strong_intervention": 0.0057, "very_strong_intervention": 0.0057, "loss_of_immunity": null, "increased_testing": null } }, { "id": "epsilon", "value": { "no_intervention": null, "mild_intervention": null, "strong_intervention": null, "very_strong_intervention": null, "loss_of_immunity": null, "increased_testing": 0.200 } }, { "id": "theta", "value": { "no_intervention": null, "mild_intervention": null, "strong_intervention": null, "very_strong_intervention": null, "loss_of_immunity": null, "increased_testing": null } }, { "id": "zeta", "value": { "no_intervention": null, "mild_intervention": null, "strong_intervention": null, "very_strong_intervention": null, "loss_of_immunity": null, "increased_testing": null } } ] }

**Comment by bigglesandginger** [comment]
Unreproducible
