### ISSUE TITLE
[BUG]: Failed to create model from code

### ISSUE THREAD

**Issue by YohannParis** [DARPA-ASKEM/terarium#3794]
![Screenshot 2024-06-07 at 12 44 36](https://github.com/DARPA-ASKEM/terarium/assets/636801/53a2ee03-dfb1-44bc-9a53-238269486302)

**To Reproduce**
Step 3.5 of [model-from-code](https://github.com/DARPA-ASKEM/terarium/blob/main/testing/manual/model-from-code.md)

**Comment by mwdchang** [comment]
model from code not currently supported
