### ISSUE TITLE
[BUG]: resetting a stratified model does not reset everything

### ISSUE THREAD

**Issue by dgauldie** [DARPA-ASKEM/terarium#3798]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
1. the original model: 
![image](https://github.com/DARPA-ASKEM/terarium/assets/4194153/203e4eaa-934d-47fe-b782-b9daa7fe30e5)

2. the stratified model 
![image](https://github.com/DARPA-ASKEM/terarium/assets/4194153/1d34a044-6bc7-4205-a951-cced2d3c8837)

3. press the rest button
![image](https://github.com/DARPA-ASKEM/terarium/assets/4194153/a2ea50a3-589a-44f0-871f-fca5de65d868)

4. the legend is still visible in the graph

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by YohannParis** [comment]
Fix the legend reactivity.
