### ISSUE TITLE
[BUG]: Model configurations do not update when linked stratified model changes

### ISSUE THREAD

**Issue by dgauldie** [DARPA-ASKEM/terarium#3803]
**Describe the bug**

**To Reproduce**

1. create and run a stratification on an SIR model for age with only young and old groups
![image](https://github.com/DARPA-ASKEM/terarium/assets/4194153/a75b27f9-353a-4d67-b99a-2a47922f8950)

2. linked to a model configuration
![image](https://github.com/DARPA-ASKEM/terarium/assets/4194153/e661730b-bdb7-4c4a-9f41-4526d1e00c9a)

3. change the stratification and add a `middle` group, run, and set as new output
![image](https://github.com/DARPA-ASKEM/terarium/assets/4194153/949351ee-d87e-4afb-8717-c23c347e98aa)

4. the resulting model configuration does not have all stratified initial parameters
![image](https://github.com/DARPA-ASKEM/terarium/assets/4194153/e661730b-bdb7-4c4a-9f41-4526d1e00c9a)

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by blanchco** [comment]
It looks like this may have been fixed at some point, I cannot reproduce it.  I followed the steps above and the resulting model configuration is properly showing with all stratified parameters.

![Image](https://github.com/user-attachments/assets/95d62408-9de2-4924-8d00-80ffe4769874)
