### ISSUE TITLE
[BUG]: Initial variables and parameters are not being updated on subsequent stratifications

### ISSUE THREAD

**Issue by dgauldie** [DARPA-ASKEM/terarium#3805]
**Describe the bug**
After a stratification some parameters are lost or not updated.

**Screenshots**
![image](https://github.com/DARPA-ASKEM/terarium/assets/4194153/25b59eec-e9f7-4e9c-b8a1-20f095e587cc)

**Comment by blanchco** [comment]
@YohannParis I am not able to reproduce this...the values seem to be stratifying properly, and Im not losing any parameters values

**Comment by liunelson** [comment]
@dgauldie 
I can't reproduce this issue in your project/workflow:
* I stratified a SIR model by age (y, o) over all parameters and variables
* Then I stratified the result by intelligence (s, d) over only the S_y, I_y, R_y variables
* The doubly-stratified model looks right
![Screenshot 2024-07-02 at 1 12 53 PM](https://github.com/DARPA-ASKEM/terarium/assets/1030720/5c323505-aaea-4c6a-86c4-7dd6e62b11f7)

https://app.staging.terarium.ai/projects/64a38156-9815-40f6-bf7a-dcd8e4559d3e/workflow/7f2e0c84-1cae-4549-9a44-b7e4c6f67bff?operator=760ed4d7-cf32-4490-bdc0-7d10db672e7f

Could you give more details?
