### ISSUE TITLE
[BUG]: `Stratify model` Save as new model does not update output

### ISSUE THREAD

**Issue by YohannParis** [DARPA-ASKEM/terarium#3849]
**Describe the bug**
Following the test [Model Stratify Step 2.21](https://github.com/DARPA-ASKEM/terarium/blob/main/testing/manual/stratify-model.md).
Live project as QA user: https://app.staging.terarium.ai/projects/b0a98ccb-d186-449e-a703-e151dea3f18f/workflow/a8c9b331-3915-4fc3-9093-77584f6fb834?operator=32dc66fc-23e2-408f-9ad6-2df35ae8ed01

Saving the output as a new model, and giving it a name doesn't update the output with the name provided in the modal box.

**Comment by YohannParis** [comment]
This should be a common behaviour on all output that produce TerariumAssets.

**Comment by mwdchang** [comment]
The "save as XYZ" function and the outputs are two distinct ideas
- The output holds an instance of the artifact created
- The "Save as", as I understand,  creates a _new_ instance of something that may or may not match the object-type of the output

So right now this doesn't make a lot of sense, it is kind of like saying "I bought an apple and I want to change the name of the orange on my table".

If we want to have a different behaviour, we should discuss.

**Comment by mwdchang** [comment]
consolidate to: https://github.com/DARPA-ASKEM/terarium/issues/4320
