### ISSUE TITLE
[BUG]: dataset enrichment without a document fails

### ISSUE THREAD

**Issue by dgauldie** [DARPA-ASKEM/terarium#3854]
**Describe the bug**
while enriching a dataset, the resulting table contains both enriched and unenriched rows

**To Reproduce**
1. Upload the dataset [SIR_Dataset](https://drive.google.com/file/d/1wdCLKKznHaoCg1gWI7q7OO8W4F7zOjpc/view?usp=drive_link)
2. Go to SIR dataset (uploaded and created dataset) from the resource panel
3. Click Enrich description -> Click Enrich description from the modal

**Expected behavior**

**Screenshots**

![image](https://github.com/DARPA-ASKEM/terarium/assets/4194153/80583538-5ff1-453b-b186-45ca68ff252d)

**Additional context**

**Comment by shawnyama** [comment]
This didn't really fail, its just that those enriched rows are appended while they should be replacing those empty ones
