### ISSUE TITLE
[FEAT]: Calibrate PyCIEMSS graph should have a legend/colours

### ISSUE THREAD

**Issue by bigglesandginger** [DARPA-ASKEM/terarium#3859]
**Is your feature request related to a problem? Please describe.**
The variables graph (where one can choose multiple variables to be graphed together) displays all variables as black points, making distingushing the variables impossible at a glance

**Describe the solution you'd like**
Provide a visual difference between the lines (colour for instance) and a legend as to which variable corresponds to which colour

**Describe alternatives you've considered**

**Additional context**

**Comment by mwdchang** [comment]
@Tom-Szendrey can you check is this is still an issue? if not feel free to close.

**Comment by mwdchang** [comment]
We split into variable-chart and comparison-chart and this should be addressed now
