### ISSUE TITLE
[BUG]: Model Edit testing issues

### ISSUE THREAD

**Issue by jamiewaese-uncharted** [DARPA-ASKEM/terarium#3862]
**Describe the bug**
Multiple issues while trying to follow the Model Edit testing protocol found here, on staging on June 13 at 2pm: https://github.com/DARPA-ASKEM/terarium/blob/main/testing/manual/model-edit.md

**ISSUE 1**
The MODEL-EDIT test partially fails at step 2.5. After uploading the Configured SIR.json, dragging it onto a new workflow and attaching it to an Edit model operator, when you click to open it, you get this.
However, if you close the operator and reopen it, it opens properly.

![image](https://github.com/DARPA-ASKEM/terarium/assets/120480244/14af1b60-2083-44ad-9ad1-87f72515b553)
![image](https://github.com/DARPA-ASKEM/terarium/assets/120480244/63b45088-9903-4788-ad28-13263ee003d9)

**ISSUE 2**
The MODEL-EDIT test partially fails at step 3a-2. I linked port R from the t1 template to port B by accident. That's when I discovered there are is no way to disconnect ports. We probably need an unlink button like on the workflow nodes.
So I clicked the reset button and got an alert that the model was reset, but my canvas looks the same. Closing the operator and reopening it restores it.
![image](https://github.com/DARPA-ASKEM/terarium/assets/120480244/cfaf7c76-94c6-4e37-859a-e1d1972ca936)
![image](https://github.com/DARPA-ASKEM/terarium/assets/120480244/9399ba17-5b54-45d3-9c07-0483085a17ff)
![image](https://github.com/DARPA-ASKEM/terarium/assets/120480244/62078fbf-a444-4c4b-80c6-319c5c2cb2b2)

**ISSUE 3**
The MODEL-EDIT test partially fails at step 4-2. Clicking 'Save' produces this error. Closing the operator and reopening it, then clicking 'Save' again is successful.
![image](https://github.com/DARPA-ASKEM/terarium/assets/120480244/a6bb2ef2-9cc3-46dc-a282-3418b4c6e5ad)

**ISSUE 4**
The MODEL-EDIT test gets a partial design fail at step 4-2. In the output selector, there is some helper text that says "Select outputs to display in operator". This is vestigial from when we were playing with the idea that operators could have multiple outputs. It should probably just say "Select output to display"
![image](https://github.com/DARPA-ASKEM/terarium/assets/120480244/05e1b385-e97f-4fad-990c-0943fea57253)

Another partial design fail from this...
![image](https://github.com/DARPA-ASKEM/terarium/assets/120480244/899652fd-5cb2-464a-aa3b-e8c7f4d5dc4b)

**ISSUE 5**
And another partial fail when trying to save the model. First you get an error, then if you reload the site, it works.
![image](https://github.com/DARPA-ASKEM/terarium/assets/120480244/1e766d4e-a00b-403a-959e-efd2d4b15532)
![image](https://github.com/DARPA-ASKEM/terarium/assets/120480244/b63d8de0-0252-4849-a31f-323e461d11e3)

**Comment by YohannParis** [comment]
@bigglesandginger  looks like most connection fails after 5 seconds, let's try improve it.
