### ISSUE TITLE
[BUG]: Compare Two Models - Notebook code run error

### ISSUE THREAD

**Issue by ngraham76** [DARPA-ASKEM/terarium#3867]
**Describe the bug**
When working with the **Compare Models** operator drill down - notebook, clicking `Run` after generating some code with AI produces the following error message:

![image](https://github.com/DARPA-ASKEM/terarium/assets/141876103/4070c481-a35e-42c7-9040-d23e80bdcdd6)
![image](https://github.com/DARPA-ASKEM/terarium/assets/141876103/437cc4d0-2b51-4317-a058-f23caebdf096)

**Comment by Tom-Szendrey** [comment]
Being tracked via another ticket
