### ISSUE TITLE
[RESEARCH]: Using Vega/Vegalite to create charts as outlined in the design sketches

### ISSUE THREAD

**Issue by mwdchang** [DARPA-ASKEM/terarium#3888]
### Line chart for showing simulated trajectories across multiple sampled runs
- Show all trajectories
- Show statistical aggregate as a separate time series (e.g. mean of the sample-trajectories)

### Line chart showing calibration or optimization losses
- Show trajectory
- May want to consider capabilities to do different scales (linear, log)

### Area chart + xy-scatter for showing error distributions and individual error across samples against some ground truth.
- Show an area chart (estimate)
- Show the "randrop" plot of individual samples

**Comment by mwdchang** [comment]
Examples:

Technical example showing raincloud + boxplot of a dataset:
- https://gist.github.com/mwdchang/405758adac2e05fc285e50585518fe18

**Comment by YohannParis** [comment]
Overlapped by other issues.
