### ISSUE TITLE
Optimize Update: Final Design Details

### ISSUE THREAD

**Issue by Tom-Szendrey** [DARPA-ASKEM/terarium#3915]
This ticket is to keep track of the smaller details that are all left to the end.

- [x] Constraint, Policy, and Settings tooltips copy, replace TODO
- [x] Policy Intervention tooltip 
- [x] Final Copy for Constraints + Interventions + Optimization settings
- [x] css updates
- [x] #4147
- [ ] #4148
- [x] #4149

**Comment by Tom-Szendrey** [comment]
@ngraham76 can you please double check and see what I have missed in this.
This needs to be the difference from current implementation to final designs 

Things such as tooltips, wording, ect

**Comment by YohannParis** [comment]
All done
