### ISSUE TITLE
[BUG]: Model Edit Wizard interactability

### ISSUE THREAD

**Issue by Tom-Szendrey** [DARPA-ASKEM/terarium#3933]
Note: Interactable section is very limited (where the dots are at the top of the page)
https://app.staging.terarium.ai/projects/e7e67ae9-01d3-40dc-85ea-58494c8be5f0/workflow/b9c14767-2fbf-4256-92a0-8cfa0173bcd6?operator=21b4c403-ad65-4764-83d6-efe54925fcb4

![image](https://github.com/DARPA-ASKEM/terarium/assets/17088680/7293a207-452b-4e08-a1e9-94b92fff96b0)

**Comment by mwdchang** [comment]
Wizard is currently disabled, as this was meant to do model compositions (decapodes) and that is not on the agenda anymore.
