### ISSUE TITLE
[BUG]: Deleting the last Variable Chart removes ability to add a chart

### ISSUE THREAD

**Issue by bigglesandginger** [DARPA-ASKEM/terarium#3939]
**Describe the bug**
After Calibrating Pyciemss and getting a Loss Chart and Variable Chart, it is possible to add and remove Variable Charts, however, removing the last Variable Chart removes the ability to add a new chart

**To Reproduce**
1. Run through this test, and the last task asks you to add and remove charts: https://github.com/DARPA-ASKEM/terarium/blob/main/testing/manual/pyciemss-calibrate.md

**Expected behavior**
It would be nice to add the last Variable Chart back in, or if that is not possible (due to data stuff), then the last one should not be deletable (or at least present a warning)

**Screenshots**
2 Charts
![Screenshot 2024-06-20 at 2 08 52 PM](https://github.com/DARPA-ASKEM/terarium/assets/5182085/2e2613bd-c6a9-4dbc-bbcd-ed5fc93a3746)
After Deleting the first
![Screenshot 2024-06-20 at 2 09 38 PM](https://github.com/DARPA-ASKEM/terarium/assets/5182085/71d4f658-0355-49bc-bab1-45b826b98e55)
After Deleting the second
![Screenshot 2024-06-20 at 2 09 52 PM](https://github.com/DARPA-ASKEM/terarium/assets/5182085/de3d31f4-aaac-4dfb-896d-83b9eae67cfe)

**Comment by mwdchang** [comment]
Should be fixed.
