### ISSUE TITLE
[BUG]: Funman does not show false boxes in some cases

### ISSUE THREAD

**Issue by blanchco** [DARPA-ASKEM/terarium#3940]
Project: https://app.staging.terarium.ai/projects/441943bc-6777-4c0c-ba9c-b79d9057589f/workflow/538c0c0e-8787-46de-bb6c-d968b26905d0?operator=a28bac08-f223-44b3-8e7f-b042e1adb0da

**Describe the bug**
Despite the trajectory going outside the constraint, there are no false boxes, following Validate model config [test](https://github.com/DARPA-ASKEM/terarium/blob/main/testing/manual/validate-model-configuration.md) 
Step 5

<img width="1481" alt="Screenshot 2024-08-02 at 10 52 11 AM" src="https://github.com/user-attachments/assets/f846456b-caa5-496f-a4f6-8b539617b9ba">

Step 8
I believe that this scenario should be showing orange boxes since this is an impossible scenario:

<img width="1455" alt="Screenshot 2024-08-02 at 10 52 45 AM" src="https://github.com/user-attachments/assets/185694fd-4865-4ab2-8450-e246f28a94f0">

**Comment by YohannParis** [comment]
FUNMAN will be redesign as a service and the UX. Wait and see if still relevant.

**Comment by shawnyama** [comment]
I am not getting any false boxes at all. You can check out my outputs here https://app.staging.terarium.ai/projects/48b5ee70-418b-4939-b3d7-49db8a1346e1/workflow/681b6345-cdc1-4a89-91cc-27c15714b21c

**Comment by mwdchang** [comment]
I think we need to recheck our parsing logic. Here we can see two boxes, true | false relating to the project below, where only the true box showed up
```
https://app.staging.terarium.ai/projects/441943bc-6777-4c0c-ba9c-b79d9057589f/workflow/538c0c0e-8787-46de-bb6c-d968b26905d0?operator=a28bac08-f223-44b3-8e7f-b042e1adb0da
```

So the false box is there, but the timestep of which we use to grab the box-slice seemed to be quirky. 

<img width="713" alt="image" src="https://github.com/user-attachments/assets/0f12d578-9f8b-4881-9231-622af2d1557f">

**Comment by mwdchang** [comment]
Should be fixed in https://github.com/DARPA-ASKEM/terarium/pull/4718
