### ISSUE TITLE
[BUG]: Compare Models fails on the manual testing scenario

### ISSUE THREAD

**Issue by jryu01** [DARPA-ASKEM/terarium#3941]
- Scenario: https://github.com/DARPA-ASKEM/terarium/blob/main/testing/manual/compare-two-models.md
- Link to the project: https://app.staging.terarium.ai/projects/296b2313-ee16-4c0f-a081-c5458831e1a3/workflow/24d9ab8a-03e9-47b9-9219-0378d2b0e4bc?operator=aa201c99-584f-4e14-80bb-dbb9a01143a9

4-3 and 5-5 fails from the above test scenario. 
Also following error occurs during step 4

![Screenshot 2024-06-20 at 2 24 41 PM](https://github.com/DARPA-ASKEM/terarium/assets/3279838/7be10eeb-fa13-4ce1-b034-f39c68c153e7)

**Describe the issue**

**Comment by YohannParis** [comment]
GoLLM summary should returns.
