### ISSUE TITLE
[BUG]: SciML simulation does not work

### ISSUE THREAD

**Issue by YohannParis** [DARPA-ASKEM/terarium#3945]
- Scenario: [Simulate SciML](https://github.com/DARPA-ASKEM/terarium/blob/main/testing/manual/simulate-calibrate-model-configuration-w-sciml.md)
- Step:4.11
- Link to the project: https://app.staging.terarium.ai/projects/b0a98ccb-d186-449e-a703-e151dea3f18f/workflow/53e82f78-d902-4497-82cc-4f42367583f1

**Describe the issue**
![Screenshot 2024-06-20 at 15 27 50](https://github.com/DARPA-ASKEM/terarium/assets/636801/9a227674-3fe9-475c-8d40-7fda73bdb2af)

**Comment by mwdchang** [comment]
The model-configuration here is not well-formed, the rates are missing `expression_mathml` which are parsed and used  in sciml-service. @YohannParis @blanchco 

See: https://elasticsearch.staging.terarium.ai/tds_modelconfiguration_tera_2.0/_doc/9a1d2db9-49e7-45b2-a164-94a67de81737


```
          "rates": [
            {
              "target": "s",
              "expression": "-beta * s * i"
            },
            {
              "target": "i",
              "expression": "beta * s * i - gamma * i"
            },
            {
              "target": "r",
              "expression": "gamma * i"
            }
          ],
          "initials": [
            {
              "target": "s",
              "expression": "1000",
              "expression_mathml": "<cn>1000</cn>"
            },
            {
              "target": "i",
              "expression": "2",
              "expression_mathml": "<cn>2</cn>"
            },
            {
              "target": "r",
              "expression": "0",
              "expression_mathml": "<cn>0</cn>"
            }
          ]
```
