### ISSUE TITLE
[BUG]: significant digits go crazy after adding uncertainty to a parameter

### ISSUE THREAD

**Issue by dgauldie** [DARPA-ASKEM/terarium#3948]
- Scenario: model-configuration-input
- Step: 2a
- Link to the project:

**Describe the issue**
![image](https://github.com/DARPA-ASKEM/terarium/assets/4194153/7cd7d981-b8ea-4950-a3c4-eeccaa9e2a70)

After adding uncertainty to a parameter, the significant digits went crazy

**Comment by YohannParis** [comment]
@Tom-Szendrey and @blanchco is this related to the `tera-input-number` being removed?

**Comment by blanchco** [comment]
@YohannParis No this component has always used `tera-input`.  This is cause of floating point math in JS. I could set a fixed number of significant digits that are calculated when we add uncertainties.

**Comment by YohannParis** [comment]
> @YohannParis No this component has always used `tera-input`. This is cause of floating point math in JS. I could set a fixed number of significant digits that are calculated when we add uncertainties.

I will let @mwdchang make the call on this.
