### ISSUE TITLE
[BUG]: Funman timing out

### ISSUE THREAD

**Issue by blanchco** [DARPA-ASKEM/terarium#3949]
**Describe the bug**
Im getting an issue on 2 test scenarios where the funman request times out with a 504, following Validate model config [test](https://github.com/DARPA-ASKEM/terarium/blob/main/testing/manual/validate-model-configuration.md) 

Step 6:

![Image](https://github.com/DARPA-ASKEM/terarium/assets/33158416/276984d6-93b1-4170-a95a-469036854d0e)

Step 7:

![Image](https://github.com/DARPA-ASKEM/terarium/assets/33158416/c2b7b4b1-2db7-49d5-862b-12ade60f5262)

**Comment by bigglesandginger** [comment]
I have not seen any `Timeout` errors reported on any of the three environments over the last week.

**Comment by YohannParis** [comment]
Thanks @bigglesandginger
