### ISSUE TITLE
[BUG]: source does not change when dropdown changes in the model configuration

### ISSUE THREAD

**Issue by dgauldie** [DARPA-ASKEM/terarium#3950]
- Scenario: model-configuration-input
- Step: 3.4
- Link to the project:

**Describe the issue**
When switching between configurations, the value changes as expected, but the source does not. It only show the last value the user saved.

![image](https://github.com/DARPA-ASKEM/terarium/assets/4194153/e36b5f02-e16b-4b4e-b9bf-d1534d3e6b30)

![image](https://github.com/DARPA-ASKEM/terarium/assets/4194153/988700d8-7f7f-43d4-99cc-7403aad377e2)

**Comment by blanchco** [comment]
@YohannParis I cannot reproduce this, it may have been fixed when we moved from the legacy model config to the new one.  See below:

https://github.com/DARPA-ASKEM/terarium/assets/33158416/dc2b92af-d247-4f54-b940-c5ebf90e66d7
