### ISSUE TITLE
[BUG]: Ensemble Calibrate - Cannot Delete Mapping

### ISSUE THREAD

**Issue by liunelson** [DARPA-ASKEM/terarium#3954]
- Scenario: Ensemble Calibrate
- Step: Misc
- Link to the project: [link](https://app.staging.terarium.ai/projects/e98fb834-b49f-4211-9966-bf0d6e10c042/workflow/62f7c9f6-abf4-472f-b402-8eae642913a9?operator=a8658d0e-ced4-497a-ad25-22ffcff37597)

**Describe the issue**
I cannot delete a mapping after adding it. In Ensemble Simulate, there is a `X` that I can use to make a deletion.

**Comment by mwdchang** [comment]
Deleting this, since ensemble operators are being refreshed
