### ISSUE TITLE
[BUG]: Cannot add searched for model to project

### ISSUE THREAD

**Issue by bigglesandginger** [DARPA-ASKEM/terarium#4002]
**Describe the bug**
Adding a searched for model to a project causes a currentProjectAsset is null error

**To Reproduce**
1. Create a new project
2. Go to Explorer
3. Search for a model (for instance "SIR Model")
4. Choose a model and click the plus button
5. Select the newly created project and bam error time

**Expected behavior**
The model is added to the project

**Screenshots**
![Screenshot 2024-06-27 at 2 12 54 PM](https://github.com/DARPA-ASKEM/terarium/assets/5182085/996f4d05-44c2-4c58-b7f7-452f3ccf0fbc)

**Additional context**

**Comment by dgauldie** [comment]
We will retest once the DB wipe and reingest is complete
