### ISSUE TITLE
[BUG]: Stats on Dataset page should not be that long

### ISSUE THREAD

**Issue by YohannParis** [DARPA-ASKEM/terarium#4004]
- Scenario: https://github.com/DARPA-ASKEM/terarium/blob/main/testing/manual/dataset-enrichment.md
- Step: 2.3
- Link to the project: https://app.staging.terarium.ai/projects/b0a98ccb-d186-449e-a703-e151dea3f18f/dataset/0d1f7ef4-eebd-4bb4-97e5-9ca7592f1dae

**Describe the issue**
The numbers in the stats columns are ridiculously to long

<img width="361" alt="Screenshot 2024-06-27 at 15 07 34" src="https://github.com/DARPA-ASKEM/terarium/assets/636801/c1ec9e80-aac1-42db-b7c5-851fbb463905">

**Comment by dgauldie** [comment]
we should keep things at 1 digit
