### ISSUE TITLE
[BUG]: enrichment modal should use Document name and not file name

### ISSUE THREAD

**Issue by YohannParis** [DARPA-ASKEM/terarium#4005]
- Scenario: [dataset-enrichment](https://github.com/DARPA-ASKEM/terarium/blob/main/testing/manual/dataset-enrichment.md)
- Step: 3.4
- Link to the project: https://app.staging.terarium.ai/projects/b0a98ccb-d186-449e-a703-e151dea3f18f/dataset/0d1f7ef4-eebd-4bb4-97e5-9ca7592f1dae

**Describe the issue**
<img width="748" alt="Screenshot 2024-06-27 at 15 06 14" src="https://github.com/DARPA-ASKEM/terarium/assets/636801/fd217b1a-f3c3-4177-9871-502c66e8e2ca">

**Comment by dgauldie** [comment]
the issue here is that we can't rename documents... We should be able to.

**Comment by YohannParis** [comment]
> the issue here is that we can't rename documents... We should be able to.

No, the issue here, is that we display the names of the files, not the name of the asset.

**Comment by YohannParis** [comment]
This is a non issue
