### ISSUE TITLE
[BUG]: notebook updates the model config name when updating parameters

### ISSUE THREAD

**Issue by blanchco** [DARPA-ASKEM/terarium#4007]
- Scenario: Model config test notebook
- Step: 3.7
- Link to the project: https://app.staging.terarium.ai/projects/28f0c230-b197-46dd-ba18-fd546d926ca6/workflow/56a34d4e-3156-4940-bcd4-b03cdbce6e6b?operator=a2afacd4-ca39-408d-8e53-6896ec25f3be

**Describe the issue**
When updating a variable R0 to 0.2 the model configuration's name is changed as well

https://github.com/DARPA-ASKEM/terarium/assets/33158416/56d893eb-5794-4e10-8283-e0c9a789666a

**Comment by dgauldie** [comment]
The name is supposed to be changed. However, the output name did NOT change and the left side panel is missing the new configuration.
