### ISSUE TITLE
[BUG]: The Overview text never loads (despite waiting >10 seconds)

### ISSUE THREAD

**Issue by liunelson** [DARPA-ASKEM/terarium#4012]
- Scenario: Compare Models
- Step: 4.3
- Link to the project: https://app.staging.terarium.ai/projects/5352e859-0832-4ad2-9cd8-7a77d4b152ca/workflow/d7c8c2bd-babb-41a6-9c0e-f8e12c74e4e4?operator=ccb70f8f-609a-4445-bc33-938b6f500d9c

**Describe the issue**
The Overview section of the Compare Models operator should be populated with some text but that never happens, even after waiting for >10 seconds.

**Comment by dgauldie** [comment]
duplicate
