### ISSUE TITLE
[BUG]: Diagrams in Compare Models are not interactive

### ISSUE THREAD

**Issue by liunelson** [DARPA-ASKEM/terarium#4013]
- Scenario: Compare Models
- Step: 4.4
- Link to the project: https://app.staging.terarium.ai/projects/5352e859-0832-4ad2-9cd8-7a77d4b152ca/workflow/d7c8c2bd-babb-41a6-9c0e-f8e12c74e4e4?operator=ccb70f8f-609a-4445-bc33-938b6f500d9c

**Describe the issue**
The model diagrams are not interactive (cannot zoom, pan, etc.). This may just be a missing feature, not a bug.

**Comment by dgauldie** [comment]
we will replace with new graphs later on
