### ISSUE TITLE
[BUG]: 'Add to project' list is not scalable

### ISSUE THREAD

**Issue by pascaleproulx** [DARPA-ASKEM/terarium#4028]
**Describe the bug**
When copying an asset from one project to another, the 'Add to project' list is crop off (too long) and not clear how it is sorted.

**Screenshots**
![image](https://github.com/DARPA-ASKEM/terarium/assets/42645294/a208f5ef-679e-4d60-8ca4-93414e8420f9)

**Comment by mwdchang** [comment]
partially solved via addition of scrollbar
