### ISSUE TITLE
[BUG]: Stratified model configuration - add uncertainty 

### ISSUE THREAD

**Issue by Tom-Szendrey** [DARPA-ASKEM/terarium#4048]
- Scenario: https://github.com/DARPA-ASKEM/terarium/blob/main/testing/manual/model-configuration-input.md
- Step: 4
- Link to the project: https://app.staging.terarium.ai/projects/3215b073-4869-4b1d-8cfb-1c2f961b1108/workflow/cb0f1edc-0b60-42a3-9243-8364fe7fabdd?operator=a1460315-b8f0-403c-ae54-8d89c72f522b

**Describe the issue**
When utilizing the add uncertainty I do not see any selection boxes for parameters I also do not see any changes made to parameters.

**Comment by blanchco** [comment]
@YohannParis @Tom-Szendrey 
Checkboxes will only appear for _Constant_ values not uniform ones.  Once I switched the value to constant the checkbox appears and the uncertainty is applied.
