### ISSUE TITLE
[BUG]: When saving a new model in Edit Model, the new name does not propagate to the output selector and output node

### ISSUE THREAD

**Issue by liunelson** [DARPA-ASKEM/terarium#4053]
- Scenario: Edit model
- Step: 4.3
- Link to the project: https://app.staging.terarium.ai/projects/7a3989de-68ba-4bbb-a9b2-f552fa1a7079/workflow/74a055f5-375a-4bb8-9230-1df17cbbae3a?operator=af4d4e1b-23a4-4550-ae62-870df3b155a6

**Describe the issue**
When I use "save as a new model", I give the model a new name. It does appear under this new name in the Resources panel. However, the output selector in the Edit Model operator and its output port still use the UUID (`1720...`). I would have expected this UUID name to be replaced by the name I gave during the saving.
![Screenshot 2024-07-04 at 5 39 33 PM](https://github.com/DARPA-ASKEM/terarium/assets/1030720/59f22ce3-fd80-42d2-b81a-f8414102d386)

**Comment by YohannParis** [comment]
Solve in another ticket
