### ISSUE TITLE
[BUG]: Simulate with SciML fails with errors

### ISSUE THREAD

**Issue by jryu01** [DARPA-ASKEM/terarium#4055]
- Scenario: https://github.com/DARPA-ASKEM/terarium/blob/main/testing/manual/simulate-calibrate-model-configuration-w-sciml.md
- Step: 4-15 
- Link to the project: https://app.staging.terarium.ai/projects/1b61f498-ef6b-4465-a044-990c81f8b899/workflow/a265dad2-fcea-4bc5-97dd-e22f9875d17e?operator=daec0d1a-687c-4ea1-b97f-19c8d8f87cff

**Describe the issue**

Manual test failed at step 4-15
![Screenshot 2024-07-04 at 5 45 26 PM](https://github.com/DARPA-ASKEM/terarium/assets/3279838/bccc0f42-e329-4f17-8efe-37def31a57ff)
![Screenshot 2024-07-04 at 5 45 18 PM](https://github.com/DARPA-ASKEM/terarium/assets/3279838/c2bbfd0b-d79c-42dd-92ba-77c1d0d4da6e)

**Comment by YohannParis** [comment]
SciML is not supported anymore
