### ISSUE TITLE
[BUG]: Calibrate with SciMl fails with errors

### ISSUE THREAD

**Issue by jryu01** [DARPA-ASKEM/terarium#4056]
- Scenario: https://github.com/DARPA-ASKEM/terarium/blob/main/testing/manual/simulate-calibrate-model-configuration-w-sciml.md
- Step: 5-8
- Link to the project: https://app.staging.terarium.ai/projects/1b61f498-ef6b-4465-a044-990c81f8b899/workflow/a265dad2-fcea-4bc5-97dd-e22f9875d17e?operator=ba2f4eac-697e-48b3-9ab4-e9663683f7ba

**Describe the issue**
Calibrate with SciMl fails with errors
![Screenshot 2024-07-04 at 5 51 27 PM](https://github.com/DARPA-ASKEM/terarium/assets/3279838/b124d775-e7a5-4293-8a74-4de844f8bdb0)
![Screenshot 2024-07-04 at 5 51 10 PM](https://github.com/DARPA-ASKEM/terarium/assets/3279838/43f7285b-14f7-4a58-a56f-2f7ad165160f)

**Comment by YohannParis** [comment]
SciML is not supported anymore
