### ISSUE TITLE
[BUG]: Edit Model with LLM code assistant gives error

### ISSUE THREAD

**Issue by liunelson** [DARPA-ASKEM/terarium#4057]
- Scenario: Edit model
- Step: 8.3
- Link to the project: https://app.staging.terarium.ai/projects/7a3989de-68ba-4bbb-a9b2-f552fa1a7079/workflow/74a055f5-375a-4bb8-9230-1df17cbbae3a?operator=efbe93b8-87d8-491a-ae21-6c1e97449e56

**Describe the issue**
I ask the LLM agent to generate code with the query "Add a new transition from S to V with the name vax and a rate constant named v". The resulting code looks right. However, when I click Run, it gave this error and nothing happened. 
![Screenshot 2024-07-04 at 5 42 47 PM](https://github.com/DARPA-ASKEM/terarium/assets/1030720/d025dd90-89ff-4a75-a646-4de3143e24c2)

**Comment by Tom-Szendrey** [comment]
Without more details I cannot look into this. From my POV this looks to be working completely find (see screenshot below)

I am not sure what code you tried to run but I am not running into any issues
There is also a chance beaker itself was running into issues as it was crashing during our testing a few weeks ago

![image](https://github.com/user-attachments/assets/10bddfbe-af2d-43eb-a87d-442ece268fdd)
