### ISSUE TITLE
[BUG]: Ensemble Calibrate - Unable to add susceptible state

### ISSUE THREAD

**Issue by asylves1** [DARPA-ASKEM/terarium#4058]
- Scenario: Ensemble Calibrate
- Step: 3.7
- Link to the project: https://app.staging.terarium.ai/projects/543cd6df-ab9d-4010-b50c-65060b25d238/workflow/edfa0da3-0dbf-4235-aebb-e833ff3e1a95

After clicking the `Add mapping`  to add a second variable it clears the first one
![image](https://github.com/DARPA-ASKEM/terarium/assets/95376249/3dddc28d-dc31-40ca-b1ba-f662c5c2fd53)

This error appears if you click run
![image](https://github.com/DARPA-ASKEM/terarium/assets/95376249/69ccc42e-b7c6-440f-b36a-9d4326998a35)

**Describe the issue**

**Comment by Tom-Szendrey** [comment]
This is intended when you have the exact same mapping name.
I am pretty sure this is just a misunderstanding in the design:
![image](https://github.com/user-attachments/assets/3d152bc9-4e26-4741-9be2-c32734a541a8)
