### ISSUE TITLE
[BUG]: Compare two models Overview section does not render with markdown formatting

### ISSUE THREAD

**Issue by jamiewaese-uncharted** [DARPA-ASKEM/terarium#4059]
- Scenario: Compare two models
- Step: 4. 
- Link to the project: https://app.staging.terarium.ai/projects/19986f9c-cbec-4af8-ba35-ecb3df9d972c/workflow/b1633429-a474-4434-ab27-28d7089f11b3?operator=c3fbb077-d299-4c71-a003-66773596803f

**Describe the issue**
Pipe two models into a Compare operator. Open the drilldown. The summary section gets generated properly, but we don't render it with appropriate formatting.
![image](https://github.com/DARPA-ASKEM/terarium/assets/120480244/b057412e-8b30-4eba-8c31-4ea40d7ce781)

**Comment by mwdchang** [comment]
Should be fixed in https://github.com/DARPA-ASKEM/terarium/pull/4509
