### ISSUE TITLE
[BUG]: Boxplot rendering doesn't seem to make sense.

### ISSUE THREAD

**Issue by mwdchang** [DARPA-ASKEM/terarium#4088]
The box-plot component we have doesn't seem to render the statistics correctly.  
Here in the images below
- the [min, max] range is between [0, 0.81], 
- it is marking the point at 0.24

`0.24` should be about a little bit beyond the quarter mark of the entire range, however as seen in the image 0.24 is marked much closer to 0.

Old version: 

![image](https://github.com/DARPA-ASKEM/terarium/assets/1220927/d375a5b7-0908-42ef-9ba6-2c25efabebbf)

New version:

![image](https://github.com/DARPA-ASKEM/terarium/assets/1220927/23e53e24-1bab-464d-a7f0-cacb921491d1)

The payload that generated this is provided here:
```
{
    "num_null_entries": 0,
    "type": "numeric",
    "min": 0,
    "max": 0.810127005400101,
    "mean": 0.24161029649398671,
    "std": 0.2956143291379967,
    "quantile_25": 0.0014541465753126926,
    "quantile_50": 0.05539503186026315,
    "quantile_75": 0.510723642174624
}
```

It appears that we are using "mean" as if it is "medium". We should clarify exactly which metric we want to show, and adjust accordingly, either:
- add medium, or
- draw mean where mean is suppose to be

**Comment by pascaleproulx** [comment]
This will be removed so closing
