### ISSUE TITLE
[FEAT]: Annotate charts on the optimized interventions

### ISSUE THREAD

**Issue by YohannParis** [DARPA-ASKEM/terarium#4206]
Need to annotate the chart both the original and the optimized intervention and label these dashed lines.

<img width="710" alt="Screenshot 2024-07-22 at 11 11 50" src="https://github.com/user-attachments/assets/242e5f09-89d7-45ce-9c24-c9dd22cb2207">

**Comment by blanchco** [comment]
@YohannParis This should be done as of the intervention charts #4199 PR
