### ISSUE TITLE
[BUG]: QoI bar chart colours

### ISSUE THREAD

**Issue by liunelson** [DARPA-ASKEM/terarium#4220]
The Optimize operator has a horizontal bar chart that shows the distribution of values of the "quantity of interest" or "success criterion target variable", wherein the goal is to keep these values below/above some given threshold.
For example, the target variable is "H", the number of hospitalized persons.

Passing these values to a histogram generator like `numpy.histogram` would yield a list of bar widths and bar y-coordinates. Usually, the number of bars ~ square root of the number of values.

Also compute the alpha-percentile of this distribution by passing the same values to a function like `numpy.percentile(values, q = alpha)` where `alpha` is the user-given success percentage (e.g. `0.95`).

* Colour the horizontal bars whose upper y-coordinates are below the alpha-percentile to be `green` and label them as "Best <alpha*100>%"
* Colour those whose lower y-coordinates are above the alpha-percentile to be `yellow/orange` and label them as "Pass"

* PyCIEMSS returns a value called `risk`; draw it as a horizontal line coloured `yellow/orange` and label it as "Average of worst `<100 - alpha*100>`"
* Draw the user-given threshold as another horizontal line coloured `dark orange or red` and label it as "Threshold".
* Colour those whose lower y-coordinates are above the threshold to be `dark orange or red` and label them as "Fail"

In a successful optimization, the "average of worst <...>" is always less than the threshold, otherwise, the optimization has failed.

*Currently, the horizontal bars are coloured based on whether they above/below the threshold - this is incorrect, they should be coloured relative to the alpha-percentile _and_ the threshold*

![Image](https://github.com/user-attachments/assets/ffe4bcce-3790-45c3-a577-21df0c7a74b7)

**Comment by blanchco** [comment]
thanks @liunelson, these instructions are great!  Ill get this in ASAP.
