### ISSUE TITLE
[TASK]: Investigate Fuman model-configuration

### ISSUE THREAD

**Issue by mwdchang** [DARPA-ASKEM/terarium#4227]
Find out what is going on with Funman producing TA3 consumable model-configurations, and plan out next steps.
We need to
- See if we can integrate it into Terarium
- Test funman works
- Test TA3 can use the funman output
- Sync up and redeploy funman taskrunner

**Comment by mwdchang** [comment]
What remains for this task is to:
- Parse out the resulting AMR from funman output
- Take the AMR and convert it to our own model-configuration object
- Save the model configuration (the id) into the output

The AMR should be found under the field: `contracted_model`

Note it seems like a configuration will be created regardless of whether we have valid results or not, that is, even if all boxes are false there is a contracted_model AMR. Let's not worry about this for now.

**Comment by shawnyama** [comment]
Yohann's instructions:

Task Description:

Update the ValidateModelConfigHandler.java file to perform the following tasks:

- Create a Model instance using the AMR response provided by FUNMAN.
- Utilize the service/modelConfiguration/modelConfigurationFromAMR method to generate a ModelConfiguration from the created Model.
- Ensure the generated ModelConfiguration is included as an output of the operator.
