### ISSUE TITLE
Chart VEGA-lite AI assisted research

### ISSUE THREAD

**Issue by YohannParis** [DARPA-ASKEM/terarium#4297]
The user often wants to add annotations to charts created in simulate, calibrate, optimize and ensemble... The most common annotations should be enabled directly in these operators. See sketch below. This should be available in the output settings section/panel of all the TA3 operators.

![Image](https://github.com/user-attachments/assets/ad6327d6-dc41-4b6c-9c11-1fe8635c7162)

**Comment by mwdchang** [comment]
Engineering wise, one thing to think about is how we would track these AI/LLM modifications.  If the LLM were to generate a new spec, we would prefer to not store the spec as part of the workflow to avoid the workflow object getting too large to handle.
