### ISSUE TITLE
Project page

### ISSUE THREAD

**Issue by dgauldie** [DARPA-ASKEM/TERArium#43]
- [ ] Metadata , and stats (numbers of datasets, models, etc
- [ ] Recent activities
- [ ] Overview context ~ Description/abstract
- [ ] Contributions/Sharing settings
- [ ] #44
- [x] #45
- [x] #46

![Image](https://user-images.githubusercontent.com/636801/193100407-29912a12-7a43-4e4e-880e-b586aa4095cf.png)

**Comment by YohannParis** [comment]
@dgauldie should we close this issue, as most of those features are not needed as of now.
