### ISSUE TITLE
[BUG]: Parameter matrix generated by stratifying certain model transitions are wrong

### ISSUE THREAD

**Issue by liunelson** [DARPA-ASKEM/terarium#4305]
We have this SEIRDH model where the infection-exposure process is `S -> E` controlled by `I`
```
\frac{d S}{d t} = - \beta S I
\frac{d E}{d t} = \beta S I - r_{EI} E
\frac{d I}{d t} = r_{EI} E - r_{IR} p_{IR} I - r_{IH} p_{IH} I
\frac{d H}{d t} = r_{IH} p_{IH} I - r_{HR} p_{HR} H - r_{HD} p_{HD} H
\frac{d R}{d t} = r_{IR} p_{IR} I + r_{HR} p_{HR} H
\frac{d D}{d t} = r_{HD} p_{HD} H
```
[SEIRHD_base.json](https://github.com/user-attachments/files/16418970/SEIRHD_base.json)

When this model is stratified, we get this strange 2 x 4 transition matrix between `S` and `E`, wherein the `S_u, S_v` states appear on both the rows and columns. This doesn't sense.
* The transitions `t0_v_u` and `t0_u_v` are misplaced since they do not have `S_u, S_v` as output states
* If the rows are input states and the columns are output states, then `t0_u_u` and `t0_u_v` should be grouped; similarly for `t0_v_v, t0_v_u` (second index is for vax status of the `I`)
* This is suboptimal since it'd have two entries per matrix element
* Ideally, the column would use "hierarchical indexing" as in Pandas (https://pandas.pydata.org/docs/user_guide/advanced.html) where the first level is the output state combinations and the second level is the controller state combinations

![Image](https://github.com/user-attachments/assets/518c26db-b933-4b41-ac86-d258f514456a)
![Image](https://github.com/user-attachments/assets/e2c7f110-7df9-40bb-9a9b-c3aca29ef44a)
![Image](https://github.com/user-attachments/assets/dd0caa8e-01f5-4021-bd8c-2430277b5f09)

This bug changes when I toggle off the "Create new transitions between strata":
* the transition matrix becomes 2 x 2 and the `t0_u_u, t0_v_v` transitions are no longer shown 👎 

![Image](https://github.com/user-attachments/assets/c37cec6b-2619-417a-b0e5-3d725b203a38)
![Image](https://github.com/user-attachments/assets/0efe151b-74bd-43a6-854f-337ac5a71d36)

**Comment by liunelson** [comment]
This is probably a bug that @mwdchang is most familiar?

**Comment by shawnyama** [comment]
After digging around I found that there are two of the same templates generated by MIRA. These are the templates in the mmt: 
[miratemplates.json](https://github.com/user-attachments/files/16476240/miratemplates.json)

Here are the ones that are the same in the above file
![image](https://github.com/user-attachments/assets/1f138c91-7521-4c52-95a5-bcaca7c447d3)

Looking at the expanded view of the model also shows that those connections do exist

**Comment by shawnyama** [comment]
[sierdh.json](https://github.com/user-attachments/files/16511610/sierdh.json)
[sierdh_strat.json](https://github.com/user-attachments/files/16511614/sierdh_strat.json)

**Comment by mwdchang** [comment]
The duplicated template names aren't handled in our collapseTemplates function, but more than that the resulting AMR has more than one expressions point at a singular target. I filed a ticket with MIRA:

https://github.com/gyorilab/mira/issues/348

**Comment by mwdchang** [comment]
This seemed okay after the MIRA fix.
