### ISSUE TITLE
[TASK]: Settle on "Save as" behaviour for drilldown header menu

### ISSUE THREAD

**Issue by shawnyama** [DARPA-ASKEM/terarium#4320]
### Problem
- Save as buttons injected into the `tera-drilldown` ellipsis menu have inconsistent behaviour
![image](https://github.com/user-attachments/assets/5e5a2a59-e47d-41bf-a58c-96b1eec1cf03)
- In all cases (except for saving a model config) it adds an asset to the project that the user would name in a modal
- Once the save is done we need to decide if we want to either:
	- Create a new output based on what was just saved
	- OR
	- Just update current output label since the name is the only difference
		- *Currently (in some cases) we update the output label using `update-output-port` which may complicate things downstream*
##### Edit model, Stratify
- Creates a new model and adds to project
- No new output created
- Output label doesn't change
##### Model from equations
- Creates a new model
- No new output is created
- Current output label is updated with `update-output-port`
##### Transform Dataset
- Save as creates a new output and project asset
- Note that the save as here is not in the drilldown ellipsis menu but in the main page
##### Ensemble calibrate
- Adds dataset to project
- No new output created
##### Funman 
- Save as new model configurations button does nothing
##### Optimize
- Creates new dataset and adds it to project
- No new output created
- Another button "Save as new model configuration" just saves a new one in the db
### Where else is `update-output-port` used
- In `tera-intervention-policy-drilldown` the output label updates once the policy name is changed - I think this should be applied once the save button is clicked (new policy will be generated)
- In `tera-code-asset-wrapper` the entire output looks like its updated. Not too familiar with this...looks like an exception
- `tera-stratify-mira` and `tera-model-edit` pass `update-output-port` to `tera-drilldown` for no reason

**Comment by YohannParis** [comment]
The prefered behaviour for ALL of them is:
1. Creates a new Asset and adds to project if it's an asset that is in the ressource panel
2. No new output created
3. Current output label is updated with update-output-port
