### ISSUE TITLE
[BUG]: Can Save new model-configuration even without changes

### ISSUE THREAD

**Issue by YohannParis** [DARPA-ASKEM/terarium#4357]
- Scenario: 
- Step: 
- Link to the project: https://app.staging.terarium.ai/projects/24e5d75b-53c5-4190-b5cb-c5a8f92d1baf/workflow/25914819-4e21-4dd7-b6a7-820c9c69d68c?operator=03c76166-eead-4c2b-97d7-1e80d8d7063a

**Describe the issue**
The Save button should be disabled when no edit has been made to the operator.

**Comment by brittanykondo** [comment]
Closing because this will be fixed by the new designs
