### ISSUE TITLE
Simulation and Calibration should same output section as Optimize

### ISSUE THREAD

**Issue by Tom-Szendrey** [DARPA-ASKEM/terarium#4371]
![Image](https://github.com/user-attachments/assets/e67a24dc-95a2-4c94-8e12-2147961a9c82)

![Image](https://github.com/user-attachments/assets/40ef5319-a463-4b6c-b41b-75e2a197ccc9)

**Comment by Tom-Szendrey** [comment]
Show mean for both simulation plot and interventions

**Comment by Tom-Szendrey** [comment]
https://github.com/DARPA-ASKEM/terarium/pull/4457#issuecomment-2291477052

Some of the design elements are problematic, not really up-to-date with the latest thinking, or are some what contradictory. For example we'd need to think about how these settings are going to work with reporting features
Likewise, the "chartConfig" is getting rejigged to take into consideration annotations, this will impact how we would pass things back and forth between the operator drilldown and the settings panel as they wouldn't be just variable string arrays
It would still be good to assess the situation in a more systematic manner. It may be nice, if possible, for each operator to provide a generator function of its output-settings, and how the settings should be displayed.

**Comment by Tom-Szendrey** [comment]
Things to discuss:
1) Problematic design elements such as some sections of the form being filled in prior to run and others being filled in after.
- Do we want to generate summary (Before)
- What variables and charts do we want to look at? (After)

2) Each drilldown has different charts. Does this design allow for that flexibility? 
- Interventions
- Simulations allowing one selection
- Simulations allowing multiple selections
- Success Criteria 
- Calibrated Parameter charts.

3) What designs for the reporting system and how will this impact our choices here?

**Comment by dgauldie** [comment]
duplicate
