### ISSUE TITLE
[BUG]: Missing equations extracted from SIR document

### ISSUE THREAD

**Issue by brittanykondo** [DARPA-ASKEM/terarium#4392]
- Scenario:
- Step:
- Link to the project: https://app.staging.terarium.ai/projects/61bcb46d-b7d1-4881-a7c8-c105be525960/workflow/701d870a-5129-4d98-b50a-89a63d925f8e?operator=a575dbd9-0955-4dff-a32a-3b2608c44ff4

After uploading SIR.pdf, I see the following 4 equations extracted. Equations for S and I are missing.
<img width="1477" alt="Screenshot 2024-08-08 at 1 08 46 PM" src="https://github.com/user-attachments/assets/6f379b61-ba36-4d00-b8ab-23f982c0d557">

**Comment by YohannParis** [comment]
Deal with Nougat in the future
