### ISSUE TITLE
[BUG]: funman inner chart scale issue

### ISSUE THREAD

**Issue by Tom-Szendrey** [DARPA-ASKEM/terarium#4393]
https://github.com/DARPA-ASKEM/terarium/blob/main/testing/manual/validate-model-configuration.md

Step 5.8 either I do not understand or the axis should be [0.4, 0.8] and not what look to be rounding errors?

https://app.staging.terarium.ai/projects/f8501b9d-31ab-4551-bdef-c8e8cd3c7491/workflow/dc173da2-c463-43e3-82f1-d5ac2f472bd6?operator=226b8502-914a-4e16-9c9b-8cf6111ff731

<img width="584" alt="image" src="https://github.com/user-attachments/assets/d3dd5570-9b8b-44f2-8a46-bd0b073c85ae">

**Comment by YohannParis** [comment]
Dealt with redeisgn of the charts
