### ISSUE TITLE
[BUG]: Saving Model from Model Edit is super difficult

### ISSUE THREAD

**Issue by bigglesandginger** [DARPA-ASKEM/terarium#4395]
- Scenario: Model edit
- Step: 5
- Link to the project: https://app.staging.terarium.ai/projects/c5a3cb4b-7a37-4037-9f7b-f893cf206e6a/workflow/947fe5c6-a918-4d7c-88c5-c50d0e7e7bc7?operator=be85ed07-9058-4a05-905f-94466b49f6b7

Tasks asks the user to save the model, save option is well hidden, might as well not exist.

**Comment by YohannParis** [comment]
Dealt with some UX improvments
