### ISSUE TITLE
[BUG]: Clicking RESET in Wizard mode does not visually change

### ISSUE THREAD

**Issue by bigglesandginger** [DARPA-ASKEM/terarium#4396]
- Scenario: Model Edit
- Step: 7.2
- Link to the project: https://app.staging.terarium.ai/projects/c5a3cb4b-7a37-4037-9f7b-f893cf206e6a/workflow/947fe5c6-a918-4d7c-88c5-c50d0e7e7bc7?operator=be85ed07-9058-4a05-905f-94466b49f6b7

After following the steps through to 7.1, 7.2 asks one to press RESET, if one WIZARD the reset does not visually seem to happen, if on NOTEBOOK it does

**Comment by YohannParis** [comment]
Remove the model-edit test
