### ISSUE TITLE
[BUG]: Everything is wrong with GoLLM configurations extractions

### ISSUE THREAD

**Issue by pascaleproulx** [DARPA-ASKEM/terarium#4398]
- Scenario: Extract configurations from document and dataset
- Step: Results
- Link to the project: https://app.staging.terarium.ai/projects/59d1af73-e373-42da-9e88-ac020a39cc1f/workflow/05b28cbd-ad29-4355-9010-5e21bcd795b2

**Describe the issue**
~**Issue 1: Need spinner**  low~ #4427

~**Issue 2: Selecting a configuration always requires a confirmation.** medium~ #4228 

~**Issue 3: Extracted configuration with an incomplete set of values should not keep values from default configuration, only show the values extracted.** HIGHEST~ #4430 

~**Issue 4: Extracted values??** High~ #4431

~**Issue 5: Configuration from dataset** Medium~ #4432

~**Issue 6: Source** medium~ #4433

**Comment by YohannParis** [comment]
Break down in multiple GitHub issue

**Comment by YohannParis** [comment]
Done!
