### ISSUE TITLE
[TASK]: Add download option to document asset

### ISSUE THREAD

**Issue by shawnyama** [DARPA-ASKEM/terarium#4410]
**Describe the task**
There isn't a download option for the document asset. Even thought you can download it by going to the PDF viewer I think the option should be here as well for consistency.

**Screenshots**

<img width="447" alt="Screenshot 2024-08-08 at 5 07 09 PM" src="https://github.com/user-attachments/assets/961d5999-d204-4fa8-8d90-0fdabac16d80">

**Comment by YohannParis** [comment]
@dvince2 haven't you added that or I misrember?

**Comment by dvince2** [comment]
closing as dupilcate
