### ISSUE TITLE
[BUG]: Extracted values

### ISSUE THREAD

**Issue by YohannParis** [DARPA-ASKEM/terarium#4431]
**Describe the bug**
We do not see any values from the document for beta, it is just the default config value.
In the document, we have the following values for beta:
Basic social distancing (initial_outbreak): 0.0057
Incomplete lockdown (partial_lockdown): 0.005

Link to project with the bug:  https://app.staging.terarium.ai/projects/59d1af73-e373-42da-9e88-ac020a39cc1f/workflow/05b28cbd-ad29-4355-9010-5e21bcd795b2

![image](https://github.com/user-attachments/assets/87bde76e-6f90-4c99-b850-b7611f39f6c0)

**Comment by dgauldie** [comment]
unable to reproduce locally.

this is what I get:


![Image](https://github.com/user-attachments/assets/4ee69d7d-9300-41af-82cd-e1639a702c0a)
