### ISSUE TITLE
[TASK]: Investigate showing (popping up) larger version of vegalite chart

### ISSUE THREAD

**Issue by mwdchang** [DARPA-ASKEM/terarium#4452]
Pascale was asking if it is possible to "pop up" a larger version of the Vegalite chart, similar to how model-comparison has this "preview" kind of things with PrimeVue images (https://primevue.org/image/)

```
          <li v-for="(image, index) in structuralComparisons" :key="index">
            <label>Comparison {{ index + 1 }}</label>
            <Image id="img" :src="image" :alt="`Structural comparison ${index + 1}`" preview />
          </li>
```

Not a priority I think, because Vegalite itself can already be detatched into Vegalite-editor in a different window/tab ... but might be good to spend maybe half a day looking at what options are there.

**Comment by jryu01** [comment]
I think we can build something similar to `<Image preview..` into VegaChart component
