### ISSUE TITLE
[BUG]: Simulate operator (probably also Calibrate, Optimize, etc.) fails if the values in the configuration are integers and not floats

### ISSUE THREAD

**Issue by liunelson** [DARPA-ASKEM/terarium#4468]
**Describe the bug**
I wanted to run a model that I created from equations. However, I found that the Simulate operator fails if I do not make sure that the initial condition values (`S(t = 0), I(t = 0), ...`) are _floats_ and not just _integers_. This is particularly relevant in models with absolute population counts as compartments, as opposed to relative population counts (where those values are always `<= 1`).

**To Reproduce**
1. Load any model that is known to be working
2. Configure it using the "Configure Model" operator
3. Change the values of the initial condition to integers by removing any  trailing zero or decimals
4. Plug this configuration into a Simulate operator
5. Click "Run" and see the PyCIEMSS error message 

**Expected behavior**
If the operators only accept floats and not integers as initial condition values, we need to do that type validation/casting somewhere. This could either be in `pyciemss`, `pyciemss-service`, or ?

Since those initial condition value fields can be math expressions (like `S(t = 0) = S_0`), they are stored as strings in the AMR JSON. So, `"1" -> "1.0"`?

**Screenshots**

![image](https://github.com/user-attachments/assets/da1604bc-9766-4a70-ba6c-1e1265a503ea)
![image](https://github.com/user-attachments/assets/bd8e1449-71d7-48b0-9e6f-8c1c9ae54d6a)

**Comment by liunelson** [comment]
Here are the two models: one with integers and the other with floats as initial condition "expressions"
[SIR (floats).json](https://github.com/user-attachments/files/16628004/SIR.floats.json)
[SIR (integers).json](https://github.com/user-attachments/files/16628005/SIR.integers.json)

**Comment by liunelson** [comment]
Sam at PyCIEMSS says they'll address this issue.

**Comment by Tom-Szendrey** [comment]
@YohannParis @liunelson 
Is this meant as a tracking issue or something for me to address?
The most up to date comment is that Sam is looking into this

We also have a shim that could be catching this within pyciemss-service that Dan has created. Did you want me to look into that?
