### ISSUE TITLE
[BUG]: asset rename isn't updated downstream

### ISSUE THREAD

**Issue by shawnyama** [DARPA-ASKEM/terarium#4483]
**Describe the bug**
- asset rename isn't updated downstream

**To Reproduce**
- Drop in a model and attach it another operator
- Rename the model
- Notice how the name of the model is still the old one if you were to hover over the left button for drilldown nav

**Screenshots**

https://github.com/user-attachments/assets/0db24b8e-e0e6-452f-80a9-1e5e138ec96a

**Comment by YohannParis** [comment]
Dealt in another issue
