### ISSUE TITLE
[TASK]: Better way to deal with optional types that are not really optional

### ISSUE THREAD

**Issue by mwdchang** [DARPA-ASKEM/terarium#4488]
### Preamble
The majority of our Typescript types are based off 'TerariumEntity' and 'TerariumAsset'.  Roughly speaking the types generated looks something like this combined.

```
{
  id? : string,
  name?: string,
  description?: string,
  ...
}
```

However from data-engineering point of view, `id`, `name` are not really optional per se, they are either null or some kind of string/text. And indeed they are model that way in Java which is the used to generated the Typescript typings.

The crux of the issue is the use of `@TSOptional` to satisfy a specific requirement from the user-interface, that is: **when we create an entity/asset - we do not usually have an id that we can assign**

However this decision created many other pain-points for the UI:
- The code is, generally speaking, more verbose with optional-chaining syntax sugar `a?.b".c?....`
- It is harder to write for and reason with .... does the field actually needed or not??
- It makes the interface messier because data structure is passed through the component properties

### Proposal
We should not generate typings for a specific use case, rather we should just produce the needed typings on a need-basis. For example, so we have 

```
interface Person {
  id: string;
  name: string;
  occupation: string
}
```

If we want to create a new Person, we don't have an id so it is a typing error, but there are a suite of Typescript utilities that can be used to address this. We can create:

```
interface NewPerson = Omit<Person, 'id'>

function createPerson(person: NewPerson) {
}
```

And that will give us a Person definition without the id field for the creation process. In this way, we can use Person everywhere with all the fields well-defined, while on creation we will use the NewPerson typing.

### Task
`id` field should not be optional. Other than that we can probably argue over the other fields as well. But we should do an assessment and get agreement over the basic Java classes and see exactly what we want to model.

Unfortunately because of the inheritance usage, it may not be possible to do this little by little, so actual implementation is best when there is a bit of a lull on the front-end side of things.

### References
- https://www.typescriptlang.org/docs/handbook/utility-types.html

**Comment by dvince2** [comment]
Opting to close this issue.  given the time remainng for the project this won't be done, but its a good one
