### ISSUE TITLE
[TASK]: UX: Adjustments to the operator drilldown output dropdown

### ISSUE THREAD

**Issue by ngraham76** [DARPA-ASKEM/terarium#4489]
**Describe the task**
Some small UI adjustments to the operator output drop downs.

![image](https://github.com/user-attachments/assets/7efac9e7-3950-4571-af3c-6c40a9fb4cb9)

![image](https://github.com/user-attachments/assets/b345c9f3-8a8f-4ecb-acf4-a65b760631c9)

**Comment by mwdchang** [comment]
Done
