### ISSUE TITLE
[FEAT]: Dataset enrichment flow and update to page layout

### ISSUE THREAD

**Issue by jamiewaese-uncharted** [DARPA-ASKEM/terarium#4512]
**Issue 1: **
The mechanism to add metadata enrichment to a Dataset is flawed. The button is in the Provenance section, and we're removing that section. Also, it's hard to find. So we want to move that button into the header and rename it.

**Issue 2: **
Nobody likes how we split the content of a Dataset across the Description and Data tabs. We want to get rid of those tabs and add the data table to an accordion section of the main page. 

**CURRENT**
<img width="1040" alt="Monosnap Terarium 2024-08-20 13-44-55" src="https://github.com/user-attachments/assets/45dc5eed-1996-4ae8-96f5-558f47f2e919">
<img width="1041" alt="Monosnap Terarium 2024-08-20 14-02-25" src="https://github.com/user-attachments/assets/05f1b3b1-b056-4307-aa30-3e3e49e2bb97">

**PROPOSED**
The new dataset page should look something like this:
![Dataset - full page](https://github.com/user-attachments/assets/b21293c6-de67-473d-aed8-e0a8bd64635c)

When you click on the `Enrich metadata with AI assistant` button, you get a modal where you can select which document you want to use. The default option is "No document".

<img width="957" alt="Monosnap Terarium - August 2024 2024-08-20 14-09-48" src="https://github.com/user-attachments/assets/015828a4-a613-4369-a78d-88cf3165224b">

![image](https://github.com/user-attachments/assets/3a1efbc9-244a-46bc-9fe8-26efdf956685)

**Comment by shawnyama** [comment]
pass 2 coming up!
