### ISSUE TITLE
[BUG]: Clicking on dataset freezes browser

### ISSUE THREAD

**Issue by dvince2** [DARPA-ASKEM/terarium#4541]
- Scenario: https://github.com/DARPA-ASKEM/terarium/blob/main/testing/manual/manipulate-asset-from-project.md
- Step: 3.2
- Link to the project: https://app.staging.terarium.ai/projects/eb70c401-92dc-4b2a-b584-8f2002fa9041/dataset/3bbf5285-53d7-448c-8c33-dc53d4fd5baa

**Describe the issue**
Unable to click on the ... button to download the dataset, or any other buttons. Browser freezes

**Comment by dgauldie** [comment]
potentially related to #4523

**Comment by dvince2** [comment]
This issue seems to be fixed with the upcoming changes made by @shawnyama in https://github.com/DARPA-ASKEM/terarium/pull/4536
