### ISSUE TITLE
[BUG]: Update Vue Version

### ISSUE THREAD

**Issue by shawnyama** [DARPA-ASKEM/terarium#4544]
**Describe the bug**
Came across this when doing the optimize test step 5b.

This simulation chart was empty once optimize finished. I got some 404s so it seems like the chart didn't exist yet in the backend. After waiting a bit and then reopening the drilldown the chart appears as it should.

**Screenshots**
![image](https://github.com/user-attachments/assets/fef72fed-677a-4558-a29a-c19fa69cd696)

**Comment by Tom-Szendrey** [comment]
This is two different bugs
1) The simulation 404 -> This was because the hmi-server was running into issues at the time and I cannot reproduce.
2) the insertBefore -> Still looking into this.
