### ISSUE TITLE
[BUG]: Calibrate loss chart lost

### ISSUE THREAD

**Issue by Tom-Szendrey** [DARPA-ASKEM/terarium#4550]
- Scenario: https://github.com/DARPA-ASKEM/terarium/blob/main/testing/manual/calibrate.md
- Step: 4
- Link to the project: https://app.staging.terarium.ai/projects/f8501b9d-31ab-4551-bdef-c8e8cd3c7491/workflow/4b4a28b2-9c04-4759-8de1-78c9b7aa5d41

**Describe the issue**
After running a calibration the loss chart disappears, as opposed to previously being fetched in a non sorted chart 
<img width="962" alt="image" src="https://github.com/user-attachments/assets/7aad028d-1e93-44c0-bbc4-55002c1098b6">
<img width="1401" alt="image" src="https://github.com/user-attachments/assets/11413b8e-f5d7-473b-a814-16375a9811e4">

**Comment by dgauldie** [comment]
The fix for this should be to make these charts vega-lite charts if possible

**Comment by dgauldie** [comment]
closing as a duplicate
