### ISSUE TITLE
[TASK]: Add save as semantic for calibrate operation

### ISSUE THREAD

**Issue by mwdchang** [DARPA-ASKEM/terarium#4568]
See https://www.figma.com/design/uXs52uABr8tliYK5UltgaB/Terarium---August-2024?node-id=296-86122&t=tXroImdXsfn57gWe-0

Note calibrate is more complicated because it produces compounded outputs of datasetid and model-configuration. 

There are several parts for this change:

- If not already, we want to generate semi-sensible names for the model-config created from calibrate
- If not already, hook up a "reset" feature, this will require some knowledge of whether state has been modified. See workflow-service#isWorkflowNodeDirty
- Add a `save for reuse` button, that, when invoked, will make the model-configuration available in the model-config operator's resource list
- Don't worry about "saving" the dataset for now
- Don't worry too much about the renaming feature for now (e.g. change the output model's name), we will revisit this. (See: https://github.com/DARPA-ASKEM/terarium/issues/4557)

![Image](https://github.com/user-attachments/assets/40048096-308f-476c-9d89-70e86ff91680)

**Comment by blanchco** [comment]
Reset state will be done in #4660
