### ISSUE TITLE
LLM/AI chart annotation engineering

### ISSUE THREAD

**Issue by mwdchang** [DARPA-ASKEM/terarium#4571]
We currently have a prototype of LLM-assisted chart annotation that we want to move forward with.

We want to 
- Come up with the basic data structure for storing chart-annotations, these are generally speaking, too large to store directly into a workflow state so we will want to store them in a DB probably.
- Create the associated API end points to manage annotations. For the most part we need Create and Delete

**Comment by YohannParis** [comment]
Handle in split issues
