### ISSUE TITLE
[BUG]: Column widths/alignments of the `Observables` table are broken in the `Model` operator when the math expression is too long

### ISSUE THREAD

**Issue by liunelson** [DARPA-ASKEM/terarium#4574]
**Describe the bug**
The widths of the `Observables` table in the `Model` operator is broken when the sympy math expression is really long, causing a horizontal scrollbar to appear.

**To Reproduce**
1. Go to https://app.staging.terarium.ai/projects/80bfb79e-808c-45bc-a96e-7addeef46557/workflow/641e25b2-e62d-4f20-8fb9-ac32d88db8e0?operator=81a97aa9-a6e0-4e03-9735-4f53aa56cb0c

**Expected behavior**
The `R0 | R0 | Unit [Add a unit] ...` stuff should not slide around and should stay aligned with the other rows.

**Screenshots**
![Screenshot 2024-08-23 at 4 45 28 PM](https://github.com/user-attachments/assets/4c11878f-4cd0-44db-8ed2-74cf4ac46b25)
 help explain your problem.

**Comment by shawnyama** [comment]
probably should move away from css grid
