### ISSUE TITLE
[FEAT]: Add a dataset to a project

### ISSUE THREAD

**Issue by dgauldie** [DARPA-ASKEM/TERArium#46]
**Describe the solution you'd like**
- [ ] Add the ability to tie a dataset from the _Resources Page_ to any _project_ from the user
- [x] Add the ability to upload a dataset from a file or the _Data Explorer_ to a _project_ directly (which will automatically add it to the _Resources Page_

**Comment by amostafa-uncharted** [comment]
Note that the outstanding PR: https://github.com/DARPA-ASKEM/TERArium/pull/133 includes initial implementation of a client-side store to tracks all project resources including datasets, models, and papers. 
Ideally, the appropriate solution to include a client-side store (i.e., cache) that is in sync with a backend store for persistence.

**Comment by amostafa-uncharted** [comment]
Note sure what is missing here to close this issue @dgauldie
