### ISSUE TITLE
[Minor BUG]: Matrix updates cells with or without Ok button 

### ISSUE THREAD

**Issue by Tom-Szendrey** [DARPA-ASKEM/terarium#4614]
**Describe the bug**
I expect the behaviour of this is supposed to be that if a user clicks cancel it does not update the underlying structure and instead reverts back to what it previously was.

**To Reproduce**
1. Go to a model configuration page that has a matrix (has been stratified)
2. Open any matrix, remember at least one of the values in it.
3. Update that value in the matrix view and click cancel
4. See that the value was still updated

**Expected behavior**
1. Go to a model configuration page that has a matrix (has been stratified)
2. Open any matrix, remember at least one of the values in it.
3. Update that value in the matrix view and click cancel
4. See that the value was not updated

**Screenshots**
<img width="869" alt="image" src="https://github.com/user-attachments/assets/24453ae9-2d62-4b91-9a1d-fc2bde9ea751">

**Comment by YohannParis** [comment]
We need to remove the `cancel` button.
the `ok` button needs to be renamed with `apply`.
