### ISSUE TITLE
[TASK]: Extend document service implementation to give more control to users when fetching extractions

### ISSUE THREAD

**Issue by amostafa-uncharted** [DARPA-ASKEM/TERArium#468]
**Describe the task**
Currently, fetching paper extractions is done via the function `getXDDArtifacts` at the client side which calls the xdd proxy path `/xdd/extractions`. The current implementation however does not expose two parameters to either fetch ALL extractions associated with a given paper (via `doc_doi`) or to search for extractions as part of keyword search (via the `term` parameter).

IT looks like that xDD has extended the API that work with extractions on their side and now other undocumented flags can be used such as "`page`" and "`ASKEM_CLASS`"
For example, the following will returns only figure extractions that match a given search term
https://xdddev.chtc.io/askem/object?query_all=COVID-19&ASKEM_CLASS=Figure

We need to update the extraction end point that is part of the document service to allow the user to specify the type of extractions to be returned as an optional parameter. The client side code should also be updated to leverage this flag to only return perhaps Figures, Tables, and Equations.
Note that if so much data is returned, the "page" flag can be used as a query parameter to retrieve paginated result and should also be integrated in the HMI server/client.

**Task Items**
- [ ] list of items for completion
- [ ] another item

**Goal**
A clear and concise description of what the end result must have for it to be approved as complete.

**Screenshots**
If applicable, add screenshots or designs

**Additional context**
Add any other context about the task here

**Comment by dvince2** [comment]
Back end work is completed - let me know if anything else needs to be done for the front end to take advantage of it.

**Comment by amostafa-uncharted** [comment]
Thanks Derek. I just had a chat with @shawnyama a few minutes ago and he would benefit from having this PR merged in!

For the sake of prioritizing the type of extractions we get back from the service, I do think the frontend need to be updated with regards to how the extractions are fetched. Within the data explorer and while searching xDD extractions using keyword search, we should filter for returning only images, tables, and equations.
The update should be done in the `data.ts` file near the end of the function `searchXDDArticles` wherein the `getXDDArtifacts` is called

**Comment by dvince2** [comment]
@shawnyama do you want this PR merged in as-is, or do you want to complete the front end tasks needed for this feature on this branch?

**Comment by shawnyama** [comment]
@dvince2 I assume this is good to merge, my frontend should be more or less prepared for this
