### ISSUE TITLE
[BUG]: 'Create Intervention Policy' testing fail

### ISSUE THREAD

**Issue by ngraham76** [DARPA-ASKEM/terarium#4688]
**Describe the bug**
There are a couple of problems happening when [testing Create Intervention Policy](https://github.com/DARPA-ASKEM/terarium/blob/main/testing/manual/intervention-policy.md)

**To Reproduce**
1. Add a Create Intervention Policy operator
2. Create some new interventions based on what is defined in the [test script](https://github.com/DARPA-ASKEM/terarium/blob/main/testing/manual/intervention-policy.md) 
3. The Save button (**Step 8** in the test) should be enabled once changes are made to the new policy - it remains disabled, no way to save the policy except for "Save as...".
4. If you click "Save as..." to save it as a new policy and connect it to a Simulate operator - and run - there are errors. See [this example](https://app.staging.terarium.ai/projects/e97fac66-3bab-4e48-8f8f-715e32eff43e/workflow/068c9901-ba9a-470b-8189-f146e6fdc773?operator=3d7eb0fa-047b-4402-8100-b17fc396dbb9) from my test.

**Screenshots**
![image](https://github.com/user-attachments/assets/cc218f4d-88a9-4a39-98c9-03e51f5f925a)
![image](https://github.com/user-attachments/assets/53210942-2cac-48b9-ac01-502875546c57)

**Comment by blanchco** [comment]
The error in simulation seems to be coming from pyciemss service, for me it just seems to run forever, Ill look into the logs.  Will address the saving issue for now it just needs to be enabled on the initial open
