### ISSUE TITLE
[FEAT]: Create Intervention Policy - misc adjustments

### ISSUE THREAD

**Issue by jamiewaese-uncharted** [DARPA-ASKEM/terarium#4751]
A few updates to the **Create Intervention Policy** operator here:

### ISSUE 1: STATIC INTERVENTIONS
**CURRENT**
Static intervention descriptions begin with selecting the parameter or variable and you then make a list of values by date.
![image](https://github.com/user-attachments/assets/be67cdc5-b179-4aec-a7f3-f353c56a4ce1)

**PROPOSED**
We want to invert this slightly. Static interventions should begin with selecting the day you want something to happen, and then you make a list of which parameters/variables you want to set to a specific value.
<img width="765" alt="image" src="https://github.com/user-attachments/assets/16a3e1ce-e054-46c8-a126-4a9b09d66bc2">

------------------------------------------------------------------------------------------------------------------------

### ISSUE 2: DYNAMIC INTERVENTIONS
**CURRENT**
![image](https://github.com/user-attachments/assets/3951c61d-5654-4b8f-85d7-06070521c978)

**PROPOSED**
Can we add the units of the selected parameter or variable to the end of the madlib sentence?
<img width="473" alt="Monosnap Terarium - September 2024 2024-09-11 10-45-57" src="https://github.com/user-attachments/assets/ebc14cde-bf22-4bc6-bcb2-41ce570ac201">

------------------------------------------------------------------------------------------------------------------------

### ISSUE 3: ADD AN OPTIONAL DOCUMENT INPUT 

**CURRENT**
Interventions need to be created manually from scratch. There is no option to pipe a document or anything else in.
![image](https://github.com/user-attachments/assets/12cf83ed-c225-432c-b981-65048080eeaf)

**PROPOSED**
We'd like to be able to pipe a document into the node, and then use an LLM to extract any described interventions from the document.

------------------------------------------------------------------------------------------------------------------------

### ISSUE 4: ADD 'EXTRACT FROM INPUTS' AND 'CREATE NEW' BUTTONS TO DRILLDOWN

**CURRENT**
It's a pain to create new interventions.
![image](https://github.com/user-attachments/assets/0cae4413-272d-4aed-b1ca-67e71b126643)

**PROPOSED**
Click the 'Extract from inputs' button and an LLM assistant will do the job for you.
<img width="1172" alt="Monosnap Terarium - September 2024 2024-09-11 10-56-13" src="https://github.com/user-attachments/assets/e92ff77a-fd76-49df-a152-5e8755bc405d">

If you click the green 'Create new' button, you get a modal where you provide a name for the new intervention:
<img width="578" alt="image" src="https://github.com/user-attachments/assets/a04c4467-324b-4bcd-9d7e-dddfd3f45dfe">

And then the page should look something like this:
![image](https://github.com/user-attachments/assets/14f34a32-d5f3-4be9-b353-e9c11cc71a9e)

**Comment by asylves1** [comment]
POA
- issue 1:
  - Change the add method to reuse `starting at..` change layout
- issue 2: 
  - Will have to find a way to map the units from the model
- issue 3:
  - update the inputs to accept doc asset and add link to header of drill down

**Comment by asylves1** [comment]
Frontend change that don't require backend work are done in this PR
https://github.com/DARPA-ASKEM/terarium/pull/4879
