### ISSUE TITLE
Notebook re-run notifications

### ISSUE THREAD

**Issue by jamiewaese-uncharted** [DARPA-ASKEM/terarium#4754]
### Issue 1: Add 'Re-run all cells' button and notification
**CURRENT**
When you open a previously generated **Transform dataset** operator, it loads the input and output text of the previous run, and it indicates that the kernel is "Ready", but none of the transformations are actually available to use. 

![Image](https://github.com/user-attachments/assets/50d8c303-7238-41a5-a007-71029e1d74ca)

**PROPOSED**
There should be an indicator to tell users that the cells need to be re-run if they want to make any changes or use anything the operator generated downstream.

There should also be a "Re-run all cells" button on the toolbar.

It would be nice if you can make the page look more like this:
![Image](https://github.com/user-attachments/assets/3304bc82-9ef7-4f41-bc66-2d130b92dd8c)

**Comment by dgauldie** [comment]
The "Save for reuse" button should be disabled when the yellow banner is there. This adds a guardrail to prevent saving dataframes as datasets when the session is not active.
