### ISSUE TITLE
[BUG]: Model page shows incorrect/missing metadata when models has parameters named `*_*`

### ISSUE THREAD

**Issue by liunelson** [DARPA-ASKEM/terarium#4764]
**Describe the bug**

I have a model (see below) for which the model page is showing incorrect parameter information.
1. the parameter `NPI_mult` is shown as `NPI` only and is missing all its metadata
2. ditto for the parameter `vacc_mult`
3. all parameters `r_*` are forced into a single matrix, even though this model is not a product of stratification

This is probably due to the (incorrect) assumptions about IDs with `*_*`.

The model:
[SEIRHD vacc model for LA County t0 = 10_28_2021 (1).json](https://github.com/user-attachments/files/16972411/SEIRHD.vacc.model.for.LA.County.t0.10_28_2021.1.json)

**To Reproduce**
1. Upload this model
2. Inspect its model page
3. Create a Configure Model operator and plug the model to it
4. Inspect the parameter table to see the lack of values of `NPI_mult, vacc_mult` and the incorrect matrix for `r_*`

**Screenshots**
![Screenshot 2024-09-11 at 9 55 07 PM](https://github.com/user-attachments/assets/dd4bcb89-7243-47b7-8e23-28ae75bcba59)
![Screenshot 2024-09-11 at 9 54 57 PM](https://github.com/user-attachments/assets/a3cdef9b-c559-4a11-b691-e729c60b7bcd)
![Screenshot 2024-09-11 at 9 54 47 PM](https://github.com/user-attachments/assets/bb94c35d-bcbb-4638-8d77-9f671681114d)
![Screenshot 2024-09-11 at 9 37 08 PM](https://github.com/user-attachments/assets/371fc64b-7b8d-4eba-b723-c62aa6e28425)

**Comment by mwdchang** [comment]
I think we can add additional heuristics to detect cases like this - but at some point these become educated guesses.
