### ISSUE TITLE
[BUG]: There is no save for reuse in the simulate, calibrate, and optimize components

### ISSUE THREAD

**Issue by dgauldie** [DARPA-ASKEM/terarium#4767]
**Describe the bug**
We need to have "save for reuse" buttons for simulate, calibrate, and optimize components.
There will need to be design for calibrate and optimize since they have multiple outputs
 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by blanchco** [comment]
linked wrong PR, reopening
