### ISSUE TITLE
[BUG]: fail optimization

### ISSUE THREAD

**Issue by YohannParis** [DARPA-ASKEM/terarium#4773]
- Scenario: [Optimize](https://github.com/DARPA-ASKEM/terarium/blob/main/testing/manual/optimize.md)
- Step: 4.a.4
- Link to the project: https://app.staging.terarium.ai/projects/8583471a-9f09-49c2-8501-cf239870ba58/workflow/21577503-97e9-4c31-83d5-ad90640a54cc?operator=8787ff4f-7905-438c-ae60-324148fade2b

**Describe the issue**
<img width="1331" alt="Screenshot 2024-09-12 at 13 43 24" src="https://github.com/user-attachments/assets/23e8c650-3262-4553-9f23-edbc65dc4421">

**Comment by liunelson** [comment]
I re-ran this Optimize operator and everything seems fine 🤷‍♂
