### ISSUE TITLE
Select equation for extraction (front-end)

### ISSUE THREAD

**Issue by asylves1** [DARPA-ASKEM/terarium#4782]
If the document extraction component misses an equation found in the document pdf, the user should be able to use a selection tool to copy an image of the equation and send if off to get extracted into latex form

![Image](https://github.com/user-attachments/assets/4d53bf83-461d-44e7-917b-4abc8886f388)

**Comment by YohannParis** [comment]
Waiting to update Adobe account with `localhost:8080` as an allowed domain for the Embeded JS API.
