### ISSUE TITLE
[BUG]: Missing border on the notes panel

### ISSUE THREAD

**Issue by YohannParis** [DARPA-ASKEM/terarium#4821]
**Describe the bug**
![Screenshot 2024-09-17 at 11 17 08](https://github.com/user-attachments/assets/30759d3a-52e0-47e5-b208-89b1ddd44d33)

**Comment by pascaleproulx** [comment]
We are removing the Notes panel (see [FEAT]: Remove "Notes" side panel from app
[#4752](https://github.com/DARPA-ASKEM/terarium/issues/4752) so maybe this will not be an issue?
