### ISSUE TITLE
[FEAT]: Project Download/Upload

### ISSUE THREAD

**Issue by YohannParis** [DARPA-ASKEM/terarium#4840]
* We need to add a download project button and an upload button.
* Those endpoints exists and are usable via Swagger/curl.

**Comment by Tom-Szendrey** [comment]
Do we know where we want these?

For example
download being project overview + here? 
<img width="407" alt="image" src="https://github.com/user-attachments/assets/59507a9a-c961-4288-ba5b-3c8c5e269311">
