### ISSUE TITLE
[BUG]: Intervention Policy chart for dynamic intervention not displayed

### ISSUE THREAD

**Issue by YohannParis** [DARPA-ASKEM/terarium#4846]
- Scenario: [Simulate](https://github.com/DARPA-ASKEM/terarium/blob/main/testing/manual/simulate.md)
- Step: 3.13. inspect charts
- Link to the project: https://app.staging.terarium.ai/projects/8583471a-9f09-49c2-8501-cf239870ba58/workflow/ab7f641f-99c3-4489-8672-d834c7bde053

**Describe the issue**
The chart for S is not being displayed in the node of the intervention policy

![Screenshot 2024-09-19 at 11 11 30](https://github.com/user-attachments/assets/c61e984c-46ae-4094-95c2-8a783c35eb48)

Nor in the drilldown

![Screenshot 2024-09-19 at 11 13 20](https://github.com/user-attachments/assets/0ae68e3f-680b-40c8-bcc7-5aa3eeeeca9a)

**Comment by blanchco** [comment]
This looks like it has been fixed and dynamic charts are no linger being shown. We do not have a design to show the dynamic interventions at the moment so we should not show any graph at this moment
