### ISSUE TITLE
[FEAT]: Change behaviour of _Save as_

### ISSUE THREAD

**Issue by YohannParis** [DARPA-ASKEM/terarium#4858]
When a user click an asset `Save as...` or `Save for Reuse` buttons, a new asset is created and added to the project, which is correct.
But the current asset page should be update with this new asset. In the case of a node, then it's state needs to be updated and the output dropdown.

**Comment by mwdchang** [comment]
This needs some additional discussion with Pacale on exactly what she wants, the behaviours are not uniform across operators. Roughly the current state of things: 

```
## Save and change output #1
Right now if we "save as" it saves a new asset, but does not change the output of the operator.
- Model

## Save and change output #2
We don't change the output, but you can just select it from the side resource panel after save-as operation completes, we can automate this if desired.
- Model Config
- Intervention Policy


## Don't apply
Not implemented, but Save-as acs on the outputs directly (we are not creating new assets), so putting them into projec-asset should be sufficient
- Model-from equation
- Vallidate
- Simulate


## Doesn't really work because of compound output types
These operators produce compound outputs, but save-as saves only one of them, for example calibrate saves a model-config, it the operation it self produces both model-config and dataset.
- Optimize
- Calibrate


## Unknown or not well defined
Not exactly sure what we want to do here
- Document transform
```

**Comment by YohannParis** [comment]
From my understanding the goal is to have the following:

```
### Save
The user has made changes to the asset/state. Clicking on `Save` will update the asset/state.

### Save as
- Asset
Clicking on `Save as` will create a new asset, add it to the project, and update the __current page__ with the new asset.
- Operator
Clicking on `Save as` will create a new asset, add it to the project, and update the __current state and output__ with the new asset. 

### Save for re-use
Clicking on `Save for re-use` will create a new asset, add it to the project.
```

**Comment by mwdchang** [comment]
Chatted with Pascale/Cole/Shawn, the consensus is that the operators that need changing are
- model-operator
- dataset-operator

For both of these operators, "Save as" should be (always) available, and such that when save-as is invoked, the newly saved asset should replace the existing asset in the operator. For example, if the model-operator has model-X, after save-as, it will have model-Y, and subsequently the downstream operators will be invalidated because their upstream has a new instance (Y instead of X).
