### ISSUE TITLE
[BUG]: The code cell in the notebook view of Configure Model operator does not show any AI assistant response

### ISSUE THREAD

**Issue by liunelson** [DARPA-ASKEM/terarium#4867]
- Scenario: Model Configuration Notebook
- Step: 3.4. Ensure code is generated
- Link to the project: https://app.staging.terarium.ai/projects/34e7b955-f408-4e8b-be27-9429480ad6aa/workflow/fc27475c-d08c-4365-9117-6bed954c1635?operator=1cb2adb1-b7b2-4842-b8ea-27a023bb082f

**Describe the issue**
Regardless of what query is sent to the AI assistant in the Configure Model notebook view, the code cell remains empty.
![Screenshot 2024-09-20 at 9 41 56 AM](https://github.com/user-attachments/assets/057bc62b-5c56-48c4-a7a1-02a9a9128b6c)

**Comment by YohannParis** [comment]
fix #4958
