### ISSUE TITLE
[BUG]: if a user changes title or description and then moves to another configuration, the system does not warn them that they will lose those changes

### ISSUE THREAD

**Issue by dgauldie** [DARPA-ASKEM/terarium#4873]
- Scenario:
- Step:
- Link to the project:

**Describe the issue**

![image](https://github.com/user-attachments/assets/69b00bb1-6df9-4965-a181-5a7b4eb50a9f)

**Comment by YohannParis** [comment]
Please rephrase the modal to explain that the user will loose all the changes on top of changing the state.
