### ISSUE TITLE
[BUG]: Stratify notebook llm output missing structure field

### ISSUE THREAD

**Issue by brittanykondo** [DARPA-ASKEM/terarium#4932]
In the test: https://github.com/DARPA-ASKEM/terarium/blob/main/testing/manual/stratify-notebook.md. Step 3.5 says the code output should look like: 
![Screenshot 2024-09-26 at 11 58 34 AM](https://github.com/user-attachments/assets/46eb6785-f90b-49b6-a94d-25d6dacd9848)

However, in the UI, it returns a blank 'structure' field':
<img width="721" alt="Screenshot 2024-09-26 at 11 59 29 AM" src="https://github.com/user-attachments/assets/59f735bc-9eb4-4ec4-b0d2-0257814230e6">

**Comment by YohannParis** [comment]
@liunelson please validate if this is an issue.

**Comment by liunelson** [comment]
The generated code is incorrect:

There are three cases:
1. when you want one specific directed interaction, for example, travel from Toronto to Montreal
```
structure = [['Toronto', 'Montreal']],
directed = True
```
2. when you want one specific interaction, for example, travel between Toronto and Montreal, in _both_ directions
```
structure = [['Toronto', 'Montreal']],
directed = False
```

3. when you want _all_ possible interactions (e.g. travel from every city to every other and vice versa)
```
structure = None,
directed = <irrelevant>
```
or 
```
structure = <a list of all possible pairs of stratum group>,
directed = <False if the structure list is all permutations (e.g. AB, BA), irrelevant if the list is all combinations (AB, no BA)> 
```

4. when you want _no_ interaction (i.e. all the stratified pieces of a model are independent from each other, equivalent to travel whatsoever).
```
structure = [],
directed = <irrelevant>
```

In @brittanykondo's prompt, it should have returned *Case 2*.
This suggests that we need to expand on the LLM prompt to cover all these different cases.
