### ISSUE TITLE
[BUG]: "all timepoints" vs. "last timepoint" - success criteria charts in Optimize incorrect

### ISSUE THREAD

**Issue by liunelson** [DARPA-ASKEM/terarium#4937]
**Describe the bug**

Holly experienced this bug here:
https://app.staging.terarium.ai/projects/ab5351dd-72a7-44f3-9d3c-0cebb6fee13c/workflow/7cd01f35-eb2d-48d2-b85f-bdbb64eda33f?operator=cae75259-b39a-42e9-b622-6795e795f2c2

She picked `all timepoints` in their success criterion but the output chart for success criteria shows that `obs_nday_average_qoi` was selected for the optimization.

**Expected behavior**
`all timepoints` -> `obs_max_qoi`
`last timepoint` -> `obs_nday_average_qoi`

**Screenshots**

The user's success criterion:
![Screenshot 2024-09-26 at 2 06 58 PM](https://github.com/user-attachments/assets/0919335f-62bd-405c-8167-f52572df1a5c)

The output chart showing `19.9854`
![Screenshot 2024-09-26 at 2 08 41 PM](https://github.com/user-attachments/assets/ce553f5a-f84f-43d4-963a-6433fbc8b76d)

The simulation plot showing that the global maximum is ~`5,000` and the last timepoint value is ~`20.0`
![Screenshot 2024-09-26 at 2 08 08 PM](https://github.com/user-attachments/assets/b90c7131-81ca-4bbf-9189-cd7c58e769dd)

**Comment by Tom-Szendrey** [comment]
Just to keep some notes visible
The following dropdowns are connected correctly.
```
all timepoints -> obs_max_qoi
last timepoint -> obs_nday_average_qoi
```

The risk results returned from optimize call is always providing **average** and Nelson is suggested that if the user selected the "last timepoint" we should not be displaying this **average** on the success criteria chart:
![Image](https://github.com/user-attachments/assets/81777e62-518e-43be-b6ab-8e0a5147bd28)

**Comment by liunelson** [comment]
The success criteria charts are not being populated with the correct data.

When the QoI is "last timepoint", it should be as it is currently: filter for all values with timepoint = last timepoint and make a histogram from them.
```python
t = result_postoptimize['data']['timepoint_id'].iloc[-1]
data = result_postoptimize['data'][result_preoptimize['data']['timepoint_id'] == t]['I_state']
```

When the QoI is "all timepoints", it should be: group by sample ID and calculate the max value (one per sample ID).
```python
data = result_postoptimize['data'].groupby(['sample_id']).max()['I_state']
```

For this scenario, where I switch between "last timepoint" (orange) and "all timepoints" (green):
![Image](https://github.com/user-attachments/assets/2fc591bb-7593-416d-9459-d809e2431728)

I should get a "success criteria" chart like this:
![Image](https://github.com/user-attachments/assets/7e655153-5d8e-43b3-89a6-a35b6c5abc72)
