### ISSUE TITLE
[BUG]: Intervention charts not considering different parameters in the same intervention

### ISSUE THREAD

**Issue by pascaleproulx** [DARPA-ASKEM/terarium#4940]
- Scenario: https://github.com/DARPA-ASKEM/terarium/blob/main/testing/manual/intervention-policy.md
- Step: 4
- Link to the project: https://app.staging.terarium.ai/projects/59d1af73-e373-42da-9e88-ac020a39cc1f/workflow/8f52229b-276a-474a-a534-f30d3c409f54?operator=415c1627-fbc2-4565-bc9a-0f287f569f6d

**Describe the issue**
Chart should look at which parameter is defined in an intervention, not assume all values are for the same parameter in one intervention like it was before. In the screenshot below, you can see that the gamma parameter value is shown on the beta plot. Instead, there should be two chart, one for each parameter.
![image](https://github.com/user-attachments/assets/f0ce26e7-7dcd-465e-ad73-a37c1f8336d4)

**Comment by jryu01** [comment]
This is fixed by https://github.com/DARPA-ASKEM/terarium/pull/4974
