### ISSUE TITLE
[BUG]: Calibration run fails with an error

### ISSUE THREAD

**Issue by jryu01** [DARPA-ASKEM/terarium#4942]
- Scenario: https://github.com/DARPA-ASKEM/terarium/blob/main/testing/manual/calibrate.md
- Step: 3-4
- Link to the project: https://app.staging.terarium.ai/projects/242133ac-4579-4a27-952c-eb645c3dd5a1/workflow/2f5739b8-ac8b-4140-b728-07bfe2915ffb?operator=cb12b3b9-9a03-461e-aafe-509481beb111

**Describe the issue**
Failed calibration run
![Screenshot 2024-09-26 at 2 46 08 PM](https://github.com/user-attachments/assets/3280a87c-a09b-4235-b2b7-455866a997f5)

**Comment by YohannParis** [comment]
If the error is because of the model uses, we should have better test before sending to calibration service.

**Comment by liunelson** [comment]
I just re-ran the calibration and the result looks exactly as expected. The error might have been caused by our lagging PyCIEMSS version.
