### ISSUE TITLE
[BUG]: model-configuration-notebook test fails

### ISSUE THREAD

**Issue by jamiewaese-uncharted** [DARPA-ASKEM/terarium#4948]
- Scenario: model-configuration-notebook
- Step: 3-3
- Link to the project: https://app.staging.terarium.ai/projects/499d77df-a751-45fa-a3ce-8982cdcdd248/workflow/ca602f43-3a4e-4e2f-9265-e610736e098f

**Describe the issue**
The AI assistant doesn't generate code as expected.![image](https://github.com/user-attachments/assets/fd3ba89a-f7f1-4893-b4cc-a33e627fa7d4)

![image](https://github.com/user-attachments/assets/8105df78-b2c0-49e3-bd35-1375a4b4d318)

**Comment by YohannParis** [comment]
Update the test to not include that question because it doesn't match the goal of the operator anymore.
