### ISSUE TITLE
[BUG]: Non-stratified parameters with `_` in their ID/name are misrepresented in the parameter table

### ISSUE THREAD

**Issue by liunelson** [DARPA-ASKEM/terarium#4959]
**Describe the bug**
I have a model with a parameter named `p_unvaccinated_vaccinated`. In the Model page and the Configure Model operator, it is simply shown as `p` and thus not obvious if they are actually the same parameter or not.

**To Reproduce**
See this Model page of this model:
https://app.staging.terarium.ai/projects/29205f06-9b02-45e9-aeb1-164aa2be3e28/model/47ac0215-412b-4f2f-b0b3-d12fdc0da311

**Expected behavior**
I imagine that Terarium tried to represent all parameters with `_` as matrices but the `n = 1` case (where only one parameter has `_`) is bugged.

It's probably ok to represent `p_unvaccinated_vaccinated` as either (1) `p` with a `1 x 1` matrix view or (2) just a normal, independent parameter.

**Screenshots**
![Screenshot 2024-09-26 at 5 10 41 PM](https://github.com/user-attachments/assets/d2632552-3abf-444a-ad73-0c3da6ab4fd1)
![Screenshot 2024-09-26 at 5 10 49 PM](https://github.com/user-attachments/assets/7cb6b5f0-f5cb-49b6-9f50-d04253d3c68d)

**Comment by mwdchang** [comment]
This seem to be the same problem as https://github.com/DARPA-ASKEM/terarium/issues/4764
