### ISSUE TITLE
[BUG]: "undefined" chart title in the `Create intervention policy` operator

### ISSUE THREAD

**Issue by liunelson** [DARPA-ASKEM/terarium#4960]
**Describe the bug**
The title of the chart in `Create intervention policy` is just "undefined"

**To Reproduce**
Example workflow:
https://app.staging.terarium.ai/projects/29205f06-9b02-45e9-aeb1-164aa2be3e28/workflow/e26c7135-5609-4d34-98fe-e60dce0197ab

**Expected behavior**
Probably one chart per intervened parameter, with the title = name of the parameter

**Screenshots**
![image](https://github.com/user-attachments/assets/f2b6dcf3-5c1b-439a-911e-e1b2b7da94f2)

**Comment by YohannParis** [comment]
Duplicate
