### ISSUE TITLE
[BUG]: Cannot "save" when a new policy is created using "Create" in the `Create intervention policy` operator

### ISSUE THREAD

**Issue by liunelson** [DARPA-ASKEM/terarium#4961]
**Describe the bug**
When I click "Create new" in the `Create intervention policy` operator, a blank policy is created but I cannot save any edit made to it since the "Save" button is always greyed out. 

**To Reproduce**
1. Create a new project and workflow
2. Load any model
3. Connect the model to a `Create intervention policy` operator
4. Click "Create new"
5. Edit this policy by adding a new intervention, changing the description, etc.
6. Note the "Save" button is always greyed out

**Expected behavior**
Let me edit and save intervention policies! Otherwise, there is an accumulation of redundant policies as every round of edit must create a new policy. Also, let me delete policies too!

**Screenshots**
![Screenshot 2024-09-26 at 6 22 33 PM](https://github.com/user-attachments/assets/c2a3ebfa-b82c-4a28-91a0-3d66b93f283c)

**Comment by YohannParis** [comment]
Not to be solve yet.

**Comment by pascaleproulx** [comment]
The result of clicking `Create New Intervention' button should be the same as when opening a new create intervention policy operator: i.e. it should just show an undefined intervention and policy, let the user fill it, and when clicking on Save (which should be enabled), then the modal would show up to name it.
