### ISSUE TITLE
[BUG]: PDF extraction is supposed completed but nothing shows up in the Document page

### ISSUE THREAD

**Issue by liunelson** [DARPA-ASKEM/terarium#4965]
- Scenario: Model extraction
- Step: 2.3
- Link to the project: https://app.staging.terarium.ai/projects/34e7b955-f408-4e8b-be27-9429480ad6aa/workflow/26486066-01d1-4870-b687-6c99fc8901a0

**Describe the issue**

After the test document is uploaded, a notification says that the PDF extraction is completed:
![Screenshot 2024-09-27 at 9 35 55 AM](https://github.com/user-attachments/assets/6b04c017-9222-4d07-a240-19218096d380)

However, the document page never shows any extraction - only "PDF Extractions are processing please come back in some time..."

Plugging this document into `Create model from equations` operator, no extraction show up there either.

**Comment by YohannParis** [comment]
Not an issue anymore per new design
