### ISSUE TITLE
[TASK]: Create model-configuration from FUNMAN output

### ISSUE THREAD

**Issue by YohannParis** [DARPA-ASKEM/terarium#4979]
**Task Description:**

Update the `ValidateModelConfigHandler.java` file to perform the following tasks:
- Create a `Model` instance using the AMR response provided by FUNMAN.
- Utilize the `service/modelConfiguration/modelConfigurationFromAMR` method to generate a `ModelConfiguration` from the created `Model`.
- Ensure the generated `ModelConfiguration` is included as an output of the operator.

**Comment by shawnyama** [comment]
duplicate
