### ISSUE TITLE
[BUG]: Incorrect column info in the Dataset page of an uploaded CSV file with `,` in column headers

### ISSUE THREAD

**Issue by liunelson** [DARPA-ASKEM/terarium#4994]
**Describe the bug**

Question 1 of Problem 4 of the monthly demo scenarios asks the user to extract some datasets to Terarium. They can be simply downloaded from the paper website and uploaded to Terarium.

However, the Dataset page of the flow rates CSV file has two minor bugs:
1. The data table is parsed correctly (4 columns) but the "Column information" section shows 6 columns; the issue is probably the `,` in the column headers.
2. "Enrich metadata with AI" failed to provide summary info for 4 of the 6 columns in the info section, probably due to the above issue.

![Screenshot 2024-09-30 at 5 47 55 PM](https://github.com/user-attachments/assets/519c3d33-22e1-4dce-b9d1-620830d16054)

**To Reproduce**
1. Upload this CSV file [flow rates in the wastewater treatment plant_Total_flow.csv](https://github.com/user-attachments/files/17196743/flow.rates.in.the.wastewater.treatment.plant_Total_flow.csv)
3. Go to its Dataset page
4. Note the number of columns in the info section vs. the data table
5. Note the lack of summary info for 4 of the columns in the info section.

**Comment by dvince2** [comment]
Related to: https://github.com/DARPA-ASKEM/terarium/issues/4970
