### ISSUE TITLE
[BUG]: If simulate still can't handle long values why don't we convert to float?

### ISSUE THREAD

**Issue by dgauldie** [DARPA-ASKEM/terarium#5029]
- Scenario: simulate
- Step: 
- Link to the project: https://app.staging.terarium.ai/projects/17086c53-c727-4607-a0b1-e661aed048b9/workflow/b9871aa9-d1b2-4307-b0e7-37c92bdc41a2?operator=40f7e45b-41db-4963-8749-bc83d1d05842

**Describe the issue**

![Image](https://github.com/user-attachments/assets/d7697796-ae62-416d-88ac-71279fea5c3c)

**Comment by Tom-Szendrey** [comment]
Notes: 
[broken model.json](https://github.com/user-attachments/files/17316862/broken.model.json)
[working model.json](https://github.com/user-attachments/files/17316861/working.model.json)
[stacktrace.txt](https://github.com/user-attachments/files/17316871/stacktrace.txt)
