### ISSUE TITLE
[BUG]: No charts return for validate model config

### ISSUE THREAD

**Issue by brittanykondo** [DARPA-ASKEM/terarium#5033]
The screenshot shows what I entered for settings and sanity checks:
![Image](https://github.com/user-attachments/assets/90af326b-547b-4d6f-a9b5-47afb416317c)
After clicking run, no charts were returned so I couldn't complete Step 5 of the test.

**Comment by YohannParis** [comment]
Will be fixed once @shawnyama is done with the charts

**Comment by shawnyama** [comment]
When this happens it's due to funman's output not having any boxes. In those cases there is no data to be rendered for the charts.
