### ISSUE TITLE
[BUG]: Cant save for re-use the model in edit model

### ISSUE THREAD

**Issue by blanchco** [DARPA-ASKEM/terarium#5035]
- Scenario: Model edit test
- Step: 4.1
- Link to the project: https://app.staging.terarium.ai/projects/f96d8f8b-1391-4d4c-be3a-f55db2ac8483/workflow/58462915-91fb-4ef7-8a01-6669cd508d24?operator=80895dca-c859-4c5d-bd3c-56b024687414

**Describe the issue**
I know there's a PR in the pipeline to fix this but figured it would be okay to log this anyways. The issue is simply that there is no save for re-use button in edit model

**Comment by YohannParis** [comment]
Fixed
