### ISSUE TITLE
[FEAT]: Transition matrices in the model graph viz should have the subject-outcome etc. dropdown (default: subject-controllers if controllers exist)

### ISSUE THREAD

**Issue by liunelson** [DARPA-ASKEM/terarium#5063]
**Is your feature request related to a problem? Please describe.**

1. The transition matrices are always showing the subject-outcome view; this is misleading at best in the case where there are controllers.
2. Users are often confused by the meaning of subject-outcome, subject-controllers, etc. When there are controllers, they almost always expect to see the subject-controllers view.

**Describe the solution you'd like**
1. Add the same dropdown as in the parameter matrix view to the transition matrix view.
2. If controllers exist, the default view for both the transition matrices (in the model graph) and parameter matrices (in the parameter table) should be subject-controllers.

**Comment by dgauldie** [comment]
The dropdown is no longer necessary
