### ISSUE TITLE
[BUG]: Upload of a document not finishing

### ISSUE THREAD

**Issue by YohannParis** [DARPA-ASKEM/terarium#5123]
**Describe the bug**
 
* Sometimes, when sending a document, the status can be stuck to 90% at the end of the `textExtractionFuture.get()`.
But we might never get the last 10% that allow us to close the notification and clear/clean it.

![Image](https://github.com/user-attachments/assets/e2130832-2b21-4c50-a128-9edae3c073f7)

* The percentages give to the document extraction are not accurate, here you can see that the table extraction has started but the percentage is still 0%

![Image](https://github.com/user-attachments/assets/b1ea2a48-3e39-425d-97fd-3e0880e6ea37)

**Comment by dgauldie** [comment]
we should clean up the back-end to ensure we have better notifications and messages
