### ISSUE TITLE
[BUG]: Automap not working on Calibrate

### ISSUE THREAD

**Issue by YohannParis** [DARPA-ASKEM/terarium#5129]
- Scenario: [Optimize](https://github.com/DARPA-ASKEM/terarium/blob/main/testing/manual/optimize.md)
- Step: 3.2
- Link to the project: https://app.staging.terarium.ai/projects/ec1c9313-26f9-4d35-8e60-ecb491eafaa0/workflow/e3e056f3-f119-4e9d-983b-6702cf9706c1?operator=9b726808-6d7a-4ae1-bf8d-5c44b13bc3af

**Describe the issue**
The Auto map feature is not working, and it removes the empty fields from the interface.

![Image](https://github.com/user-attachments/assets/90f693cd-2eb9-49fd-af7d-bea1e8612a6e)

**Comment by Tom-Szendrey** [comment]
-automap not working -> this is only mapping concepts, not string match. I will adjust this i think thats the issue youre bringing up?
-and it removes the empty fields from the interface. -> This is no longer true.
