### ISSUE TITLE
[BUG]: Optimize success criteria is wrong when using Fast defaults

### ISSUE THREAD

**Issue by YohannParis** [DARPA-ASKEM/terarium#5134]
- Scenario: [Optimize](https://github.com/DARPA-ASKEM/terarium/blob/main/testing/manual/optimize.md)
- Step: 4.a.4
- Link to the project: https://app.staging.terarium.ai/projects/ec1c9313-26f9-4d35-8e60-ecb491eafaa0/workflow/e3e056f3-f119-4e9d-983b-6702cf9706c1?operator=f2a48251-8ea7-43d5-b2d0-113715f48244

**Describe the issue**
This results makes no sense.

![Image](https://github.com/user-attachments/assets/9cffc6ab-ef14-4e82-9319-51e4e492646f)

**Comment by YohannParis** [comment]
We should update the FAST setting to be a bit more useful

**Comment by Tom-Szendrey** [comment]
The result when using the fast preset is not meant to make sense. 
We are looking the most optimal result while setting our "looking" parameters to essentially "dont look"
We have functional evaluations set to 0 and iterations set to 1

**Comment by YohannParis** [comment]
Okay, I'm not sure we should have a fast preset if it's job is not to useful to the user.
