### ISSUE TITLE
[BUG]: need to pre-filled interventions chart display input

### ISSUE THREAD

**Issue by YohannParis** [DARPA-ASKEM/terarium#5135]
- Scenario: [Optimize](https://github.com/DARPA-ASKEM/terarium/blob/main/testing/manual/optimize.md)
- Step: 4.a.4
- Link to the project: https://app.staging.terarium.ai/projects/ec1c9313-26f9-4d35-8e60-ecb491eafaa0/workflow/e3e056f3-f119-4e9d-983b-6702cf9706c1?operator=f2a48251-8ea7-43d5-b2d0-113715f48244

**Describe the issue**
Intervention input field to visualize the chart should be pre-filled, and not selected afterwards
maybe something related to `setOutputSettingDefaults`

 ![Image](https://github.com/user-attachments/assets/23765b3a-d4c4-408a-a151-eecb99176e0c)

**Comment by blanchco** [comment]
@YohannParis After taking a quick look, it looks like this has already been fixed/implemented.  The interventions that the attached policy already has will automatically be selected when the user presses "Run".

https://github.com/user-attachments/assets/6595d8cc-3243-4891-b2d0-edbb7131e11e


After optimization:

![Image](https://github.com/user-attachments/assets/8e9a4bd4-84ef-4777-bc9a-7b12999766aa)
