### ISSUE TITLE
[BUG]: Equations in document are cut off in `Create model from equations` extractions

### ISSUE THREAD

**Issue by liunelson** [DARPA-ASKEM/terarium#5166]
**Describe the bug**

Holly tried to use `Create model from equations` on a document with a sizable list of equations (15).
The equations seem to have been cut-off:
* Equations 13, 14, 15 are completely missing
* Equations 11, 12 are missing their right-most 20% (`rho P_v` and `rho P_s`)

![Image](https://github.com/user-attachments/assets/33672b47-bea0-4083-bd41-84139557d8b7)

**To Reproduce**
1. Connect this paper (https://app.staging.terarium.ai/projects/eb16a7a8-17f1-4295-a938-146969f8f1a1/workflow/7fa3148d-01f6-4ef6-a4d6-64402d004d07?operator=bb280e6f-c836-45ed-adc8-aadff1ea5d5d) to a `Create model from equations` operator)
2. Look at the extractions for Page 23

**Additional context**
I speculate that this may be a failure in the OCR step where the equation image is too small to capture the entire length of the equations.

**Comment by dgauldie** [comment]
We can't change the model at this point
