### ISSUE TITLE
[BUG]: Opening Calibrate operation fails to render node

### ISSUE THREAD

**Issue by mloppie** [DARPA-ASKEM/terarium#5187]
- Scenario:  https://github.com/DARPA-ASKEM/terarium/blob/main/testing/manual/optimize.md
- Step: Clicking the Calibrate from the Plus sign off a configure model in a new workflow
- Link to the project: https://app.staging.terarium.ai/projects/d0d0e082-8556-4906-ad84-cfb7d5be9afb/overview

**Describe the issue**
After attempting to create the Calibrate operator the link renders but not the node:

![Image](https://github.com/user-attachments/assets/5d59ad15-9471-4ce5-8316-67bc39773455)

The node(s) do appear after refreshing the browser:

![Image](https://github.com/user-attachments/assets/f5595d88-bf49-4238-b151-6374e8d493ed)

**Comment by mwdchang** [comment]
Should be fixed in https://github.com/DARPA-ASKEM/terarium/pull/5174
