### ISSUE TITLE
[BUG]: Mapping of `Calibrate` operator is stuck in "Please wait..." indefinitely

### ISSUE THREAD

**Issue by liunelson** [DARPA-ASKEM/terarium#5196]
**Describe the bug**

Molly from MITRE reported this bug and I was able to reproduce it in their project on Prod.
https://app.terarium.ai/projects/15e6144e-d8ac-4438-b9e4-a6704ef5a41c/workflow/9f4dec9a-088b-4443-bf4c-daa4bbf799e7

The "Mapping" section of the `Calibrate` operator is either incredibly slow or stuck indefinitely in "Please wait...".
This happens with Dataset 1 but not Dataset 2. It's likely because of the size of Dataset 1 (~10 MB or >10,000 rows).

Dataset 1: https://drive.google.com/file/d/1L8uGgNzo2KEqk_IvXgwXtShEICVD_Ww8/view?usp=drive_link
Dataset 2: https://drive.google.com/file/d/1HghnPA0_ET8qeCiM_DxylMPj9P4VouC5/view?usp=drive_link

**To Reproduce**
1. Upload any model and select some default configuration
2. Upload Datasets 1 and 2
3. Connect each to a `Calibrate model` operator
4. See that "Mapping" of the operator connected to Dataset 1 is stuck

**Expected behaviour**

The operator might be trying to load the entire dataset when it only needs to read the first row to get the column headers.
It might also be doing this _before_ loading the model and reading its state variables and observables.
In any case, the usage of a large dataset shouldn't be bogged down already at the calibration settings step.

**Screenshots**

![Image](https://github.com/user-attachments/assets/360c6011-1f61-41b1-959f-28ca8ab08ccf)

**Additional context**

**Comment by Tom-Szendrey** [comment]
There are two issues here that will be fixed
1) With a large datafile it can take a few seconds to finish initializing. Testing that first datafile of 10mb it will take approximately 6 seconds locally
2) when plugging in a simulation result we the `columns` field in the dataset asset is not filled in and therefore we do not have columns to select
