### ISSUE TITLE
[BUG]: Calibrate still does not like longs

### ISSUE THREAD

**Issue by dgauldie** [DARPA-ASKEM/terarium#5199]
- Scenario: calibrate
- Step: 3.4
- Link to the project: https://app.staging.terarium.ai/projects/17086c53-c727-4607-a0b1-e661aed048b9/workflow/39960c4b-20ae-4c03-b6e3-eed9c9617641?operator=fab5c564-49d8-4244-8197-9be915cb2452

**Describe the issue**

Pyciemss still does not like longs

![Image](https://github.com/user-attachments/assets/0bafba0a-86ec-4841-a17b-d628c67888a4)

**Comment by Tom-Szendrey** [comment]
This will be resolved by the ciemss team
Can we close this?

https://github.com/ciemss/pyciemss/issues/618
