### ISSUE TITLE
[BUG]: Loss charts in calibrate node and drilldown do not match

### ISSUE THREAD

**Issue by mloppie** [DARPA-ASKEM/terarium#5234]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
1. Generate a calibrate node
2. Open the Calibrate drilldown

**Expected behaviour**
Graphs should be the same

**Screenshots**
![Image](https://github.com/user-attachments/assets/4add2f2d-cbe4-4747-af20-b3445872a1b6)
![Image](https://github.com/user-attachments/assets/e1952874-0156-4fb0-865b-ee8a5fdf2644)

**Additional context**
Project is shared with the QA user: http://localhost:8080/projects/513fa68a-a0c0-4ca7-93d6-09f04ae9fc31/workflow/58e2d76a-8426-4186-8aa2-e490c6a5f3f9

**Comment by mwdchang** [comment]
Force client-side sort
