### ISSUE TITLE
[BUG]: Exact match results should be displayed first

### ISSUE THREAD

**Issue by hvasque14** [DARPA-ASKEM/TERArium#525]
**Describe the bug**
When searching by a DOI, the paper with the DOI that matches exactly is not displayed as the first result. 

**To Reproduce**
Search by doi: 10.1101/2020.12.22.20248736
The paper that has this doi as an exact match is the third and fourth result. 
The first two papers do not have doi's that match the query.

**Expected behavior**
The papers with the exact matching doi should be displayed at the top.

**Screenshots**
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/116816354/214352576-6d483a41-91d5-4221-8a5f-8cc22568fa0f.png">

**Additional context**

**Comment by shawnyama** [comment]
Found why this is the case. In `search-results-list.vue` the `filteredAssets` returned is a concatenation of all the documents with xdd extractions and then all the ones without them. This stems from the `searchResults` a.k.a. `dataItems` being limited by the `SearchResults` type that separates normal `results` and `xddExtractions`.

To have everything in the correct order these two attributes need to combined in some way, probably in the backend. Ideally everything should just be under `results`.

**Comment by dvince2** [comment]
There was actually a specific issue when searching for DOIs, which ended up being resolved with issue #596 .  You may see duplicate entries still when searching for DOIs - this is a known issue with some entries on xDD
