### ISSUE TITLE
[BUG]: Exact title search does not return results

### ISSUE THREAD

**Issue by hvasque14** [DARPA-ASKEM/TERArium#526]
**Describe the bug**
When I search for a specific paper by the title, it does not return any results; however, when I search for the same paper by the doi, it returns the exact paper. 

**To Reproduce**
Search: 
REAL-TIME MECHANISTIC BAYESIAN FORECASTS OF COVID-19 MORTALITY, no results are found.
Then search by the paper doi: 10.1101/2020.12.22.20248736, it finds the paper with the exact title that we initially searched

**Expected behavior**

**Screenshots**
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/116816354/214355061-7ffa53a2-fdb8-453f-8858-578247a94ddd.png">
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/116816354/214355210-ebf74304-d044-40fe-84c2-cbf141c2107e.png">

**Additional context**

**Comment by dvince2** [comment]
This issue appears to have been resolved at some point in the last week with another fix - closing off
