### ISSUE TITLE
[BUG]: Re-running `Validation configuration` does not consistently give new results

### ISSUE THREAD

**Issue by liunelson** [DARPA-ASKEM/terarium#5299]
- Scenario: Validate configuration
- Step: 6
- Link to the project: https://app.staging.terarium.ai/projects/34e7b955-f408-4e8b-be27-9429480ad6aa/workflow/ae644619-7fe5-40d7-bb90-880c447ba9a4

**Describe the issue**
Running a validation, changing the settings, and then re-running it does not consistently produce new results (i.e. always `Result - 1` showing).
It seems that this happens when the second run possibly fails without any error.

**Comment by shawnyama** [comment]
Can't reproduce
