### ISSUE TITLE
[BUG]: Copying a public project creates an error and never finishes copying

### ISSUE THREAD

**Issue by pascaleproulx** [DARPA-ASKEM/terarium#5333]
**Describe the bug**
Copying a public project creates an error and never finishes copying

**To Reproduce**
1. Go to Public projects on staging and click the vertical stacked dots icon at the bottom right corner of the project 'Demo Oct 2024' for example
2. See errors

This seems to be an issue just with that project. I tried with another random one and it worked as expected.

**Comment by YohannParis** [comment]
The issue is that the project contains old assets wich do not match the new format.

**Comment by YohannParis** [comment]
@kbirk if we could just pass over the assets that have an issue and keep going non-blocking assets.
