### ISSUE TITLE
[BUG]: Model configurations can not be used

### ISSUE THREAD

**Issue by dgauldie** [DARPA-ASKEM/terarium#5348]
- Scenario: model-configuration-extracting-variables
- Step: 3.8
- Link to the project: https://app.staging.terarium.ai/projects/3ff970f6-12ef-4691-9a16-3a03f99b38af/workflow/ee7e127e-b2dd-48b3-b1e9-fc883d4ae039?operator=617e7bb8-b1e7-40c7-bbd0-f46fe2f915fd

**Describe the issue**

After extracting configurations, the user is unable to select or use any configurations.

Even after reloading the page, the user can't apply configurations

**Comment by asylves1** [comment]
Unable to recreate issue
