### ISSUE TITLE
[BUG]: Save for reuse not working in transform dataset

### ISSUE THREAD

**Issue by jryu01** [DARPA-ASKEM/terarium#5353]
- Scenario: https://github.com/DARPA-ASKEM/terarium/blob/main/testing/manual/transform-dataset.md
- Step: 3-8
- Link to the project: https://app.staging.terarium.ai/projects/47f6fb2b-9a7b-4269-85a4-300ee1eb5437/workflow/8834d9e5-5ac6-409a-be36-8175f1b60057?operator=55b17fce-df46-4bbb-8629-dbef93aab74a

**Describe the issue**
![Image](https://github.com/user-attachments/assets/708a2897-0144-4759-82f3-267c55ef17ab)

Save for reuse button is not working and there's no way to save the updated/created dataset as new dataset.

**Comment by mloppie** [comment]
Fixed in https://github.com/DARPA-ASKEM/terarium/pull/5412
