### ISSUE TITLE
[BUG]: Deleting from Cart removes all items

### ISSUE THREAD

**Issue by hvasque14** [DARPA-ASKEM/TERArium#536]
**Describe the bug**
When I delete one item from the cart it removes **all** items from the cart. 

**To Reproduce**
Add multiple items to the cart
Remove one item
All items will be removed

**Expected behavior**
Only the selected item should be removed

**Screenshots**

**Additional context**

**Comment by shawnyama** [comment]
I think this was fixed. If this is working properly on your end feel free to close the issue.
