### ISSUE TITLE
[BUG]: selection of checkboxes not sticking

### ISSUE THREAD

**Issue by YohannParis** [DARPA-ASKEM/terarium#5363]

**Comment by mwdchang** [comment]
If we can, turning off collaboration will help quite a bit here, then the UI doesn't need to worry about whether it is getting a valid update or potentially stale update from the database. This situation is seemingly reproducible if the DB is slow and trying to catch up with front end interactions.  So a scenario like this can occur
- UI: Click checkbox-A
- >> send event to DB
- UI: Click checkbox-B
- >> send event to DB
- ...
- << DB comes back, but it hasn't processed checkbox-B yet, so UI can mistaken that checkbox-B had been unchecked.

**Comment by mwdchang** [comment]
Attempt to address the issue is in this PR to selective update workflow
https://github.com/DARPA-ASKEM/terarium/pull/5422
