### ISSUE TITLE
[TASK]: Ensemble Calibrate Output Settings

### ISSUE THREAD

**Issue by Tom-Szendrey** [DARPA-ASKEM/terarium#5389]
- Add output settings to the ensemble calibrate
- Add existing chart components to this

Depends on https://github.com/DARPA-ASKEM/terarium/issues/5172
Figma link: https://www.figma.com/design/SLO56PGmGq7kFQRFCeaPsY/Terarium---September-2024?node-id=603-116&t=NDRd81PqXGRBcJ9a-1

**Comment by jryu01** [comment]
I'll close this ticket as we have most of basic features are already in for the ensemble calibrate outputs. For subsequent tasks, we can create separate tickets.
