### ISSUE TITLE
[BUG]: Model Configuration Extraction - 0 values not correctly extracted

### ISSUE THREAD

**Issue by Tom-Szendrey** [DARPA-ASKEM/terarium#5419]
- Scenario: https://github.com/DARPA-ASKEM/terarium/blob/main/testing/manual/model-configuration-extracting-variables.md
- Step: 4.6 -> `Gamma and P should be 0s` Did not correctly extract these 0 values.
- Link to the project:  https://app.staging.terarium.ai/projects/f8501b9d-31ab-4551-bdef-c8e8cd3c7491/workflow/0268376b-f71f-4dc0-84f4-33b2cf641261

**Describe the issue**
When following step 4.6 I checked the matrix values for Gamma and P which were expected to be 0 based off of the test.
These values were the only thing that did not correctly get extracted in this entire test

**Comment by shawnyama** [comment]
when I tried it this week the S, I, R values were empty too

**Comment by dgauldie** [comment]
The tests are wrong, not the application.
