### ISSUE TITLE
[TASK]: Investigate using Vegalite memory usage: rendering images

### ISSUE THREAD

**Issue by mwdchang** [DARPA-ASKEM/terarium#5452]
### Task
Investigate if we can use Vegalite to render an image instead of an interactive chart, in particular for the operator nodes on the workflow graph.

### Motivation:
We have seen Vegalite taking up a lot of memory in chart renderings, especially in the case of simulations where the sampling is quite high (e.g. > 200). Vegalite seem to retain the data points in memory so the memory can grow with the number of samples taken.

Rendering into an image instead of an interactive chart may alleviate the memory usage, assuming we can dispose the rendering context and memory is released.

### Misc
Alternatively, we can consider disabling the tooltip layer for operator node graphs

**Comment by jryu01** [comment]
Resolved in https://github.com/DARPA-ASKEM/terarium/pull/5642
