### ISSUE TITLE
[BUG]: Model cards sometimes have empty `Transitions` tables

### ISSUE THREAD

**Issue by liunelson** [DARPA-ASKEM/terarium#5478]
**Describe the bug**

I have this model here:
[Test 2.json](https://github.com/user-attachments/files/17723407/Test.2.json)

It's a model AMR JSON that is produced by `Create Model from Equations` (SKEMA) and it can also be ingested by MIRA's `template_model_from_amr_json` without error or warning, giving _three_ templates.

**To Reproduce**

Steps to reproduce the behaviour:
1. Create a workflow
2. Add a `Create model from equations` operator
3. Paste in these equations
```latex
\frac{d S}{d t} = -\gamma S - \mu R
\frac{d R}{d t} = \gamma S
```
4. Click `Run`
5. Note that it says `Transitions (2)` but the transition table is empty

**Expected behaviour**

I imagine that this bug is due to this edge case where the AMR has _two_ transitions but MIRA ingests it and create _three_ templates. We probably should generate all the tables in the model drilldown using the AMR and _not_ converting the AMR into a MIRA template model and then reading things from that.

**Screenshots**

![Image](https://github.com/user-attachments/assets/dd3078af-a468-4c07-a28a-a399420c7773)

**Comment by YohannParis** [comment]
Ignored, as SKEMA is going to be replaced by MIRA.
