### ISSUE TITLE
[BUG]: Refreshing the page causes duplicate operators and "Configure Model" to lose its state

### ISSUE THREAD

**Issue by liunelson** [DARPA-ASKEM/terarium#5505]
**Describe the bug**

I have this workflow 
https://app.staging.terarium.ai/projects/5e884b3e-0be1-48d7-b627-184ec15c1d5f/workflow/dd4b1147-d0c3-4798-84d8-efc2ee39b676

Refreshing the page caused this nasty mess of operators:
* Broken edges
* Duplicated operators
* "Configure model" turned yellow and lose its state

**Screenshots**

Before:
![Image](https://github.com/user-attachments/assets/5b80ccef-e336-4ef3-813c-7d39fd859034)

After:
![Image](https://github.com/user-attachments/assets/8db0af8c-548a-4795-b1d8-714caa12e724)

**Comment by YohannParis** [comment]
* We should display the name of other users that are editing the same workflow
* Write a manual test for collaboration (@liunelson )
