### ISSUE TITLE
[BUG]: Stratify notebook has some limitations when asked what states/parameters to stratify on

### ISSUE THREAD

**Issue by blanchco** [DARPA-ASKEM/terarium#5510]
- Scenario: https://github.com/DARPA-ASKEM/terarium/blob/main/testing/manual/stratify-notebook.md
- Step: 3.7 & 3.8
- Link to the project: https://app.staging.terarium.ai/projects/5a317c32-3668-4b3e-acb2-fda35aef3bf6/workflow/927ee327-a2c5-4b92-ad7a-946404b62402?operator=d3612e33-88a8-48e3-815b-fc08269ef8dd

**Describe the issue**
The notebook doesn't seem to understand or provide the ability to not stratify parameters/states as eluded to in the test cases:

The example given:
Stratify my model by the locations Toronto, Montreal, Vancouver, Yellowknife where Montreal population can interact with Toronto population but not vice versa. Do not stratify the "I" state and "β" parameter.
```
model = stratify(
    template_model=model,
    key= "Location",
    strata=['Toronto', 'Montreal', 'Vancouver', 'Yellowknife'],
    structure= [['Montreal', 'Toronto']],
    directed=True, # Should the reverse direction conversions be added based on the given structure?
    cartesian_control=False,
    modify_names=True,
    concepts_to_stratify=None, 
    params_to_stratify=None, 
    concepts_to_preserve = ['I'],
    params_to_preserve = ['β'],
    param_renaming_uses_strata_names = True
)
```

I tried multiple times to run this but I do not get an code that includes the `concepts_to_preserve` or `params_to_preserve` keys
![Image](https://github.com/user-attachments/assets/f4e26312-eac6-4f0a-b8c6-4e7050b4126d)

**Comment by liunelson** [comment]
Should be solved by https://github.com/DARPA-ASKEM/askem-beaker/pull/169
