### ISSUE TITLE
[BUG]: Cannot create intervention policy

### ISSUE THREAD

**Issue by kbirk** [DARPA-ASKEM/terarium#5516]
Attempting https://github.com/DARPA-ASKEM/terarium/blob/main/testing/manual/simulate.md

Cannot create new policy or save the existing one.

![Image](https://github.com/user-attachments/assets/8bed8894-0df5-4cde-93dd-7f2cd9803f9a)

**Comment by mwdchang** [comment]
Probably because of our validation check not accepting an empty policy?

**Comment by Tom-Szendrey** [comment]
Can you share your workflow link? 
We have an intervention validation check to ensure that time values are not negative and we do not have duplicates within our intervention definition
If you wrote a valid intervention and it did not work that is an issue
If you wrote an invalid intervention and it was not clear that it was invalid that is an issue
