### ISSUE TITLE
[BUG]: Preview of tables/figures does not include search term

### ISSUE THREAD

**Issue by hvasque14** [DARPA-ASKEM/Terarium#555]
**Describe the bug**
The preview for tables and figures does not include the search term used and instead is a general description.  Documents however show at least one truncated block of text with the search term highlighted.

**To Reproduce**
1. Search for the term "Github".
2. Notice that the preview for tables and figures is a description of the table/figure.
3. Notice that the preview for the documents is actually a snippit of text which includes the word "Github" at least once.
4. Notice that when clicking into the table/figure, the word "Github" can be found highlighted.

Github URL should be extracted and displayed in the preview. 

**Screenshots**
First result in the list is a table/figure with no "github" present in the preview:
![image](https://user-images.githubusercontent.com/30270901/217034137-54d12c52-f7a5-4790-a952-178bc6c43127.png)

Clicking on the table/figure, you can scroll until you find the search term highlighted:
![image](https://user-images.githubusercontent.com/30270901/217034257-ec86d167-1ad0-41ca-9193-c9d6fe710180.png)

Documents however show truncated text blocks with the search term highlighted:
![image](https://user-images.githubusercontent.com/30270901/217034411-18e57794-8787-4061-a4c7-1ffc86081c20.png)

**Additional context**

**Comment by dvince2** [comment]
After doing a bit of a dive, it turns out that highlights are entirely unavailable for extractions.  I've spoke with Ian from the xDD team and they will be updating the extractions API this week to allow for highlights to be returned to us.  Once thats in place we can work on this issue.

**Comment by iross** [comment]
I've added an `include_highlights` parameter to the dev instance of the ASKEM object endpoint: https://xdddev.chtc.io/askem/object?query_all=test&include_highlights=true. Take a look and let me know if there are any tweaks you'd like to see!

**Comment by dvince2** [comment]
Thanks @iross ! Will likely be getting back to this later this week.

**Comment by iross** [comment]
I deployed a change that will bring back a `_highlight` field for both the object and within the parent documentBibjson field.
