### ISSUE TITLE
[BUG]: Links in reference should be clickable

### ISSUE THREAD

**Issue by hvasque14** [DARPA-ASKEM/TERArium#557]
**Describe the bug**
When reviewing references in the preview panel, URLs should be clickable so that the user does not need to copy and paste. 

**To Reproduce**
Open the preview panel for a paper, open the references, references with URLs are not clickable

**Expected behavior**
References with URLs should be clickable

**Screenshots**
<img width="437" alt="image" src="https://user-images.githubusercontent.com/116816354/214885396-5225a6e2-1cdd-42c3-a69c-c9971ed7d914.png">

**Additional context**

**Comment by echl** [comment]
@hvasque14 can you provide the name of an example paper that has links as references? Having trouble finding one.
