### ISSUE TITLE
[TASK]: Adjust controller edges in model graph

### ISSUE THREAD

**Issue by liunelson** [DARPA-ASKEM/terarium#5570]
**Describe the task**

Currently, the model graph shows two dashed lines with arrows for every controller in a controlled transition (e.g. `S` => `E` controlled by `I`).

We want to change this behaviour to _one_ dashed line without arrow for every controller.

The reason is that the arrows represent flow of individuals between compartments and controllers do not flow to/from transitions. 

![image-20.png](https://github.com/user-attachments/assets/56897687-587a-4042-a99d-3d589dcd05db)

**Comment by mwdchang** [comment]
Addressed in https://github.com/DARPA-ASKEM/terarium/pull/5612
