### ISSUE TITLE
[BUG]: Edge case with parameter matrix - when a parameter is reused in multiple templates, its matrices are empty (except other)

### ISSUE THREAD

**Issue by liunelson** [DARPA-ASKEM/terarium#5578]
**Describe the bug**

I have this SIR model from a paper (Hewitt et al. 2024).

The model equations are:
```
d s / d t = - R * y * s * i
d i / d t = R * y * s * i - y * i
d r / d t = y * i
```

We stratify this model by `N` locations over all the state variables and parameters `s, i, r, R, y`. Thus, the parameter `y` becomes a matrix `y_k` for `k = 0, 1, ..., (N-1)`.

When I view this parameter matrix in `Configure Model` operator, the default view is `subjectOutcome` and it's completely empty.

Model AMR:
[Hewitt Model A (NY counties) (1).json](https://github.com/user-attachments/files/17834999/Hewitt.Model.A.NY.counties.1.json)

**To Reproduce**
Open the matrix view of the parameter `y`

**Expected behavior**
Since `y_k` is used in many templates, the default and only view probably should just be "other". I suggest locking the dropdown to just "other".

**Screenshots**
![Image](https://github.com/user-attachments/assets/2aa201e0-8901-47d6-8dd4-4d95098cb665)

**Comment by mwdchang** [comment]
I suspect this is correct, but you have a big sparse matrix and didn't scroll enough?
![Image](https://github.com/user-attachments/assets/1bf8c6be-4d52-4dbd-a4d2-af4a2bec424d)


Schematically the orange and blue rectangles are where the values are, where each colour represents one of `R * y * s * i` and `y * i`.

![Image](https://github.com/user-attachments/assets/6c69442e-f88c-4c1e-8f65-130490c4f07e)
