### ISSUE TITLE
[BUG]: Query text field in the "Transform Dataset" operator cuts off when I paste in a long string.

### ISSUE THREAD

**Issue by liunelson** [DARPA-ASKEM/terarium#5581]
**Describe the bug**
When I paste a long string in the LLM query text field in the "Transform Dataset" operator, the top is cut off.

**Expected behavior**
The text field should not be cut off!

**Screenshots**
![Image](https://github.com/user-attachments/assets/4555d469-50eb-4067-894a-5703f2d43dcc)

**Comment by Tom-Szendrey** [comment]
https://github.com/DARPA-ASKEM/terarium/pull/5579
