### ISSUE TITLE
[BUG]: "Simulate" operator thumbnail missing baseline curve, different from drilldown charts.

### ISSUE THREAD

**Issue by liunelson** [DARPA-ASKEM/terarium#5656]
**Describe the bug**
The thumbnail of charts on "Simulate" operators is different from those in the drilldown view, e.g. missing the baseline curve.

![Image](https://github.com/user-attachments/assets/146636b1-d4cc-49dd-b47d-5e75d2899105)

![Image](https://github.com/user-attachments/assets/632e12e6-28dd-47a4-8234-57aad75f7bf5)

**Comment by mwdchang** [comment]
I wonder if this is a reactivity problem ....

**Comment by mwdchang** [comment]
This should be addressed in this PR https://github.com/DARPA-ASKEM/terarium/pull/5746
