### ISSUE TITLE
[FEAT]: Too many charts show up as thumbnail of the "Create intervention policy" operator - should user-selected and/or capped

### ISSUE THREAD

**Issue by liunelson** [DARPA-ASKEM/terarium#5659]
**Describe the bug**

The SIDARTHE model is an example of a modelling use case where the intervention policy intervened on a lot of parameters.

![Image](https://github.com/user-attachments/assets/03a54866-4afc-4a1b-bba6-6ea0e175a644)

The "Create intervention policy" operator currently puts one chart per intervened parameter as thumbnail. This looks _crazy_ in the workflow view.

We could have the user select what they want to see as thumbnail or just capped the number to 2-3.

**Comment by YohannParis** [comment]
The solution is to display the written version of the intervention policy instead of the charts.!

for example what we display in simulate operator.
[Image](https://github.com/user-attachments/assets/3f18280b-34fc-4c89-b7b1-617a04d8c0ab)
