### ISSUE TITLE
[BUG]: Failed running calibrate ensemble

### ISSUE THREAD

**Issue by jryu01** [DARPA-ASKEM/terarium#5684]
- Scenario: https://github.com/DARPA-ASKEM/terarium/blob/main/testing/manual/ensemble-calibrate.md
- Step: 3-8
- Link to the project: https://app.staging.terarium.ai/projects/47f6fb2b-9a7b-4269-85a4-300ee1eb5437/workflow/c10c9683-770a-42b9-a10b-4a9a159f56a9?operator=a2a2ab00-fad9-4461-a4c7-7175c4486569

![Image](https://github.com/user-attachments/assets/46c6a9d3-d507-4104-91f0-fcc65146cdcb)

**Comment by Tom-Szendrey** [comment]
This appears to be an issue with the intermediate results task:
[server logs calibrate ensemble fail.txt](https://github.com/user-attachments/files/17979413/server.logs.calibrate.ensemble.fail.txt)

**Comment by Tom-Szendrey** [comment]
I have re-ran this and another (normal instead of fast preset) while keeping `dirichlet_alpha` at 1 for each model
https://app.staging.terarium.ai/projects/e76d2579-abd8-43ba-a9c5-5c4bfea384f7/workflow/3416c376-402c-4202-9bf5-d1eb50437e93
