### ISSUE TITLE
[TASK]: Scenario: Sesnsitivty chart updates

### ISSUE THREAD

**Issue by YohannParis** [DARPA-ASKEM/terarium#5695]
@pascaleproulx to fill the requirement.

**Comment by jamiewaese-uncharted** [comment]
### Two variables (H, I) and one parameter (Beta) selected.
If only one parameter is selected for sensitivity analysis, we draw a histogram with 10 buckets, with a rug plot beneath it for the variable. 
![Image](https://github.com/user-attachments/assets/a9350d35-b9c5-4e58-b378-235cd1cd509d)
![Image](https://github.com/user-attachments/assets/d40ecf2c-fc08-4acf-9b5e-3a6e9f152aeb)


### Two variables (H, I) and three parameters (Beta, Gamma, Kappa) selected.
If more than one parameter is selected, we draw a pairwise comparison chart for each parameter, sort of like this:
![Image](https://github.com/user-attachments/assets/d164bdeb-65fb-4c35-8f69-c7fc8e681c8a)

![Image](https://github.com/user-attachments/assets/e8758ceb-20f2-438a-802d-2e6914a85451)
