### ISSUE TITLE
[TASK]: Simulate: Small multiples (comparison charts)

### ISSUE THREAD

**Issue by YohannParis** [DARPA-ASKEM/terarium#5697]
In the simulate operator, comparison charts options, we need:
- a checkbox to display small mulitples.
- a checkbox to share the same Y axis or not.

**Comment by jryu01** [comment]
FYI: here's a ticket with detailed information. you might want to look at it.
https://github.com/orgs/DARPA-ASKEM/projects/3/views/2?pane=issue&itemId=83681251&issue=DARPA-ASKEM%7Cterarium%7C5172
