### ISSUE TITLE
[BUG]: App crash if click 'Re-run all cells' after reopening a Transform dataset with existing code

### ISSUE THREAD

**Issue by pascaleproulx** [DARPA-ASKEM/terarium#5702]
**Describe the bug**
App crash if click 'Re-run all cells' after reopening a Transform dataset with existing code

**To Reproduce**
1. Add a dataset to a new workflow
2. Plug it into a transform dataset
3. In transform dataset, use a prompt to do some change like "Remove column xxx and rename the new dataframe d2."
4. Exit the driildown and reopen the Transform dataset operator
=> You see the yellow banner and only d1 in the available dataframe that can be saved for reuse (i.e. the session was closed on exit). This is all as expected.
5. Click on 'Re-run all cells' button as instructed by the yellow banner.
=> the app crashes: see Ah, snap page

**Screenshots**
![Image](https://github.com/user-attachments/assets/585cd9fc-529c-4bfa-bd9d-2f25aaf5e2ec)

**Comment by dgauldie** [comment]
I see it with this project

https://app.terarium.ai/projects/a6781dcc-becc-481c-b35b-1fe649c0b693/workflow/a300a5a4-3a02-4721-b371-ce9323dfec4e?operator=935eb92d-f9eb-4dc8-9c76-e8331d12bd49

![Image](https://github.com/user-attachments/assets/b8594248-dd8a-4719-91bd-9e7587ce502a)
