### ISSUE TITLE
[BUG]: "Aw, Snap!" every time I click "Re-run all cells" in a "Transform dataset" operator

### ISSUE THREAD

**Issue by liunelson** [DARPA-ASKEM/terarium#5807]
**The Bug**
"Aw, Snap!" every time I click "Re-run all cells" in a "Transform dataset" operator

Refreshing the page afterwards brings me back to the operator. 

I remade this notebook in a new "Transform dataset" operator - same problem.

**To Reproduce**
1. Go to https://app.staging.terarium.ai/projects/dd4412d9-8b54-4d56-b063-a8e21b461316/workflow/de8b1596-ca85-443f-b4e7-dd4e3cb462d9?operator=d1c3806d-928a-4c69-996c-0ac6a77eb492
2. Click on 'Re-run all cells"
3. See error

**Expected behavior**
Just re-run all the cells of the notebook.

**Screenshots**
![Image](https://github.com/user-attachments/assets/e56dac23-7b94-4b87-b57d-38bf5f81f413)

**Comment by YohannParis** [comment]
Duplicate
