### ISSUE TITLE
[BUG]: The loss chart should appear in the drilldown as calibrate runs

### ISSUE THREAD

**Issue by pascaleproulx** [DARPA-ASKEM/terarium#5826]
**Expected behavior**
The loss chart should be displayed both on the node thumbnail and in the drilldown while running. When calibrate is done, keep the loss chart inside but not on the node thumbnail.

**Screenshots**
![Image](https://github.com/user-attachments/assets/01450a2b-195a-4c6c-aeaa-a3b98f72406e)

![Image](https://github.com/user-attachments/assets/3d2d712c-5e93-49a3-8161-238afd9ecc83)

**Additional context**

**Comment by Tom-Szendrey** [comment]
I will be confirming this after this has been merged https://github.com/DARPA-ASKEM/terarium/pull/5810
