### ISSUE TITLE
[BUG]: Calibrate never gets passed 0.1% progress

### ISSUE THREAD

**Issue by pascaleproulx** [DARPA-ASKEM/terarium#5827]
Probably related to the pyciemss bug but wanted to capture this context to make sure.

**Screenshots**
![Image](https://github.com/user-attachments/assets/bdaa226b-4ed7-4d57-ad27-ed185128380a)

**Comment by Tom-Szendrey** [comment]
I will look into this further once https://github.com/DARPA-ASKEM/terarium/pull/5810 is merged as this PR is touching a lot of polling
