### ISSUE TITLE
[BUG](simulate-ensemble): have to reload page to see dropdown options

### ISSUE THREAD

**Issue by shawnyama** [DARPA-ASKEM/terarium#5831]
- Scenario: simulate ensemble
- Step: 3.4
- Link to the project: https://app.staging.terarium.ai/projects/48b5ee70-418b-4939-b3d7-49db8a1346e1/workflow/f1377a59-a352-455b-a60a-750abd1c52d0

**Describe the issue**
- After clicking run I get notifications saying the run has completed
- Once I click add chart, the dropdown options are empty
- In order for the options to appear I have to reload the page<img width="1490" alt="Image" src="https://github.com/user-attachments/assets/8251f8c4-1750-4cbc-a2db-c745f43eaa95" />

**Comment by Tom-Szendrey** [comment]
It should be noted that the ensemble-simulate is still using old charts.
As far as I am aware this is the only thing still using these old charts (tera-simulate-chart)
Once we update our output settings this should also cover this issue
