### ISSUE TITLE
[BUG]: deleting a workflow causes errors

### ISSUE THREAD

**Issue by pascaleproulx** [DARPA-ASKEM/terarium#5837]
On prod

**To Reproduce**
1. Add a new workflow
2. Delete it by clicking on the `x` in the resources panel
=> see errors

**Screenshots**
![Image](https://github.com/user-attachments/assets/db08b4e5-054c-4115-ae78-77bb12535a66)

**Comment by YohannParis** [comment]
Non reproducible
