### ISSUE TITLE
[BUG]: Facets disappear when filtering on models

### ISSUE THREAD

**Issue by hvasque14** [DARPA-ASKEM/TERArium#600]
**Describe the bug**
the facets disappear when filtering on facets on the model space

**To Reproduce**
go to model space
search for a model
select a facet
The facets disappear

**Expected behavior**
Should see the facets and what I am filtered on. 

**Screenshots**
<img width="847" alt="image" src="https://user-images.githubusercontent.com/116816354/215605399-d72603d2-4693-4cdb-a7c5-78970a479fad.png">
<img width="847" alt="image" src="https://user-images.githubusercontent.com/116816354/215605399-d72603d2-4693-4cdb-a7c5-78970a479fad.png">
![Uploading image.png…]()

**Additional context**

**Comment by Tom-Szendrey** [comment]
I am trying to recreate this on my side, are you able to help me with any of the following:
Was this when you hit a specific facet? Or a facet that had only 1-2 results?
Was this every time you tried to filter on the model page?
Did you previously filter on other pages before the model page? 

Thanks!!
