### ISSUE TITLE
Modeling tool research

### ISSUE THREAD

**Issue by mwdchang** [DARPA-ASKEM/TERArium#62]
Pam had provided a listing of modeling tools that might be relevant for ASKEM program
- Simulink: https://www.mathworks.com/products/simulink.html
- GleamViz: http://www.gleamviz.org/

ABMs:
- Netlogo http://www.netlogoweb.org/launch#http://www.netlogoweb.org/assets/modelslib/Curricular%20Models/epiDEM/epiDEM%20Travel%20and%20Control.nlogo
- GAMA: https://gama-platform.org/
- MESA: https://mesa.readthedocs.io/en/main/tutorials/adv_tutorial.html#adding-visualization

Misc
- EPI Grass: https://www.youtube.com/watch?v=UwZ-KWV0oGU

**Comment by bencodrington** [comment]
Marking as completed. Our notes can be found here:

https://docs.google.com/document/d/1xxJ7LGLi_yp600zMNzlNZC_pP8exhhyyD3p--r6CJRA/edit#
