### ISSUE TITLE
[BUG]: Fix links in Explorer Article Preview panel

### ISSUE THREAD

**Issue by jamiewaese-uncharted** [DARPA-ASKEM/TERArium#638]
The links in the Explorer Article Preview panel need some tweaks:
1) The DOI link should open in a new tab so we don't lose our place in Terarium
2) The Open PDF button should not be shown if it doesn't actually link to a PDF. It shouldn't link to the publisher page. That's what the DOI link is for.

<img width="518" alt="preview window links" src="https://user-images.githubusercontent.com/120480244/216685459-a23f1480-88ef-4685-9b5a-75dc6a630f29.png">

**Comment by echl** [comment]
@jamiewaese-uncharted Do we know if any of these links actually open to pdfs?

**Comment by YohannParis** [comment]
We should have a talk about link opening on new tabs, this is not a good user experience.
