### ISSUE TITLE
[TASK]: Adjust text styling and chevron color in accordion titles in the Explorer preview panel

### ISSUE THREAD

**Issue by jamiewaese-uncharted** [DARPA-ASKEM/Terarium#659]
The numbers beside the accordion labels should have less visual emphasis. Unfortunately they're currently in the same span as the label so we can't treat them separately. Let's give them their own span and class name, then make the font size smaller and the color subdued.

![Preview panel accordion design tweak](https://user-images.githubusercontent.com/120480244/217311299-c0195ee2-b545-4350-a200-02a3040f0512.png)

Also, the font-weight of the label is too strong. Let's remove the semi-bold and use regular (400) here. It should look like this:
![image](https://user-images.githubusercontent.com/120480244/217312513-29e65ab7-cf9a-4105-bcea-cc5df6f3485a.png)

Finally, the expand/collapse chevron would look better if it was subdued color.

**Comment by Tom-Szendrey** [comment]
*Not a super quick fix to have 2 unique fonts in an Accordion header. Will look into in the future

**Comment by jamiewaese-uncharted** [comment]
Great job with this Shawn but one request... Can we adjust the vertical alignment or whatever so the numbers are in line with the text? They currently look like superscript.
![image](https://user-images.githubusercontent.com/120480244/222813308-1bb937f5-8441-45da-921a-564ae9c72144.png)
