### ISSUE TITLE
[TASK]: Text styling for the filter chips at the top of the explorer screen

### ISSUE THREAD

**Issue by jamiewaese-uncharted** [DARPA-ASKEM/Terarium#695]
The font weight of the filter chips at the top of the Explorer results panel is too strong. It would look better at 400.

CURRENT
![Monosnap TERArium 2023-02-09 15-14-51](https://user-images.githubusercontent.com/120480244/217926909-37e2d3b0-d03f-4456-a2b9-59c07a87b938.png)

PROPOSED
![Monosnap TERArium 2023-02-09 15-02-18](https://user-images.githubusercontent.com/120480244/217926818-9cb0b6ca-84e4-45f0-bdbc-9da6000ce6f7.png)

Also, I'd like to put the value in its own span and make the color primary. See design...

DESIGN
![image](https://user-images.githubusercontent.com/120480244/217927135-7cf57710-02eb-4198-9882-f95b2d51d7eb.png)

**Comment by shawnyama** [comment]
Similar challenge to [#659](https://github.com/DARPA-ASKEM/TERArium/issues/659). Limited by PrimeVue component.
