### ISSUE TITLE
[TASK]: Add API key to xdd calls

### ISSUE THREAD

**Issue by dvince2** [DARPA-ASKEM/Terarium#717]
**Describe the task**
From @iross 

> I'd like to give you an API key to include in requests just so I can do a easy validation check on my side for a simple "show images only to authorized systems" functionality

**Task Items**
- [ ] Add API key to XDD calls

**Additional context**
Note that this issue is currently blocked on some changes needed on xDD

**Comment by iross** [comment]
Config and data pushed -- good to go on the xDD side. API key provided via Slack message to @dvince2
