### ISSUE TITLE
[TASK]: Loading state for home screen project and paper cards

### ISSUE THREAD

**Issue by jamiewaese-uncharted** [DARPA-ASKEM/Terarium#745]
Currently when we load the home page we see an awkward-looking screen for several seconds until the projects and paper data loads:
![image](https://user-images.githubusercontent.com/120480244/220379267-0cd750af-832a-4506-adb2-6728b3750f02.png)

We can improve the experience by adding an empty/loading state to the project and paper cards, like this:
![image](https://user-images.githubusercontent.com/120480244/220379847-736d39b2-78d5-4ca2-b42e-8e6d17c08319.png)

Here is a library for creating the placeholder rectangles with a slight shimmer effect:
https://github.com/michalsnik/vue-content-placeholders

**Comment by echl** [comment]
@jamiewaese-uncharted primevue has a skeleton component, might we want to use those?

**Comment by jamiewaese-uncharted** [comment]
Yes, absolutely, use the PrimeVue component. Thanks.
