### ISSUE TITLE
[BUG]: Repeatedly clicking on the same related project paper thumbnail (and dismissing the modal) shuffles the preview images

### ISSUE THREAD

**Issue by tangopapatime** [DARPA-ASKEM/terarium#777]
**Describe the bug**
Repeatedly clicking on the same related project paper thumbnail (and dismissing the modal) shuffles the preview images.  A GIF is worth is a thousand words.  See below.

**To Reproduce**
Steps

1. Go to the Home Page
2. Click on a project preview
3. Close the modal
4. Repeat
5. Watch related paper previews shuffle

**Expected behavior**
will let @jamiewaese-uncharted chime in.

**Screenshots**
![odd](https://user-images.githubusercontent.com/98172806/221913827-cd035b59-cbac-4b57-aca5-e5b63859a8f8.gif)

**Additional context**
N/A

**Comment by Tom-Szendrey** [comment]
This is because these pictures are all mock images. The vast majority of XDD articles we looked into do not have images to display. In order for the demo to have more to visually chew on we have a bunch of images that we assign (at random) to these empty images
