### ISSUE TITLE
[TASK]: Paper preview modal on home page needs styling 

### ISSUE THREAD

**Issue by jamiewaese-uncharted** [DARPA-ASKEM/terarium#785]
The paper preview modal on our home page needs styling.

CURRENT
![image](https://user-images.githubusercontent.com/120480244/222495113-f4a045dd-8a3e-4ee2-9f97-843c476f4a8e.png)

PROPOSED
![Monosnap TERArium HMI Designs - PrimeVue version 2023-03-02 11-53-03](https://user-images.githubusercontent.com/120480244/222497940-a50147e8-e04d-46da-bda5-36c5a2b9237a.png)

**Comment by Tom-Szendrey** [comment]
Figures + sticky footer + links to search still to be done in future (Busy atm with other things)

**Comment by jamiewaese-uncharted** [comment]
I made some progress with this but it's incomplete: 
- The whole paper preview should show, not just the header and abstract.
- The "Add to project" button should be sticky at the bottom of the modal dialog, always visible, the content scrolls beneath it.

<img width="1586" alt="image" src="https://user-images.githubusercontent.com/120480244/229838830-bf87f9ed-73a6-480d-8a83-fb290d618209.png">
