### ISSUE TITLE
[TASK]: Multiple design tweaks to the notes side panel

### ISSUE THREAD

**Issue by jamiewaese-uncharted** [DARPA-ASKEM/Terarium#807]
### Code

Clean up the code so that it:
* uses services instead of calling it from within `<tera-project>`.
* Saves notes per project/assets in `data-service`
* Add proper error handlings on all API calls, etc.

### Design

Nice work on the notes side panel. Here are some design tweaks to make it pretty:
- The width of the side panel should be 240 px
- There should be 16 px of padding on the left and right
- There should be 16 px of padding between different notes
- The font size should be caption (12 px) for everything
- There should be a borderless dropdown selector at the top of each note for users to select which section of their notes document they want to assign each note to. The options should be: Unassigned, Abstract, Intro, Methods, Results, Discussion, References, and "+ Add section" where you can add another section and name it whatever you want.
- The author and creation date should be on one line
- The "Add note" button should just be a text button (see design)
- The empty text input field should not be shown by default. It should only be revealed when the user clicks "Add note". (See design).
- The text input field border should be the same grey as all other input fields, not black. 
- There should be an 3-dot menu button in the corner. Clicking it should open a menu with two options: Edit and Delete. If you click delete, another option appears with "Are you sure?". (See design)

CURRENT
<img width="346" alt="image" src="https://user-images.githubusercontent.com/120480244/223769735-a7deee51-45d0-4ea2-99ae-2249653d8036.png">

DESIGN
Overall
<img width="225" alt="image" src="https://user-images.githubusercontent.com/120480244/223777851-cb7d7f4b-8cf0-44e5-b232-cf005f78d18d.png">

Default note
<img width="185" alt="image" src="https://user-images.githubusercontent.com/120480244/223775368-21f5ba80-1e0d-4ced-8fb3-3cf27d676373.png">

Options menu
<img width="186" alt="image" src="https://user-images.githubusercontent.com/120480244/223775557-a7d8ec44-bc1f-4570-be91-b6729d9efbb4.png">

Delete confirmation
<img width="187" alt="image" src="https://user-images.githubusercontent.com/120480244/223775632-cb26cc79-5f7c-4ef1-b626-474ae9143276.png">

Edit mode
![image](https://user-images.githubusercontent.com/120480244/223777024-2ff44a99-71fd-4763-ba9b-4dcf6dd9ff91.png)

**Comment by echl** [comment]
@jamiewaese-uncharted I suggest instead of having an 'add section' item, to use the vue dropdown menu's existing option to allow the user to enter new sections into the dropdown menu directly i.e. it functions as a dropdown and input field
