### ISSUE TITLE
Papers to Code to Model to Mathematic Formula

### ISSUE THREAD

**Issue by YohannParis** [DARPA-ASKEM/Terarium#820]
- [x] #822
    - [x] Checkout GitHub API to see what we can do with a GitHub link
    - [x] Implement prototype of a _Import_ button next to GitHub link to let user select a file
    - [x] Open such file within the _Code View_ 
- [x] #821
    - [x] Checkout [MIT API ](https://github.com/DARPA-ASKEM/mit-matching) API link: `http://100.26.10.46/#/`
    - [x] Try at least to test code to formula endpoint 
    - [x] Implement it in the hmi-server as endpoint
    - [x] Open formulat from the _Code View_ within [model preview ](https://www.figma.com/file/lOoGAsDwLfMmP3u5qzKHRh/Terarium-Designs?node-id=9547-256792&t=808gXKhjyiD9Q6oR-4)
- [ ] Update provenance, metadata, etc. within `data-service`

**Comment by liunelson** [comment]
Google Doc documenting the different conversions:
https://docs.google.com/document/d/1chiRJIrFodz8-GjOaGhtaqiHt8c2sMuEJgKLQxDatUo
