### ISSUE TITLE
Transformation selected code to Model / Mathematic Formula via MIT/SKEMA

### ISSUE THREAD

**Issue by YohannParis** [DARPA-ASKEM/Terarium#821]
- [ ] Checkout [MIT API ](https://github.com/DARPA-ASKEM/mit-matching) API link: `http://100.26.10.46/#/`
- [ ] Try at least to test code to formula endpoint 
- [ ] Implement it in the hmi-server as endpoint
 - [ ] Open formulat from the _Code View_ within [model preview ](https://www.figma.com/file/lOoGAsDwLfMmP3u5qzKHRh/Terarium-Designs?node-id=9547-256792&t=808gXKhjyiD9Q6oR-4)

**Comment by echl** [comment]
Most recent documentation is here https://github.com/mikecafarella/mitaskem/blob/main/demos/2023-02-01/mit-feb1-demo.ipynb
