### ISSUE TITLE
[BUG]: Facets disappear in model explorer

### ISSUE THREAD

**Issue by bgyori** [DARPA-ASKEM/Terarium#852]
**Describe the bug**
When visiting the model explorer page, the list of facets shows up but then disappears, leaving an empty Facets sidebar.

**To Reproduce**
1. Go to https://app.terarium.ai/app/#/
2. Click on Home -> Explorer -> Models

**Expected behavior**
Facets should not disappear

**Additional context**
The problem seems to goe away when reloading the page or navigating away and back again.

**Comment by pascaleproulx** [comment]
Problem no longer exists so closing.
