### ISSUE TITLE
[BUG]: Facet filtering for models doesn't seem to work

### ISSUE THREAD

**Issue by bgyori** [DARPA-ASKEM/Terarium#853]
**Describe the bug**
When clicking on a domain concept in the Facet filter sidebar in the model explorer, filtering doesn't seem to happen, all models are still shown.

**To Reproduce**
1. Go to Explorer -> Models
2. Click on "exposed population" on the Facets sidebar

**Expected behavior**
A single model should be shown (exposed population appears in 1 model according to the Facets Concepts list).

**Comment by dvince2** [comment]
This issue appears to be resolved with the facet work done yesterday. closing.
