### ISSUE TITLE
[TASK]: Dataset viewer: Add column summary histograms just above the datatable

### ISSUE THREAD

**Issue by jamiewaese-uncharted** [DARPA-ASKEM/Terarium#967]
We need more data visualization in this app!

One easy thing we can add that is also a huge boost for usability are summary charts above the columns of the data table. Kaggle does this. It helps users get a feeling for the content of the dataset.
![image](https://user-images.githubusercontent.com/120480244/230158123-59d6184a-f63f-4fff-be18-3e06aa37840e.png)

I think the easiest way for us to do this is to add a one-row table above our datatable, and insert PrimeVue charts into each cell based on the numbers in the column beneath it.

**NUMBERS**
By default, a column of numbers should be represented with a histogram. The maximum value should be written on top, and the minimum value written on the bottom. Tooltips for the bars would be nice, but aren't critical. In my mockups, the histograms have ten bins. 

Note, these histograms are vertical instead of the usual horizontal. It's based on Richard's design for Bloomberg. It solves the variable-width-columns problem because they can all be the same size, no matter how wide or narrow the column is.

If you click on a column header to sort the table based on that column (this is built into the datatable), it would be cool if the histogram changes to a line chart of the now-sorted numbers. This would show the distribution differently and it should feel very intuitive.

**STRINGS**
A list of strings should be represented with a simple table of the top three strings and their percentage

**INTERACTIVE BRUSHING**
A stretch goal that would be VERY cool is to add the plumbing to allow for a user to hover over a row in the table and the appropriate bar in the histogram above changes color. This helps users see where in the distribution each value happens to be. This was part of Richard's design for Bloomberg as well (though he added a line connecting each of the highlighted items). It would be nice to reproduce that here.

![image](https://user-images.githubusercontent.com/120480244/230161711-efa7b31f-22d4-448f-901f-a0c9275ee73c.png)

**Comment by Tom-Szendrey** [comment]
just as a reminder from a quick discussion:
-Jataware might be calculating some of these for us already - worth a check 
-Potential for future sampling depending on size of dataset we are making these histograms for
