### ISSUE TITLE
[BUG]: result selection is not reset when switching from models to datasets

### ISSUE THREAD

**Issue by dgauldie** [DARPA-ASKEM/terarium#991]
**Describe the bug**
The result selection is not reset when switching from model results to dataset results

**To Reproduce**
1. Go to the explorer view
2. Click on models and select the first model
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/4194153/232129626-5f79768b-2924-4aa1-a3c6-76d5b752ca04.png">
3. Switch to datasets
4. [ERROR] The first dataset shows that it is selected even though it is not
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/4194153/232129725-98320073-43d0-4a34-b4b5-eecae3a7e2e1.png">

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by shawnyama** [comment]
(can't reproduce was probably fixed)
